### ISSUE TITLE
My file is not getting upload

### ISSUE THREAD

**Issue by adityaunaik** [rest-assured/rest-assured#1006]
This is my code to rest my api to upload file

    given().auth().preemptive().basic("*****","****").contentType("multipart/form-data").multiPart("type", "SAMPLE_XML").
    multiPart("preview_file",new File("C://hello.xml")).
    multiPart("connector_id", "MTUyMjMyNTU0NTMwNA").
    when().post(Endpoint.FILE_CONTEXT_UPLOAD).

My API has a validation where it checks the file extension .xml when this request is made.For the above request my api doesnot receive .xml file extension and so it gives out 400 error

FYI the same request works fine using Postman

**Comment by adityaunaik** [comment]
Can someone help me here? A work around would be more appreciated

**Comment by johanhaleby** [comment]
It's impossible to help unless we know more about what the server expects.
Also please provide the response logs.

**Comment by adityaunaik** [comment]
Basically my server expect the file path along with file extention. below is the API response

Connection: close
Transfer-Encoding: chunked

{
    "status": 400,
    "message": "Only '.xml' files can be uploaded for provided 'type'",
    "response_data": {
        
    }
}

**Comment by johanhaleby** [comment]
Hmm perhaps you could try wireshark to see that the contents of the file
looks correct. Also make sure that the content-type is correct.

**Comment by adityaunaik** [comment]
Content type is definately form data since it works with postman

**Comment by anderfsilva** [comment]
I tested your code and it is working here.
I created a simple API using Spring. The MultipartFile created by Spring shows me the file extension correctly. As @johanhaleby said, check if the XML file is correct. Also note that my test API does not require to set the content-type.

Here is my Wireshark POST test:
```
POST /test HTTP/1.1
    [Expert Info (Chat/Sequence): POST /test HTTP/1.1]
    Request Method: POST
    Request URI: /test
    Request Version: HTTP/1.1
Authorization: Basic ...
Accept: */*
Content-Length: 732
Content-Type: multipart/form-data; boundary=tQflzV3n-yiV99o-Rc1_UmmZy0hTAVyY5kqTPUrc
Host: localhost:8080
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_60)
Accept-Encoding: gzip,deflate
[Full request URI: http://localhost:8080/test]
[HTTP request 1/1]
[Response in frame: 2015]
File Data: 732 bytes
```

**Comment by adityaunaik** [comment]
figured out what was wrong 
multiPart("preview_file", new File("C://hello.xml"), "application/xml").
this worked for me i had to provide the mime/type
