### ISSUE TITLE
Path Params custom regex

### ISSUE THREAD

**Issue by arg20** [rest-assured/rest-assured#1007]
I'm using vert.x which uses path parameters with colons: eg: `/users/:user_id`, rest-assured format is `/users/{user_id}`. I have all my app routes in an enum.

I'd like to reuse this enum in my tests, but rest assured demands that my path params are between curly braces which would force me to duplicate code replacing the vert.x format for the rest assured format. Is there any way to tell the library to use `:path_param` instead `{path_param}`?

**Comment by johanhaleby** [comment]
Hi, 

No there's no way to tell REST Assured that. REST Assured is inspired by Spring which uses curly braces. There are no plans to change this.

That being said maybe you could just bypass REST Assured's resolving of path parameters entirely if you like. There must exists some library out there that does something like `resolve("/users/:user_id", "2422")`. 

Regards,
/Johan
