### ISSUE TITLE
ResponseSpecBuilder can't be used with DetailedCookieMatcher

### ISSUE THREAD

**Issue by aldaris** [rest-assured/rest-assured#1014]
The expectCookie methods on ResponseSpecBuilder only allow Matcher<String> arguments, whilst ResponseSpecificationImpl exposes DetailedCookieMatcher as well.
The not so pretty workaround is to do this:

```java
        return new ResponseSpecBuilder()
            .expectStatusCode(200)
            .build().cookie("iPlanetDirectoryPro", detailedCookie().maxAge(-1));
    }
```

**Comment by johanhaleby** [comment]
Oh that's true. Good find and thanks for pointing out. Care to provide a pull request?

**Comment by aldaris** [comment]
Yepp, should be easy to do :)
