### ISSUE TITLE
CookieFilter can't handle multiple cookies set in the same response

### ISSUE THREAD

**Issue by runtarinn** [rest-assured/rest-assured#1016]
In case there are more than one Set-Cookie headers in the response, only the first cookie seems to be stored using CookieFilter.

The bug/issue is located in the extractResponseCookies method, when calling response.getHeader("Set-Cookie"), this method only returns the first "Set-Cookie" header found:
`    
public class CookieFilter implements Filter {
...
private List<Cookie> extractResponseCookies(Response response, CookieOrigin cookieOrigin) {

        Header setCookieHeader = new BasicHeader("Set-Cookie", response.getHeader("Set-Cookie"));
        try {
            return cookieSpec.parse(setCookieHeader, cookieOrigin);
        } catch (MalformedCookieException e) {
            return Collections.emptyList();
        }
    }
...
}
`

**Comment by runtarinn** [comment]
I have created this pull request to fix this issue:
https://github.com/rest-assured/rest-assured/pull/1017

**Comment by johanhaleby** [comment]
I've now merged the PR! Thanks for your help.
