### ISSUE TITLE
prettyPrint() method displays response in json twice

### ISSUE THREAD

**Issue by oleg--manzhos** [rest-assured/rest-assured#1026]
@Test
    public void prettyPrintTest(){
        Response yWing = given().contentType(ContentType.JSON)
                .when()
                .get("http://jsonplaceholder.typicode.com/posts/1");
        System.out.println(yWing.prettyPrint());
    }

The response is 

{
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
{
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

**Comment by britka** [comment]
@oleg--manzhos why do you use 
`System.out.println(yWing.prettyPrint());` ?
prettyPrint method itself prints the response body and returns the String.
So now it works as expected.

**Comment by johanhaleby** [comment]
Yes, prettyPrint() does indeed print and then returns the string. This is
as intended. You can also you prettyPeek if you don't want to return the
string but rather continue using the response.

**Comment by britka** [comment]
So I think this bug can be closed.

**Comment by johanhaleby** [comment]
Yes it probably should. But maybe you're asking for an additional method that doesn't "print" but only returns the prettified json? Perhaps something like that would make sense but then I'd like it to be a new issue and I'd like you do elaborate on the use case a bit more (i.e. why would you need this?)

**Comment by ivan-baranovski-intellectsoft** [comment]
@johanhaleby I have problem like you described above. Do you have any solution how I can return the prettified json but not print?
Thank you.

**Comment by oleg--manzhos** [comment]
Hey, do not put response.prettyPrint() into system.out.println. It will return response by itself

**Comment by ivan-baranovski-intellectsoft** [comment]
@oleg--manzhos Thank you for your response but unfortunately it is not possible in range of my framework. I attach response in my report and I should have response like String.

**Comment by testingtoolsco** [comment]
> @oleg--manzhos Thank you for your response but unfortunately it is not possible in range of my framework. I attach response in my report and I should have response like String.

the method prettyPrint() does 2 tasks:

1. Print the response body in beautiful format and 
2. Returns a string in pretty format, which you can use it where ever you want.

**Comment by oleg--manzhos** [comment]
> > @oleg--manzhos Thank you for your response but unfortunately it is not possible in range of my framework. I attach response in my report and I should have response like String.
> 
> the method prettyPrint() does 2 tasks:
> 
> 1. Print the response body in beautiful format and
> 2. Returns a string in pretty format, which you can use it where ever you want.

1. You can try to use ...when().log().all().... to get beautifully formatted response.
2. Try to evaluate response.prettyPeek() to use beautifully formatted response wherever you need.
