### ISSUE TITLE
Rest Assured basic auth issue

### ISSUE THREAD

**Issue by ademdogu** [rest-assured/rest-assured#1038]
I have an endpoint which works perfectly fine when I use Postman with Basic Auth. However, when I tried it in Rest Assured it returns 401. I have tried both different auth methods in rest assured and none of them worked for me so far. Need help!

>     RequestSpecification requestSpec;
>     String baseURI = "http://qa3-phoenix.labcorp.com";
>     String basePath = "/phx-rest/healthcheck/ping";
>     RestAssured.useRelaxedHTTPSValidation();
>     RestAssured.baseURI = baseURI;
>     requestSpec = new RequestSpecBuilder()
>                 .setContentType(ContentType.JSON)
>                 .build();
> 
>         Response response = RestAssured
>                 .given()
>                     .spec(requestSpec)
>                     .auth().basic("username","password")
>                 .when()
>                     .get(basePath)
>                 .then()
>                     .extract().response();

It also worked with Postman when I have an Authorization header with the value of "Basic" + base64 encoded username:passoword. However, it returns 401 on rest assured.

**Comment by johanhaleby** [comment]
Try preemptive basic auth:

```
.auth().preemptive().basic("username","password")
```
