### ISSUE TITLE
In Rest Assured, how to maintain the session which is created by previous request.

### ISSUE THREAD

**Issue by Aditya1209** [rest-assured/rest-assured#1044]
Example : First i will call a login request which creates session, the next subsequent request which i made should be in same session and will applicable on logged in account.

I am not able to achieve this using Rest Assured, i tried all possible ways suggested in Rest Assured documents but no luck. Please help me with this.

Note : The above mentioned thing is working fine in postman.

**Comment by johanhaleby** [comment]
Have you tried the [SessionFilter](https://github.com/rest-assured/rest-assured/wiki/Usage#session-filter)?

**Comment by Aditya1209** [comment]
I have tried it but no luck. Actually my application creates session as soon as login but we are not using any auth.form .. our application built on react so do I need to do some thing else ?

**Comment by johanhaleby** [comment]
Have you tried the CookieFilter? :)

**Comment by Aditya1209** [comment]
Thanks johan its working for me when i used CookieFilter.
