### ISSUE TITLE
Java 10: ResolutionException duplicate package names among rest-assured.jar and xml-path.jar

### ISSUE THREAD

**Issue by chagen19** [rest-assured/rest-assured#1051]
I am getting the following exception during application startup with Java 10:

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules xml.path and rest.assured export package io.restassured.assertion to module commons.logging

```
As I understand this is related to the fact that rest-assured-3.1.0.jar and xml-path-3.1.0 both contain the same package **io.restassured.assertion**. Is there a workaround for this?

Here is my java version info:
$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**Comment by johanhaleby** [comment]
Hmm I'm not aware of any workaround myself. I'd prefer not having to break
backward compatibility. Is there anything we can do?

**Comment by johanhaleby** [comment]
Thanks Tomasz. It would be very very helpful if you could help out with
this.

**Comment by johanhaleby** [comment]
I've moved the XmlAssertion class to a new package, hopefully this will resolve it.
