### ISSUE TITLE
Support properties injection

### ISSUE THREAD

**Issue by johno1985** [rest-assured/rest-assured#1060]
It would be nice if rest-assured supported the DI of a properties object without having to explicitly add a DI container like Pico or Spring to the test project

**Comment by johanhaleby** [comment]
@johno1985 Thanks for your suggestion, but what's your use case for this? It definitely sounds to me  like this would be out-of-scope for the REST Assured project.

**Comment by johno1985** [comment]
Not really. My use case is that I need a properties file to be able to run the tests on different machines/environments and that I would like to be able to access these properties throughout my test code

**Comment by johanhaleby** [comment]
I see. Then I would say that it's better to be able to pick a "DI" framework/library of choice instead of building something into REST Assured. Also I think runners like TestNG has something like this built-in.

**Comment by johno1985** [comment]
I am currently using JUnit. Do you know of a way to achieve this in JUnit?

**Comment by johanhaleby** [comment]
You can use any library that deals with properties. For example if using Spring you could just inject properties as you normally would using `@Value` or `@ConfigurationProperties`. Or you can use something like [Owner](http://owner.aeonbits.org/). I'm going to close this issue now.
