### ISSUE TITLE
not able to add Query Params to Get request  (I am using io.restassured)

### ISSUE THREAD

**Issue by decentboy5** [rest-assured/rest-assured#1067]
Hi Team, 

I am using "io.restassured"  for get request. below is the sample code for it. some how. it is not woking as expected. it would be great, if someone helps us. 
we are framework implementation stage. everything works fine .except query params. 

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

String uri="http://abc.allow.com"
RestAssured.baseURI = uri;
RequestSpecification httpRequest = RestAssured.given();
httpRequest.param("expand", "details").param("filter", "10003");
response=httpRequest.request(Method.GET);

**Comment by johanhaleby** [comment]
What error do you get?

**Comment by decentboy5** [comment]
its not taking it as original request, when i did it from fidder/postman. everything working fine. 

{"status":"success","data":{"status":"failure","statusCode":"500","statusDescription":"The server encountered an unexpected condition which prevented it from fulfilling the request."}}

**Comment by decentboy5** [comment]
One more thing, 
I am using "io.restassured", 
Can you give me the working sample code like below. 


String uri="http://abc.allow.com"
RestAssured.baseURI = uri;
RequestSpecification httpRequest = RestAssured.given();
httpRequest.param("expand", "details").param("filter", "10003");
response=httpRequest.request(Method.GET);

**Comment by 379753498** [comment]
public restAssuredUtil(String baseURI)
	{
		RestAssured.baseURI=baseURI;
	}
	
	
	public Response GetResponse(String url, HashMap<String, String> parameters,	HashMap<String, String> heders) {

		return given().params(parameters).headers(heders).when().get(url);

	}

**Comment by decentboy5** [comment]
![capture](https://user-images.githubusercontent.com/30362271/45742817-7603d600-bc18-11e8-8d40-957e2480b3ed.png)

**Comment by johanhaleby** [comment]
There are several working examples in the [examples](https://github.com/rest-assured/rest-assured/tree/master/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java) project. For example [this](https://github.com/rest-assured/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java/JSONGetITest.java) one.

**Comment by decentboy5** [comment]
Johanhleby, 
                     thanks for your quick response. 
my only query.. i am using some different pattern compare to all examples. 

please help me with the below code. whats wrong with the code . I am suspecting something wrong in the below code. but not able to find out.  

**My Get call with params is   :**    http://abc.allow.com?$expand=details&$filter=10002


String uri="http://abc.allow.com"
RestAssured.baseURI = uri;
RequestSpecification httpRequest = RestAssured.given();
httpRequest.param("expand", "details").param("filter", "10003");
response=httpRequest.request(Method.GET);

is anything needs to be changed.

**Comment by johanhaleby** [comment]
Well you could just do `RestAssured.get("http://abc.allow.com?$expand=details&$filter=10002")`

**Comment by decentboy5** [comment]
Yes. Because those 2 are query params... not parameters...
Here is my confusion...

So , is it ok to pass query params like above ? 

Or is there any other way .

**Comment by decentboy5** [comment]
Thank you so much. it worked for me.

cheers.......!
