### ISSUE TITLE
RestAssured fails to parse responses with cookies that has numbers out of signed decimal range 

### ISSUE THREAD

**Issue by Mjl33** [rest-assured/rest-assured#1069]
A request results in a response that has a cookie with a large number 
fails with `NumberFormatException`
e.g. for response with cookie `set-cookie: Max-Age=20000000`

I believe it's because cookies are parsed with `Integer.parseInt(s, 10)` which limits the range to signed integer decimal

**Comment by danielblokus** [comment]
Correct me if I'm wrong but the RFC2616 says that max-age should be integer.

**Comment by jsmyczek** [comment]
It doesn't say that it should be at most 31-bit integer, though.

**Comment by mradomyski** [comment]
Issue still valid after 2 years. Maybe worth consideration?

**Comment by johanhaleby** [comment]
@mradomyski Please provide a PR
