### ISSUE TITLE
Not logging response body if status code is different from what I was expecting.

### ISSUE THREAD

**Issue by nrstaber** [rest-assured/rest-assured#1074]
I have this code:
`given().when().get(path).then().log().ifValidationFails().statusCode(404);`
If the Status Code comes back different I thought it would log the response body, but now it does not log much of anything.

**Comment by johanhaleby** [comment]
Can you give me a full example?

**Comment by nrstaber** [comment]
`given()
        .header(headerCreater(session))
        .queryParams(paramList)
        .contentType("application/json")
        .accept("application/json")
        .when()
        .get(path)
        .then()
        .log().ifValidationFails()
        .statusCode(404)
        .body("status", is("NOT_FOUND"));`
If the body comes back different it logs the json that is being return, but if the statusCode comes back different from a 404 it does not log.

I was going to show the error, but it looks like it got fixed today and now is showing the response body
