### ISSUE TITLE
Post Body data missing

### ISSUE THREAD

**Issue by hanymorcos** [rest-assured/rest-assured#1079]
I'm trying to use Rest Assured to post XML content to postman echo. The echo response for data is empty. I tried in a variety of methods to post the data but the echo response is always empty. I'm attaching a snippet of code below. I look forward for some insight. 

    private Response response;
    private ValidatableResponse xml;
    private RequestSpecification request;

        RequestSpecBuilder requestSpecBuilder = new RequestSpecBuilder();
        byte[] bytes = "<tag attr='value'>/".getBytes( "UTF-8" );
        requestSpecBuilder.setBody(bytes);
        requestSpecBuilder.setContentType(ContentType.XML);
        request = given()
                .spec(requestSpecBuilder.build())
                .log().body()
                .when();

         response =      request.post("https://postman-echo.com/post");
        System.out.println("My response:   " + response.asString());

**Comment by hanymorcos** [comment]
I figured it out.

**Comment by pintea-cos** [comment]
> 

What have you done to fix the issue? I have the same problem>
