### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by enexusde** [rest-assured/rest-assured#1086]
License is not filled.

**Comment by enexusde** [comment]
Line 190 of the license has detailed informations how to fill the license.

**Comment by johanhaleby** [comment]
Sorry I still don't get it

**Comment by enexusde** [comment]
Steps to reproduct: 

1. Open file: https://github.com/rest-assured/rest-assured/blob/master/LICENSE
2. Scroll down to line 190
3. Read the line 190 carefully.
4. Tell me what software is licensed here.

**Comment by johanhaleby** [comment]
@enexusde Thanks Peter, now I get it :) I thought that you were talking about the [generic license](https://www.apache.org/licenses/LICENSE-2.0) or the license headers in the javadoc.
