### ISSUE TITLE
Does ifValidationFails should use the PrintStream define in LogConfig?

### ISSUE THREAD

**Issue by plum117** [rest-assured/rest-assured#1087]
I'm trying to make the response log in my logger when the status validation failed. However, for an unknown reason it was not logging into my console.

After some debugging, I found out that the ifValidationFails actually create a new PrintStream to output the logging instead of using the one define in default log config.

See io.restassured.internal.ValidatableResponseOptionsImpl#ifValidationFails(io.restassured.filter.log.LogDetail, boolean)

```
    public T ifValidationFails(LogDetail logDetail, boolean shouldPrettyPrint) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        responseSpec.getLogRepository().registerResponseLog(baos);
        return logResponse(logDetail, shouldPrettyPrint, ps);
    }
```

Which I think should be:

```
    public T ifValidationFails(LogDetail logDetail, boolean shouldPrettyPrint) {
        PrintStream ps = config.getLogConfig().defaultStream();
        responseSpec.getLogRepository().registerResponseLog(baos);
        return logResponse(logDetail, shouldPrettyPrint, ps);
    }
```

**Comment by johanhaleby** [comment]
Thanks for the investigation @plum117. It sounds right that we shouldn't create a new PrintStream. Perhaps you could supply a PR?

**Comment by plum117** [comment]
I'll try to find some times for that.

**Comment by Bisk1** [comment]
@johanhaleby @plum117
I think the original code is actually correct. The new PrintStream() is supposed to store the log output temporarily and it is always populated. I think this was forced by the fact the request and response printing filters are executed before validation takes place. Then, if validation actually fails, the temporary stream in logRepository is used to copy the log into the defaultStream. This is done in method ResponseSpecificationImpl.logRequestAndResponseIfEnabled().
If you will make this change, response will be logged even if validation passes.

**Comment by plum117** [comment]
@Bisk1 thanks to have validate my comment. I reviewed my code and retried `.log().ifValidationFails()` and it is logging correctly. Not sure what was the problem at the time finally!

Can be closed as not a bug
