### ISSUE TITLE
How do I upload file with parameters?

### ISSUE THREAD

**Issue by georgedelacruz213** [rest-assured/rest-assured#1089]
Hi,

How do I upload file with parameters?

given().
        .param("key","value")
        .param("key","value")
        .param("key","value")
        .multiPart(new File("/path/to/file.zip")).
when().
        post("/upload")
.then()
        .statusCode(200).log().body();

Thanks!

**Comment by johanhaleby** [comment]
Please use the mailing list, http://groups.google.com/group/rest-assured.

**Comment by georgedelacruz213** [comment]
Hi @johanhaleby 

tried looking for a similar problems like I have (https://groups.google.com/forum/#!searchin/rest-assured/upload|sort:date/rest-assured/6j3JwM5BazY/cWxRCeu3BAAJ), still no luck, can you help me with this issue? Thanks!
