### ISSUE TITLE
Getting the actual call

### ISSUE THREAD

**Issue by shakye** [rest-assured/rest-assured#1091]
Hi,
I'm getting an error response when I call a URL which shouldn't result an error. Is there anyway I can get the actual call to the server ?. I can't disable URL encoding because I have some URLs which should be encoded.
Is there any work around for this?
Thanks.

**Comment by apodkutin** [comment]
Hi @shakye,
What about request logging like this `given().log().everything()` ? 
Will it help you?

**Comment by shakye** [comment]
@apodkutin thank you so much...it worked
