### ISSUE TITLE
How to globally log for all requests?

### ISSUE THREAD

**Issue by lazycodeninja** [rest-assured/rest-assured#1092]
Would it be possible to add a global method to enable logging for all requests, similar to 
`RestAssured.enableLoggingOfRequestAndResponseIfValidationFails()`?  I'd like to enable this for all our tests, without having to add this to every request in every test.

**Comment by johanhaleby** [comment]
Yes you can probably use a [RequestSpecification](https://github.com/rest-assured/rest-assured/wiki/Usage#specification-re-use) that contains a [logging filter](https://github.com/rest-assured/rest-assured/wiki/Usage#request-logging) ([RequestLoggingFilter](http://static.javadoc.io/io.rest-assured/rest-assured/3.2.0/io/restassured/filter/log/RequestLoggingFilter.html) and [ReponseLoggingFilter](http://static.javadoc.io/io.rest-assured/rest-assured/3.2.0/io/restassured/filter/log/ResponseLoggingFilter.html)).
