### ISSUE TITLE
Create differently configured gson mappers on the fly

### ISSUE THREAD

**Issue by adam66** [rest-assured/rest-assured#1102]
I have a REST API which is wild and untamed, and each endpoints can accept or return variations on the JSON, sometimes properties missing, sometimes extra properties present, sometimes date formats or boolean formats different etc etc.

I'd like to use 

```
    given().spec(mySpec)
                .body(myObjects, customObjectMapper)
                .when()
                .post("different/again/argh")
                .then()
                .assertThat()
                .statusCode(HttpServletResponse.SC_OK);

```
where **customObjectMapper** is different each time, based on a **GsonObjectMapperFactory** implementation which I can supply with the appropriate date formats or ExcludeStrategies. 

I have set up my RequestSpecification with a RestAssuredConfig and a ObjectMapperConfig but I can't see how to use your API to get an ObjectMapper to feed into **RequestSpecificationImpl.body(obj, mapper)**

**Comment by apodkutin** [comment]
Hi @adam66, if I've understood it correctly, you need to get the `objectMapper` from your own `GsonObjectMapperFactory` which you've already set to `ObjectMapperConfig`.

From my point of view you can do it in two ways:

1. Simply call `create(Type cls, String charset)` on your own `GsonObjectMapperFactory` object.
2. Or by `config().getObjectMapperConfig().gsonObjectMapperFactory().create(Type cls, String charset)` if you've already set with help of `ObjectMapperConfig`.

Or it's not that you want to achieve?

**Comment by adam66** [comment]
Hi Aleks
`create(Type cls, String charset)` on the `GsonObjectMapperFactory` returns a `Gson` object but `body(Object o, ObjectMapper om)` obviously can't handle that. 

`body()` requires a generic REST-assured `ObjectMapper` but your suggestions provides a specific `Gson` mapper. 

This code demonstrates where I'm stuck, specifically on the line instantiating the custom `ObjectMapper`:

        ExclusionStrategy[] exclusionStrategies = new ExclusionStrategy[] {
                new GsonExcludeFieldStrategy(new String[] {"id"},
                        MyPojo.class, AnotherPojo.class, AndAgain.class)
        };
        
        ObjectMapperConfig config = new ObjectMapperConfig(ObjectMapperType.GSON)
                .gsonObjectMapperFactory(
                        (type, s) -> new GsonBuilder()
                                .setDateFormat("yyyy-MM-dd'T'HH:mm:ss")
                                .setExclusionStrategies(exclusionStrategies)
                                .create());
        
        ObjectMapper customObjectMapper = config.gsonObjectMapperFactory()
                .create(null, "");
        
        given().spec(new RequestSpecBuilder().setBaseUri("localhost").build())
                .body(new Object(),
                        customObjectMapper)
                .when()
                .post("myUrl")
                .then()
                .assertThat()
                .statusCode(HttpServletResponse.SC_OK);

**Comment by apodkutin** [comment]
Oh sorry @adam66 , my mistake.
I think you can create `GsonMapper` based on the factory `GsonObjectMapperFactory`, which I've mentioned earlier, like this `ObjectMapper customObjectMapper = new GsonMapper(config.gsonObjectMapperFactory());`:
```
ExclusionStrategy[] exclusionStrategies = new ExclusionStrategy[] {
            new GsonExcludeFieldStrategy(new String[] {"id"},
                    MyPojo.class, AnotherPojo.class, AndAgain.class)
    };
    
    ObjectMapperConfig config = new ObjectMapperConfig(ObjectMapperType.GSON)
            .gsonObjectMapperFactory(
                    (type, s) -> new GsonBuilder()
                            .setDateFormat("yyyy-MM-dd'T'HH:mm:ss")
                            .setExclusionStrategies(exclusionStrategies)
                            .create());
    
    ObjectMapper customObjectMapper = new GsonMapper(config.gsonObjectMapperFactory());
    
    given().spec(new RequestSpecBuilder().setBaseUri("localhost").build())
            .body(new Object(),
                    customObjectMapper)
            .when()
            .post("myUrl")
            .then()
            .assertThat()
            .statusCode(HttpServletResponse.SC_OK);
```

**Comment by adam66** [comment]
So simple! Thank you. I really should have seen that.
