### ISSUE TITLE
Get pretty response as String.

### ISSUE THREAD

**Issue by ivan-baranovski-intellectsoft** [rest-assured/rest-assured#1104]
We have prettyPeek() and prettyPrint() but both of them do not return response as pretty json.
String prettyPrint() - Returns: The body as a string.
T prettyPeek() - Returns: The same response instance.

Do we have any options to return pretty String response?

**Comment by johanhaleby** [comment]
Hmm can't you supply a boolean to prettyPrint/Peek that allows you to configure this?

**Comment by ivan-baranovski-intellectsoft** [comment]
@johanhaleby Sorry, but I'm not sure that I'm following you. I need to have response like a pretty JSON String to have possibility attach it to my report. In case of prettyPrint/Peek I have only returned simple String response.

**Comment by Lewka** [comment]
Hi, don't know if you still need this, but you could use Prettifier class in package io.restassured.internal.support

**Comment by johanhaleby** [comment]
It's internal though so used it with at your own risk. 

You should be able to just do:

```java
get("/x").log().body(true);
```

This pretty prints the response (json/html or xml). `true` is also the default value so this also works:

```java
get("/x").log().body(true);
```

Now if you want to get a hold of what's logged you can have a look at [LoggingITest](https://github.com/rest-assured/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java/LoggingITest.java) or even my [blog post](http://code.haleby.se/2018/10/05/logging-to-disk-with-rest-assured/) on the matter.

**Comment by justinebateman** [comment]
I came across this issue trying to do the same thing, I want to return the prettified response as a string and then process it myself. I *might* have a workaround, it's working for me so far and I haven't noticed any issues with it yet
```
Prettifier prettifier = new Prettifier();
String prettyResponseBody = prettifier.getPrettifiedBodyIfPossible(response, response.getBody());
```
