### ISSUE TITLE
Access to the field named "size"

### ISSUE THREAD

**Issue by ishaigor** [rest-assured/rest-assured#1106]
I have an array of sizes in my payload. Each size is represented by height, width and the name of the size in the field named "size". When accessing 'body("sizes.size", ...)' the size of the array is returned, not the collection of the valued found in each field.
```
{
"sizes": [{
  "height": 10,
  "width": 10,
  "size": "ORIGINAL"
}]
}
```
Is there a way to escape the name of the field and get the values for assertion?

**Comment by johanhaleby** [comment]
Yes you can escape it with single quotes
