### ISSUE TITLE
Detailed File Logging

### ISSUE THREAD

**Issue by shakye** [rest-assured/rest-assured#1108]
Hi,
First of all thanks for developing this amazing tool. :)
I've a requirement to log all the request and responses into a file in a more detailed format.
example - 
----------------------------------------------------------------------
-----------------------------REST-ASSURED------------------------
----------------------------------------------------------------------
Class.Method- line 98
Total time : 1664ms
--------------------------------REQUEST----------------------------
Request Specification
--------------------------------RESPONSE----------------------------
Response Specification 

I've can't figure out how to add a print custom lines in between the default logging.
Is there any work around?
Thanks.

**Comment by johanhaleby** [comment]
Logging is implemented using a filter so you can create your own filter. You can probably copy the LoggingFilter's and make your required changes to them.
