### ISSUE TITLE
How to set Content-Transfer-Encoding in rest assured?

### ISSUE THREAD

**Issue by WeiYang1982** [rest-assured/rest-assured#1109]
I use rest assured for my RESTful api test. and I will send some file to server.
now, I use like this:
`
       
        config = RestAssured.config().encoderConfig(encoderConfig().defaultContentCharset("UTF-8"));
        File f = new File("testdata/王刚询问笔录.doc");
        InputStream is = new FileInputStream(f);
        String fileName = f.getName();
        given().filter(new AllureRestAssured()).log().all()
                .config(config)
                .contentType("multipart/form-data")
                .header("Accept-Language", "zh-cn")
                .header("Connection", "keep-alive")
                .queryParam("caseName", "20181210-19")
                .multiPart("documentations",
                        fileName, is, "application/msword")
        .when()
                .post("/caseAnalysis/addCase")
        .then().log().all()
                .assertThat()
                .statusCode(200)`

I use charles to see the request, the header is:
`

  | POST /api/caseAnalysis/addCase?caseName=20181210-19 HTTP/1.1
-- | --
Accept | */*
Connection | keep-alive
Accept-Language | zh-cn
Transfer-Encoding | chunked
Content-Type | multipart/form-data; boundary=g14aD-eczJMSd3Mn58EaDDC--3gvYHrweMIWs
Host | umbrella-server.test.richinfoai.com
User-Agent | Apache-HttpClient/4.5.3 (Java/1.8.0_192)
Accept-Encoding | gzip,deflate

`
and in the text col it will be start with this:
`
--g14aD-eczJMSd3Mn58EaDDC--3gvYHrweMIWs
Content-Disposition: form-data; name="documentations"; filename="??????.doc"
Content-Type: application/msword
Content-Transfer-Encoding: binary

��ࡱ�>��	BD����A
`

Why the request will send the file with "??????.doc"?
And, how can I fix it?

**Comment by siddharthanG** [comment]
what is the solution provided ?

**Comment by aceton41k** [comment]
@WeiYang1982 solition?
