### ISSUE TITLE
Assertion issue on BIG_DECIMAL value in JSON response in 3.3.0

### ISSUE THREAD

**Issue by hexingjiehao** [rest-assured/rest-assured#1120]
2019-01-11 version3.3.0。
json:
{
	"price": 11.11,
	"money": 22.22,
	"cash": 33.33
}
java code：given().config(RestAssured.config().jsonConfig(jsonConfig().numberReturnType(BIG_DECIMAL))).
                when().
                get("/number").
                then().
                body("cash", is(new BigDecimal(33.33)));
error info：java.lang.AssertionError: 1 expectation failed.
                  JSON path cash doesn't match.
                 Expected: is <33.3299999999999982946974341757595539093017578125>
                Actual: 33.33

**Comment by johanhaleby** [comment]
Oh! And this worked in 3.2.0?

**Comment by hexingjiehao** [comment]
@johanhaleby 
in version 3.2.0
same error info.

**Comment by johanhaleby** [comment]
Ok I see what that problem is. You cannot pass `33.33` to BigDecimal like you do. You need to do `new BigDecimal("33.33")`. This is standard Java behavior.

**Comment by hexingjiehao** [comment]
@johanhaleby thank you
