### ISSUE TITLE
FailureConfig doesn't work with ResponseSpecification

### ISSUE THREAD

**Issue by viclovsky** [rest-assured/rest-assured#1128]
Found here https://github.com/rest-assured/rest-assured/pull/1127

This one works:
`given().config(RestAssuredConfig.config().failureConfig(failureConfig)) .get("http://jsonplaceholder.typicode.com/todos/1").then().statusCode(400); `

But this one — doesn't :
`given().config(RestAssuredConfig.config().failureConfig(failureConfig)) .get("http://jsonplaceholder.typicode.com/todos/1").then().spec(new ResponseSpecBuilder().expectStatusCode(400).build());`

**Comment by johanhaleby** [comment]
thanks for reporting!

**Comment by Bisk1** [comment]
@viclovsky @johanhaleby  when you create `new ResponseSpecBuilder()` it has the default config set from `RestAssured.config()`. So this approach won't also work with any other configs, not just FailureConfig, because no matter what you do in `given().config(...)` it gets nullified when you combine it with `new ResponseSpecBuilder()` constructor.

You can achieve expected result here by modyfing global config:
```
RestAssured.config = RestAssuredConfig.config().failureConfig(failureConfig);

given() .get("http://jsonplaceholder.typicode.com/todos/1")
.then().spec(new ResponseSpecBuilder().expectStatusCode(400).build());
```

Honestly when I wrote this feature I thought this is how it is supposed to work

**Comment by johanhaleby** [comment]
@Bisk1 Thanks for your comments, I guess this is a larger issue. Not sure if I've personally seen it before. It's indeed quite strange and has nothing to do with the FailureConfig per se.

One day we should probably rewrite rest-assured from scratch :) There are so many things that could be made simpler internally and avoid such issues altogether.

**Comment by johanhaleby** [comment]
Yes this is actually how it's supposed to work right now, I had forgotten and was a bit too fast when I read the issue. It's confusing however and it would make more sense to use a better merge strategy.

**Comment by johanhaleby** [comment]
I think I've fixed this now

**Comment by johanhaleby** [comment]
I've published the snapshot now. Please try version `3.3.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by viclovsky** [comment]
Thanks a lot @johanhaleby. I have checked 3.3.1-SNAPSHOT. Issue has gone.
