### ISSUE TITLE
Default Accept headers are present and cannot be overriden

### ISSUE THREAD

**Issue by johno1985** [rest-assured/rest-assured#1142]
Rest Assured - Version 3.0.3
Java Version - 1.8

It appears that the RequestSpecification builds request with two Accept headers already added. There does not appear to be a method to remove/override these.

When I run a test with the following: 

```
given().accept(ContentType.JSON).log().all().when().get("");
```

The following output is generated:

```
Request method:	GET
Request URI:	http://localhost:8000/myapp
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=application/json, application/javascript, text/javascript
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
```
As you can see, there are two additional, unwanted Accept headers, application/javascript and text/javascript

**Comment by gemini-kim** [comment]
@johno1985 Hi, I might be able to help you.

rest-assured `ContentType.JSON` uses the value of the below.
https://github.com/rest-assured/rest-assured/blob/c5dcd189e43191a1dfcb52c7d4410829bce2d1a9/rest-assured/src/main/java/io/restassured/http/ContentType.java#L69
and `Accept` header supports multiple values.

If you want to use a single value, you can use `org.springframework.http.MediaType` or `String` value.
like this:
```
import org.springframework.http.MediaType;

void test(...) {
   given().accept(MediaType.APPLICATION_JSON_VALUE).log().all().when().get("");
   //or given().accept("application/json").log().all().when().get("");
}
```
I hope this helps. 😄
