### ISSUE TITLE
empty parsed response body even when status code is 200

### ISSUE THREAD

**Issue by SandeepPadhy** [rest-assured/rest-assured#1148]
I am receiving empty response body even when the response status code is 200 OK. And the same when i test with Postman i see proper JSON response. Interesting part is the issue is not consistent (sometimes it works perfectly fine and i get the entire JSON body).

Need help how to debug the real cause

**Comment by johanhaleby** [comment]
Try the mailing list and please provide more info.

**Comment by SandeepPadhy** [comment]
Response resp = RestAssured.given().baseUri(myurl)
				.relaxedHTTPSValidation()
				.cookie("JSESSIONID="+ mysessionid)
				.contentType(ContentType.JSON)
				.accept(ContentType.JSON)
				.get();
		System.out.println("StatusCode: "+resp.getStatusCode());
		System.out.println(resp.getBody().asString());

Console Output:
StatusCode: 200
[]
