### ISSUE TITLE
Issue while matching string assrestion.

### ISSUE THREAD

**Issue by NLRKUM1** [rest-assured/rest-assured#1155]
I am using cucumber and passinf belwo for validation 
And response Get Countries and Cities names
        | Response.Data["countries_and_cities_names "][3].language_code    | IT 	|

glue code using is belwo 
@And("response Get Countries and Cities names")
	public void response_Get_Countries_and_Cities_names(Map<String,String> responseFields)
	{
		for (Map.Entry<String, String> field : responseFields.entrySet()) {
			if(StringUtils.isNumeric(field.getValue())){
				json.body(field.getKey(), containsInAnyOrder(Integer.parseInt(field.getValue())));
			}
			else{
//error line 				
json.body(field.getKey(), containsInAnyOrder(String.valueOf(field.getValue())));
				
	}
		}
	}

error msg :
JSON path Response.Data["countries_and_cities_names "][3].language_code doesn't match.
Expected: iterable containing ["IT"]
  Actual: IT

Can u help me to resolve it. there must be slight change is frequired.

**Comment by johanhaleby** [comment]
Please use the mailing-list when asking questions
