### ISSUE TITLE
Support for JUnit Jupiter API

### ISSUE THREAD

**Issue by emre-yildirim** [rest-assured/rest-assured#1173]
Hello, 
I've tried to use rest-assured with the latest stable version of  JUnit which is JUnit Jupiter API 5.4.2
But the tests are not being executed with this version of JUnit.
The specific case can be reproduced after using junit-jupiter-api's annotations for "@Test".
Do you have any plans to support JUnit's last stable version?

**Comment by AngelLopezBellmont** [comment]
Good question Emre. I have the same problem.

**Comment by johanhaleby** [comment]
What error do you get?

**Comment by AngelLopezBellmont** [comment]
Sorry error by my side. Now it is working. 
Thanks @johanhaleby

**Comment by emre-yildirim** [comment]
Actually, there are no errors. the tests are running but the test cases inside are not recognized. so none of them are executed.
Do we need to include "junit-jupiter-engine" in the pom file apart from "junit-jupiter-api" ??

**Comment by johanhaleby** [comment]
@emre-yildirim Hmm ok, but what has this to do with rest assured? Can you run *any* test at all?

**Comment by emre-yildirim** [comment]
I thought rest assured had a compatibility issue with JUnit but it seems like I was the one who was missing junit-jupiter-engine. sorry for the inconvenience
