### ISSUE TITLE
javax.net.ssl.SSLHandshakeException:sun.security.validator.ValidatorException:PKIX path building failed:sun.security.provider.certpath.SunCertPathBuilderException: Unable to find the valid certification path to requested target

### ISSUE THREAD

**Issue by sanjay058** [rest-assured/rest-assured#1174]
Please help me on how to solve the below error I m new to API testing

javax.net.ssl.SSLHandshakeException:sun.security.validator.ValidatorException:PKIX path building failed:sun.security.provider.certpath.SunCertPathBuilderException: Unable to find the valid certification path to requested target
I have below code:
RestAssured.baseURI = wc.getField("BaseURL",Config_Env);
RequestSpecification request = RestAssured.given().header("Authorization" , "Basic ...").body(map);
Response response =request.post(url); <--- getting above error here.

RestAssured version: 3.1.0

Please help me.

Thanks

**Comment by sanjay058** [comment]
working now after using relaxedHTTPSValidation()

**Comment by JanisSharma** [comment]
You need to add the certificate for App2 to the truststore file of the used JVM located at %JAVA_HOME%libsecuritycacerts.

First you can check if your certificate is already in the truststore by running the following command: keytool -list -keystore "%JAVA_HOME%/jre/lib/security/cacerts" (you don’t need to provide a password)

If your certificate is missing, you can get it by downloading it with your browser and add it to the truststore with the following command:

keytool -import -noprompt -trustcacerts -alias <AliasName> -file <certificate> -keystore <KeystoreFile> -storepass <Password>

After import you can run the first command again to check if your certificate was added.

Full Source Code [Here](https://icetutor.com/question/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatorexception-pkix-path-building-failed-error)

**Comment by x-rajaram** [comment]
working now after using relaxedHTTPSValidation()

**Comment by ashokkumarg** [comment]
Here, the maven itself not downloading the dependency. Unable to import the Rest assured? and that produce PKIX issue. Any suggestion?

**Comment by Anujalami** [comment]
> working now after using relaxedHTTPSValidation()

How did you resolved this?
