### ISSUE TITLE
Rest assured do not work with java 11

### ISSUE THREAD

**Issue by emre-yildirim** [rest-assured/rest-assured#1175]
Hello, I've tried using rest assured with v4.0.0. with java v11 & jupiter-api v4.5.2 & jupiter-engine v4.5.2
but the tests are not working and giving the following error ->

> Caused by: java.lang.ClassNotFoundException: io.restassured.path.json.mapper.factory.JohnzonObjectMapperFactory 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

And I've found a workaround to make it work, which is , downgrading restassured to v3.3.0. 
also using the default junit provided by intellij's maven.

**Comment by dunglamtuan** [comment]
I had the problem too, but with `java-8`
Downgrade to 3.3.0 helped.

**Comment by johanhaleby** [comment]
@emre-yildirim When did you get this? Do you have Johnzon in the classpath?

**Comment by twajr** [comment]
I have a similar problem. I've tried lots of things to bypass. However, this is my first attempt to use this framework, but I've tried many things. Also on Java 11 using IntelliJ. GSON is already there 2.8.x is already part of the project and I've tried removing that dependency and letting it use whatever RA pulls in, but same result. 

```java.lang.NoClassDefFoundError: io/restassured/path/json/mapper/factory/DefaultGsonObjectMapperFactory
	at io.restassured.config.ObjectMapperConfig.<init>(ObjectMapperConfig.java:49) ~[rest-assured-4.0.0.jar:na]
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41) ~[rest-assured-4.0.0.jar:na]
	at io.restassured.RestAssured.<clinit>(RestAssured.java:420) ~[rest-assured-4.0.0.jar:na]
```

**Comment by johanhaleby** [comment]
Are you using maven or gradle or something else?

**Comment by twajr** [comment]
Maven: 
```
<!-- https://mvnrepository.com/artifact/io.rest-assured/rest-assured -->
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>4.0.0</version>
</dependency>
```

**Comment by Vicky19r** [comment]
Same here, java8 with spring boot, simple helloworld rest api...tried to test it with restAssured for the first time just to see how it works. 

```
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>4.0.0</version>
			<scope>test</scope>
		</dependency>
```

```
java.lang.NoClassDefFoundError: io/restassured/path/json/mapper/factory/JohnzonObjectMapperFactory

	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:420)
```

It is not detecting Jackson even though it is on the class path as stated in the restAssured documentation.

**Comment by earth001** [comment]
I use with Java 12.01 and Spring Boot 2.1.5 this dependency without issues:

		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured-all</artifactId>
			<version>4.0.0</version>
			<scope>test</scope>
		</dependency>

Also, the documentation mentions something about that here https://github.com/rest-assured/rest-assured/wiki/GettingStarted#java-9

**Comment by eliasnogueira** [comment]
I had this problem and I did exactly @earth001 mentioned: add the `rest-assured-all` dependency.
It worked for me.

**Comment by peter-ponzel** [comment]
tried it with rest-assured-all:4.0.0 and rest-assured:4.0.0 and spring boot 2.1.4 and got 
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer(io.restassured.path.json.mapper.factory.DefaultJackson2ObjectMapperFactory)

**Comment by hugoguerra** [comment]
testCompile "io.rest-assured:json-path:$restAssuredVersion"
	testCompile "io.rest-assured:xml-path:$restAssuredVersion"

**Comment by johanhaleby** [comment]
I finally encountered what may be a similar issue in a project. The problem
was due to Maven dependency resolution and that the "json-path" and
"xml-path" version where not explicitly defined and thus picked up by
spring boot dependency declaration. Adding json-path and xml-path to
explicitly point to 4.0.0 worked for me. I doubt that there's anything we
can do from the rest-assured side.

**Comment by pedromvu** [comment]
I had a similar problem using gradle, make sure it is not this particular issue which made it work without having to add every dependency explicitly:

https://github.com/rest-assured/rest-assured/issues/1168

**Comment by lukebk** [comment]
> tried it with rest-assured-all:4.0.0 and rest-assured:4.0.0 and spring boot 2.1.4 and got
> groovy.lang.GroovyRuntimeException: Could not find matching constructor for: io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer(io.restassured.path.json.mapper.factory.DefaultJackson2ObjectMapperFactory)

This configuration works fine with java 11:
in pom.xml:

`<rest-assured-parent.version>4.1.0</rest-assured-parent.version>
....
<dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${rest-assured-parent.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>io.rest-assured</groupId>
                    <artifactId>json-path</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured-all</artifactId>
            <version>${rest-assured-parent.version}</version>
            <scope>test</scope>
        </dependency>

<dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.5.8</version>
            <scope>test</scope>
        </dependency>
....

`

hope this helps.

Luke

**Comment by johanhaleby** [comment]
It should work with version 4.1.1 (works on all projects I've tried that uses Java 11). Please upgrade!

**Comment by zyzbroker** [comment]
rest-assured:4.3.0 and rest-assured-all:4.3.0 is not working with graalvm ce 20.0.0 (build 11.0.6+9-jvmci-20.0-b02) and spring boot 2.3.0. rest-assured:4.2.0 works perfectly fine.

**Comment by panyis** [comment]
Java 8, springboot2.2.6, the same with @zyzbroker, 4.3.0 still have problem, changed to 4.2.0 it worked.

**exclusion:**
`		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>





`

**add dependency:**
`		
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>${rest.assured.version}</version>
		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>json-path</artifactId>
			<version>${rest.assured.version}</version>
		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>xml-path</artifactId>
			<version>${rest.assured.version}</version>
		</dependency>`

**Comment by netent-perty** [comment]
Downgrade from 4.3.0 -> 4.2.0 worked for me running Java 13.

**Comment by nielsutrecht** [comment]
Thanks @netent-perty : that solved the problem for me too.

**Comment by aubreyyan** [comment]
Java 11, `rest-assured` is only working on `3.3.0`, broken on `5.0.0`.

Can't believe it's still broken after 2 years.

**Comment by mjameer** [comment]
I added test scope to all rest assured jars for Java 17, it worked. 

```
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured-common</artifactId>
			<version>5.4.0</version>
			<scope>test</scope>
		</dependency>
```
