### ISSUE TITLE
How to write request or response log?

### ISSUE THREAD

**Issue by shandongdong** [rest-assured/rest-assured#1180]
- By default when invoking log().all() (or any of the equivalents) in REST Assured logs are written to the console,But I want get log to String Object.  How to get？

- for example:
`
String requestLog = request.log().all();
String responseLog = response.then().log().all(); 
Reporter.write(requestLog);
`

**Comment by johanhaleby** [comment]
Hmmm not sure what you want to achieve. Have a look at https://github.com/rest-assured/rest-assured/blob/c1a52a612cd4c1c14f6f5dd29cd71b4cde284b5c/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java/LoggingITest.java for some examples as well as this blog: http://code.haleby.se/2018/10/05/logging-to-disk-with-rest-assured/
