### ISSUE TITLE
JsonPath.get not working

### ISSUE THREAD

**Issue by decentboy5** [rest-assured/rest-assured#1181]
Not able to get the response for Json Xpath if it contains special character like '/'
Can you help me on this. below is my json data 

My json :
---------

{
  "punchMetaData": {
    "/workAssignmentID": {
      "optional": false,
      "default": "98479290N"
    },
    "/badgeID": {
      "default": "123123123"
    }
  }
}

// Here my Xpath contains '/' 
String keyORXpath="punchMetaData./workAssignmentID";
Object responseFromServer = null;
			JsonPath jsonpath= response.jsonPath();
			responseFromServer = jsonPathEvaluator.get(keyORXpath);

**Comment by johanhaleby** [comment]
You need to escape it: "punchMetaData.'/workAssignmentID'"
