### ISSUE TITLE
AsyncHttpClient - User Agent = AHC/2.0

### ISSUE THREAD

**Issue by jagdeepjain** [rest-assured/rest-assured#1182]
does rest-assured uses https://github.com/AsyncHttpClient/async-http-client for API calls?

**Comment by johanhaleby** [comment]
No, it uses apache http client

**Comment by jagdeepjain** [comment]
Thanks @johanhaleby

**Comment by ScottG489** [comment]
Is it possible to inject a different http client such as AsyncHttpClient?
