### ISSUE TITLE
Can't send multiple query params with same key in URL

### ISSUE THREAD

**Issue by klubi** [rest-assured/rest-assured#1188]
When I build my request I have dynamic number of query params with same key.
Easiest way for me would be to concatenate URL on a side, and paste it to `get()`.
Unfortunately when I do that, all params except one are removed from request.

```
when().get(http://someURL?param=1&param=2&param=3);
```

results in request being sent to `http://someURL?param=3`

In my use case I can't really use dedicated method for adding query params, because I never know how many params with same key there will be.

**Comment by johanhaleby** [comment]
Just do given().queryParam("param", 1,2,3).when().get("http://someURL"). ..
