### ISSUE TITLE
While uploading a file, how to set filename within boundary

### ISSUE THREAD

**Issue by eriklumbela** [rest-assured/rest-assured#1200]
I'm trying to upload a file, with a specific filename.. but so far my implementation doesn't seem to work:

### Given example request:
```
Content-Type: multipart/form-data; boundary=MultipartBoundary

--MultipartBoundary
Content-Disposition: form-data; name="foo.bar"

/path/too/file/foo.bar
--MultipartBoundary--
```

**My attempt:**
```
response = given()
                .contentType("multipart/form-data; boundary=MultipartBoundary")
                .multiPart(getMultiPart(file,filename))
        .when()
            .post(path);
```
**Also tried with (same result)**
```
response = given()
                .contentType("multipart/form-data")
                .multiPart(getMultiPart(file,filename))
        .when()
            .post(path);
```

```
private static MultiPartSpecification getMultiPart(File file, String filename) {
        MultiPartSpecification specification = null;
        try {
            specification = new MultiPartSpecBuilder(Files.readAllBytes(file.toPath()))
                    .fileName(filename)
                    .build();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return specification;
    }
```
### Results
**rest-assured**
The upload succeeds, but the filename is not set (instead I have a default filename), 
**postman result**
trying it with postman succeeds with filename included, so the API is working correctly

![Postman settings 1](https://user-images.githubusercontent.com/28491397/62623966-5786f600-b922-11e9-8ec8-26246d242bbc.png)
![Postman settings 2](https://user-images.githubusercontent.com/28491397/62623968-5786f600-b922-11e9-8f43-d70298100e23.png)

### What am I missing here?

**Comment by johanhaleby** [comment]
Hmmm it should work if you specify the boundary manually. See tests in [MultiPartITest.java](https://github.com/rest-assured/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/io/restassured/itest/java/presentation/MultiPartITest.java).

**Comment by eriklumbela** [comment]
### Solved

thanks @johanhaleby for your reply, that was what I suspected

The way I solved it, was by comparing the raw request of Rest-Assured (using: `log().all()`), with the raw request of Postman (with `Code` button)

Turns out I had two use two `.multiPart()`'s

```
.contentType("multipart/form-data")
    .multiPart(new MultiPartSpecBuilder(file).fileName(file.getAbsolutePath()).build())
    .multiPart(new MultiPartSpecBuilder(filename).controlName("name").build())
```
