### ISSUE TITLE
The order of input JSON is not preserved?

### ISSUE THREAD

**Issue by Pezhin** [rest-assured/rest-assured#1213]
I am looking into this test: https://github.com/rest-assured/rest-assured/blob/165a85b65070f5a07fe0045175613fb2c2811642/json-path/src/test/java/io/restassured/path/json/JsonPathTest.java#L407

where the input is 
```
 private final String JSON2 = 
           "[{\"email\":\"name1@mail.com\",\"alias\":\"name one\",\"phone\":\"3456789\"},\n" +
            "{\"email\":\"name2@mail.com\",\"alias\":\"name two\",\"phone\":\"1234567\"},\n" +
            "{\"email\":\"name3@mail.com\",\"alias\":\"name three\",\"phone\":\"2345678\"}]";
```
After parsing and prettifying, the test expects
```
[
    {
        "phone": "3456789",
        "alias": "name one",
        "email": "name1@mail.com"
    },
    {
        "phone": "1234567",
        "alias": "name two",
        "email": "name2@mail.com"
    },
    {
        "phone": "2345678",
        "alias": "name three",
        "email": "name3@mail.com"
    }
]

```

For each object, the order is no longer same as the input. Is this an expected behavior? How is the order determined?

**Comment by johanhaleby** [comment]
@Pezhin Is this fixed by [this](https://github.com/rest-assured/rest-assured/pull/1215) PR?

Please try version `4.1.2-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

and let me know if it works.

**Comment by Pezhin** [comment]
@johanhaleby I believe it fixes the issue I opened!

However, my original thoughts were that a specific order is expected by this project. This only becomes problematic when comparing "Stringify" version of the json object (e.g., pretty printing in this case) and it does not affect the value if we access by key of object (e.g., "email").  

Now after using LinkedHashMap, the order is specified (as insertion order of elements). So now the stringify version also becomes stable,  but at the cost of a little overhead of changing HashMap to LinkedHashMap. However, I think it's acceptable.

Feel free to close this issue or post your thoughts!

**Comment by johanhaleby** [comment]
@Pezhin No it was not expected by the project, this has probably been a bug for many years. Quite strange that I haven't noticed it before though. 

Thanks for your comments and for reporting the issue.
