### ISSUE TITLE
JAXB GAV changed: jakarta.xml.bind

### ISSUE THREAD

**Issue by Sanne** [rest-assured/rest-assured#1226]
See also:
 - https://wiki.eclipse.org/New_Maven_Coordinates

Would be awesome if rest-assured could change to using the new coordinates, as other projects are moving to change as well, but if you lag behind then we end up with non-conflicting GAVs , yet have conflicting classes.

I realize it's very annoying, don't shoot the messenger :) I just hope you could consider this.

**Comment by johanhaleby** [comment]
Is it just changing some dependencies in Maven? If so maybe you could provide a PR?

**Comment by Sanne** [comment]
Sure, happy to!
