### ISSUE TITLE
doIfValidatableResponseImpl in Kotlin extensions tries to access private field responseSpec

### ISSUE THREAD

**Issue by reddyalready** [rest-assured/rest-assured#1229]
When using the Kotlin extension of 4.1.2 (or -SNAPSHOT) with rest-assured-all and Kotlin 1.3.50 and doing:

```
    val response =
      Given {
        redirects().follow(false)
      } When {
        get(loginUrl)
      } Then {
        statusCode(302)
      } Extract {
        response()
      }
```

I get a 

```
class io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$doIfValidatableResponseImpl$1 tried to access private field io.restassured.internal.ValidatableResponseOptionsImpl.responseSpec (io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$doIfValidatableResponseImpl$1 and io.restassured.internal.ValidatableResponseOptionsImpl are in unnamed module of loader 'app')
```

Because [RestAssuredKotlinExtensions.kt#L80](https://github.com/rest-assured/rest-assured/blob/f44d43b826a94eaa848a980d40f5bf75de21f3b6/modules/kotlin-extensions/src/main/kotlin/io/restassured/module/kotlin/extensions/RestAssuredKotlinExtensions.kt#L80) is:

```
    if (resp is ValidatableResponseImpl) {
        fn(resp.responseSpec)
    }
```

And responseSpec does indeed seem to be a private field.

Should resp.responseSpec be accessed in this way? Or is this a dependency mismatch on my end?

Thank you!

**Comment by reddyalready** [comment]
This was indeed a dependency mismatch caused by `rest-assured:3.3.0` being pulled in by another library. My dependency include of `rest-assured-all:4.1.2` was therefore ignored, and the solution was to also include `rest-assured:4.1.2` explicitly.

Thanks for the fantastic testing library!

**Comment by domshahbazi** [comment]
I am having the same issue. However, it is not clear where `rest-assured:3.3.0` is being pulled in from. `mvn dependency:tree` does not show any dependencies pulling in version `3.3.0`.

**Comment by domshahbazi** [comment]
I am having the same issue. However, it is not clear where rest-assured:3.3.0 is being pulled in from. mvn dependency:tree does not show any dependencies pulling in version 3.3.0.
