### ISSUE TITLE
I dont want to print below statements in my console, is there any way

### ISSUE THREAD

**Issue by decentboy5** [rest-assured/rest-assured#1246]
Hi, 
   Thank you so much for wonderful tool called Rest assured, Everything working great. 

I have below query, after hitting the server i am printing the response in console for debugging purpose. But i am seeing extra statements in my console, how to avoid this ? any idea .

System.out.println(response.getBody().asString());

Now, 
in console, I am seeing below which is highlighted in bold along with response. How to stop printing it on console. 

**main] INFO net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated - No BaseStepListener, GET {myURL} not registered.**

{My response here}

**Comment by johanhaleby** [comment]
This seems related to the "serenitybdd" project, which is not a part of rest assured. But you can probably configure your log settings to disable logging for the RequestSpecificationDecorated class.
