### ISSUE TITLE
Add support for SameSite in Cookie

### ISSUE THREAD

**Issue by anjo-swe** [rest-assured/rest-assured#1255]
Chrome 80 is about to be released (2/4) and it includes a major change to how cookies are handled.

> Cookies that are not properly labeled with **“SameSite=None”** and **“Secure”** will no longer be accessible across sites.

**References:**
* https://web.dev/samesite-cookies-explained/
* https://web.dev/samesite-cookie-recipes/

We are using Rest Assured to test our Services and it would be great if the `Cookie` class was improved with `SameSite` information. (Strict / Lax / None)

**Example Code:**
```
Cookie cookie =
    expect()
        .statusCode(204)
    .when()
        .get("/test/?write_cookie=foo")
        .detailedCookie("foo");

assertEquals("None", cookie.getSameSite());
```

**Comment by johanhaleby** [comment]
Sounds like a nice contribution. Is it something you would consider helping out with?

**Comment by anjo-swe** [comment]
@johanhaleby added a PR, let me know me what you think.
