### ISSUE TITLE
Multipart not supported with put() method.

### ISSUE THREAD

**Issue by anki2189** [rest-assured/rest-assured#1262]
Currently rest-assured doesn't support Multipart File with `PUT` method.  
Following Exception is thrown when we try to use `multipart` method with `put()` : `java.lang.IllegalArgumentException: Currently multi-part file data uploading only works for POST`

Version : 3.0.3

**Comment by steve-todorov** [comment]
@johanhaleby have you had a chance to look into this? are there any guides you can provide for fixing this?
