### ISSUE TITLE
AbstractMethodError: ResponseParserRegistrar.getProperty since RestAssured 4.3.0

### ISSUE THREAD

**Issue by jonathanlermitage** [rest-assured/rest-assured#1283]
Problem with RestAssured 4.3.0.  
OK with 4.2.0 and 4.1.1.

I get `java.lang.AbstractMethodError: io.restassured.internal.ResponseParserRegistrar.getProperty(Ljava/lang/String;)Ljava/lang/Object;` errors on every call to `RestAssured.get(...)`, `RestAssured.given()`, etc:

```
java.lang.AbstractMethodError: io.restassured.internal.ResponseParserRegistrar.getProperty(Ljava/lang/String;)Ljava/lang/Object;
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
	at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy:44)
	at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1448)
	at io.restassured.RestAssured.given(RestAssured.java:653)
	at io.restassured.RestAssured.get(RestAssured.java:720)
```

Sample project: https://github.com/jonathanlermitage/spring-mvc-tiny-sample -> change `rest-assured.version` from `4.1.1` to `4.3.0` in `pom.xml`, then run `mvn verify`.  
Tested with jdk8 and jdk11 on Windows 10 x64.

**Edit** 2020-04-22: my bad, I was still using Groovy 2 dependency (picked from Spring Boot bom). Forcing Groovy 3 fixed the issue for me. So, I think this issue is not related to RestAssured, I simply should have checked my dependencies tree, sorry.

**Comment by anki2189** [comment]
@johanhaleby I am also experiencing same issue after upgrading version from `3.3.0` to `4.3.0`

**Comment by mverwaerde** [comment]
Same problem after upgrading from 4.2.0 to 4.3.0 on jdk 11 with given() method

**Comment by iwan41** [comment]
For some reason when you look at source code of version [4.2.0](https://www.javadoc.io/doc/io.rest-assured/rest-assured/4.2.0/io/restassured/internal/RestAssuredResponseImpl.html#getProperty-java.lang.String-
)

There is getProperty

But in [4.3.0](https://www.javadoc.io/doc/io.rest-assured/rest-assured/latest/io/restassured/internal/RestAssuredResponseImpl.html) there is no such thing

I can't find reflecting change when [comparing those releases](https://github.com/rest-assured/rest-assured/compare/rest-assured-4.2.0...rest-assured-4.3.0)

**Comment by johanhaleby** [comment]
I suspect that it's due to the update of Groovy. Is the stacktrace the same for everyone?

```
java.lang.AbstractMethodError: io.restassured.internal.ResponseParserRegistrar.getProperty(Ljava/lang/String;)Ljava/lang/Object;
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
	at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy:44)
	at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1448)
	at io.restassured.RestAssured.given(RestAssured.java:653)
	at io.restassured.RestAssured.get(RestAssured.java:720)
```

**Comment by jonathanlermitage** [comment]
Finally, it may be a problem with transitive dependencies.

If I run `mvn dependency:tree | grep groovy` on a Spring Boot 2.2.6, I still see Groovy **2.5.10**.  
Forcing any Groovy transitive (groovy, groovy-xml...) version to 3.0.2 fixed the issue for me.

**Comment by anki2189** [comment]
@johanhaleby yes, the stack trace is same .

**Comment by johanhaleby** [comment]
I rewrote the entire class from Groovy to Java but now I get another error. It seems really strange, maybe it has something todo with JUnit 5? Or a bug in groovy.

**Comment by jonathanlermitage** [comment]
@johanhaleby are you sure to use Groovy 3? Could you show a project/code sample?

**Comment by johanhaleby** [comment]
@jonathanlermitage No I'm not sure, but I suspect it when I run the [https://github.com/jonathanlermitage/spring-mvc-tiny-sample](https://github.com/jonathanlermitage/spring-mvc-tiny-sample)  project.

**Comment by johanhaleby** [comment]
HMmm! When I run `mvn dependency:tree` in the root of the [https://github.com/jonathanlermitage/spring-mvc-tiny-sample](https://github.com/jonathanlermitage/spring-mvc-tiny-sample) project I get this:

```
...
\- io.rest-assured:rest-assured:jar:4.3.1-SNAPSHOT:test
[INFO]    +- org.codehaus.groovy:groovy:jar:2.5.9:test
[INFO]    +- org.codehaus.groovy:groovy-xml:jar:2.5.9:test
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.10:test
[INFO]    |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:test
[INFO]    |  \- commons-codec:commons-codec:jar:1.13:test
[INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.10:test
[INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
[INFO]    +- io.rest-assured:json-path:jar:4.3.1-SNAPSHOT:test
[INFO]    |  +- org.codehaus.groovy:groovy-json:jar:2.5.9:test
[INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.3.1-SNAPSHOT:test
[INFO]    \- io.rest-assured:xml-path:jar:4.3.1-SNAPSHOT:test
[INFO]       +- org.apache.commons:commons-lang3:jar:3.9:test
[INFO]       +- com.sun.xml.bind:jaxb-osgi:jar:2.3.0.1:test
[INFO]       \- org.apache.sling:org.apache.sling.javax.activation:jar:0.1.0:test
[INFO]          \- javax.activation:activation:jar:1.1.1:test
```

Could it be that Spring has declared Groovy versions in their master pom? This has been a source of issues before. REST Assured require Groovy 3 from version 4.3.0.

**Comment by jonathanlermitage** [comment]
@johanhaleby yes, this project still uses Groovy 2. Simply override the "groovy.version" property to use Groovy 3, and it works.

**Comment by johanhaleby** [comment]
> Simply override the "groovy.version" property to use Groovy 3, and it works.

OK, then that is the issue! You must use Groovy 3.0.2 and above when using REST Assured 4.3.0.

**Comment by johanhaleby** [comment]
I'm going to close this issue now, thanks for reporting and for sharing the solution. If you don't agree let me know :)

**Comment by aoudiamoncef** [comment]
For Maven projects, the code below works well with Spring Boot projects:

<properties>
       <groovy.version>3.0.7</groovy.version>
       <rest-assured.version>4.3.3</rest-assured.version>
   </properties>

   <dependencies>
       <dependency>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter</artifactId>
       </dependency>
       <dependency>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-test</artifactId>
           <scope>test</scope>
       </dependency>
       <dependency>
           <groupId>io.rest-assured</groupId>
           <artifactId>spring-mock-mvc</artifactId>
           <scope>test</scope>
           <exclusions>
               <exclusion>
                   <artifactId>groovy</artifactId>
                   <groupId>org.codehaus.groovy</groupId>
               </exclusion>
           </exclusions>
       </dependency>
       <dependency>
           <groupId>org.codehaus.groovy</groupId>
           <artifactId>groovy</artifactId>
           <version>${groovy.version}</version>
       </dependency>
       <dependency>
           <groupId>org.codehaus.groovy</groupId>
           <artifactId>groovy-xml</artifactId>
           <version>${groovy.version}</version>
       </dependency>
       <dependency>
           <groupId>org.codehaus.groovy</groupId>
           <artifactId>groovy-json</artifactId>
           <version>${groovy.version}</version>
       </dependency>
       <dependency>
           <groupId>io.rest-assured</groupId>
           <artifactId>json-path</artifactId>
           <version>${rest-assured.version}</version>
           <scope>test</scope>
       </dependency>
       <dependency>
           <groupId>io.rest-assured</groupId>
           <artifactId>xml-path</artifactId>
           <version>${rest-assured.version}</version>
           <scope>test</scope>
       </dependency>
   </dependencies>
