### ISSUE TITLE
The same code can be executed in the postman, writing the returned error using rest-assured.

### ISSUE THREAD

**Issue by l54808821** [rest-assured/rest-assured#1292]
Hello, I have the following problem:
    The same code can be executed in the postman, writing the returned error using rest-assured.

      RequestSpecification given = given();
        given.contentType("application/json");
        given.body("{}");
        Response response = given.post("http://gw3.ykccn.net/orderServer/order/exportSingleOrderList");
        System.out.println("===="+response.asString());

For now, troubleshooting should be a "contenttype" issue

**Comment by dr29bart** [comment]
@l54808821 what error do you get? what is the expected output?

**Comment by l54808821** [comment]
@dr29bart  This is a download request interface,The expected return is a file response, but the actual interface response reports an error of 500,Use the parameters in the postman, as shown in the code

**Comment by dr29bart** [comment]
@l54808821 I am getting:

> ===={"timestamp":1584616680122,"status":500,"error":"Internal Server Error","message":"Request processing failed; nested exception is java.lang.NullPointerException","path":"/orderServer/order/exportSingleOrderList"}

it is a product bug. It most likely Postman request is different somehow.

**Comment by l54808821** [comment]
![image](https://user-images.githubusercontent.com/49773498/77063019-f4148900-6a17-11ea-8884-bc9658124661.png)
![image](https://user-images.githubusercontent.com/49773498/77063077-0f7f9400-6a18-11ea-9caf-54414fc4b570.png)

**Comment by l54808821** [comment]
@dr29bart  I did the same thing with postman and jmeter, and they both returned my expectations.I am confused as to why rest-assured produces a different result.

**Comment by dr29bart** [comment]
@l54808821 Again it is a bug in the backend, which cannot handle charset in Content-Type header.
Please, configure request and close the ticket:
```
 RequestSpecification given = given()
            .config(RestAssuredConfig.config().encoderConfig(
                EncoderConfig.encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false)))
            .contentType("application/json")
            .body("{}");
        Response response = given.post("http://gw3.ykccn.net/orderServer/order/exportSingleOrderList");
        System.out.println("====" + response.asString());

**Comment by l54808821** [comment]
@dr29bart Thank you very much. The problem has been solved
