### ISSUE TITLE
401 Error while Pushing Data to PowerBI Rest API

### ISSUE THREAD

**Issue by bhargavkumar-65** [rest-assured/rest-assured#1322]
Hi,
Micorosft PowerBI is a Business Intelligence Platform, It has a functionality 'Streaming DataSet' which exposes RestAPI of DataSet to Push the Data [Only Post operation is supported]. 
Streaming DataSet Api **doesn't require any authorizations**, I am able to Post the data and get 200 response code from **PostMan** . Where as from RestAssured I am getting 401 Error.
Attaching the PostMan collection and RestAssured Program for Reference. Please Change the PostMan collection file Extension from **.TXT to .json** Before Importing it. 
[PowerBI.postman_collection.TXT](https://github.com/rest-assured/rest-assured/files/4590826/PowerBI.postman_collection.TXT)

Here is My RestAssured Program.
` @Test
    public void submitForm() {

        RestAssured.baseURI = "https://api.powerbi.com";
        given()
      .queryParam("Key","jJlgtn2AycfWAZrJ4R9eyGwPFsCrW09z%2FUuLEXujX5%2BJLx0g8Wv9sQ5g6Qy9HgLkxMPHs8MlNx3hIEcxFRsRzw%3D%3D")
         .body("{" +
                  "\"FlowName\":  \"RESTASSURED\",\n" +
                  "\"Activity\":  \"RESTASSURED\",\n" +
                  "\"Status\":  \"RESTASSURED\",\n" +
                  "\"Method\":  \"SELENIUM BA METHOD\"\n"+"}")
         .when().post("/beta/c8eca3ca-1276-46d5-9d9d-a0f2a028920f/datasets/36f28540-1212-40b6-ab99-9cad65ec3e8d/rows")
         .then().assertThat().statusCode(200).and().contentType(ContentType.JSON);

        System.out.println(RestAssured.baseURI);
}
`

**Comment by aistoica** [comment]
Use the log().all() method on the request and see what is really sent to the server.
