### ISSUE TITLE
Question mark symbol '?' is ignored from url

### ISSUE THREAD

**Issue by venkat675** [rest-assured/rest-assured#1339]
Question mark symbol '?' is ignored from url.

Example code below:
```
RestAssured.
                given()
                .baseUri("https://venkatrest.testrail.io/index.php?/")
                .header("Content-Type", "application/json")
                .header("Authorization", "Basic xxxxxxxx")
                .auth().preemptive().basic("venkat@test.com", "test1234")
                .log().all()
                .get("/api/v2/get_projects")
                .then().assertThat().statusCode(200);
```

**Comment by aistoica** [comment]
Check this url: https://webmasters.stackexchange.com/questions/90615/is-it-valid-to-include-digits-and-question-marks-in-the-url-slug-for-a-permalink

More specifically:

> As you can see, the ? is not allowed directly. That is because ? is a reserved character which starts the query component of the URL. So if you want to include a question mark in your slug, you have to percent-encode it with %3F. While it doesn’t appear to be human-readable, note that this string is not necessarily shown to the user. Many browsers will show the decoded form (i.e., %3F as ?) in the address bar.

**Comment by venkat675** [comment]
This make sense, thanks @aistoica
