### ISSUE TITLE
Run rest-assured tests outside JUnit scope

### ISSUE THREAD

**Issue by brunojcm** [rest-assured/rest-assured#1390]
I really like the rest-assured DSL and how tests are written, but I'd like to be able to compile my test module, generate an Java artifact and run it against a test server without having to run `mvn` or rely on JUnit.

Is it possible somehow?

Would you be accepting PRs to enable that?

**Comment by johanhaleby** [comment]
Hi! Please use the mailing list for asking questions.

**Comment by johanhaleby** [comment]
But thanks for offering a PR, but I think it's out of scope of the project.
