### ISSUE TITLE
How to configure RestAssured to send soap messages contains SOAP Envelope ? 

### ISSUE THREAD

**Issue by daniilmatafonov** [rest-assured/rest-assured#1417]
Hello!
Is it possible to configure RequestSpecBuilder to use **SOAP:Envelope** and **SOAP:Body** elements which mapping to java objects?

**Comment by daniilmatafonov** [comment]
@johanhaleby, could you please help me with this question ?

**Comment by AJ-72** [comment]
Here is how I have set it up. getSoapBody and getSoapAction are custom methods.
requestSpectBldr.setBody(getSoapBody());
requestSpectBldr.addHeader("SOAPAction", getSoapAction());

**Comment by daniilmatafonov** [comment]
@AJ-72 , thank you for your help! 
I've also found a gist which could helpful in sending SOAP requests with RestAssured.
https://gist.github.com/djangofan/2766613
