### ISSUE TITLE
Cookies with expiry date is not handled correctly in CookieFilter

### ISSUE THREAD

**Issue by AJ-72** [rest-assured/rest-assured#1430]
Cookies which contains an expiry date that is not adhering to the 'expired date format' specified at 

> http://web.archive.org/web/20020803110822/http://wp.netscape.com/newsref/std/cookie_spec.html

 is not getting applied in subsequent requests. 

The cookie expiry date format that is now recommended by **IETF is - Expires=Fri, 07 Feb 2020 12:46:00 GMT** (https://tools.ietf.org/html/rfc6265). HttpClient though has not updated to this format yet and expects a format - **Expires=Fri, 07-Feb-2020 HH:MM:SS GMT**. Note the difference in dashes between IETF and Netscape formats. 

> HttpClient further recommends to use custom configuration of Cookie Policy (https://www.mail-archive.com/dev@hc.apache.org/msg16624.html).

Though we can set the httpClient cookie config, CookieFilter does not use the standards from CookieSpec. If we modify the below code in CookieFilter.java 
```
public CookieFilter(boolean allowMultipleCookiesWithTheSameName) {
        this.allowMultipleCookiesWithTheSameName = allowMultipleCookiesWithTheSameName;
        this.cookieSpec = new DefaultCookieSpec(); //This uses the default dateFormat from netscape
        this.cookieStore = new BasicCookieStore();
    }
```

to 

```
public CookieFilter(boolean allowMultipleCookiesWithTheSameName) {
        this.allowMultipleCookiesWithTheSameName = allowMultipleCookiesWithTheSameName;
        this.cookieSpec = new DefaultCookieSpec(new String[]{"EEE, dd MMM yyyy HH:mm:ss z"},false);
        this.cookieStore = new BasicCookieStore();
    }
```
the problem might get resolved. I can raise a PR if this approach sounds good.

**Comment by Steinhain** [comment]
Any update on the issue? Will it be considered in any near future releases?

**Comment by FroMage** [comment]
I was able to fix this issue with:

```java
    public CookieFilter(boolean allowMultipleCookiesWithTheSameName) {
        this.allowMultipleCookiesWithTheSameName = allowMultipleCookiesWithTheSameName;
        this.cookieSpec = new RFC6265StrictSpec();
        this.cookieStore = new BasicCookieStore();
    }
```

Would you want a PR for this?
At the moment, the `CookieFilter` doesn't work for lots of use-cases, and it took me a while to figure out why. I bet lots of users run into this issue but never figure out why it doesn't work.

**Comment by FroMage** [comment]
Any update? Also, cookies are not handled correctly when following redirects, even with a proper cookie filter.

**Comment by FroMage** [comment]
Great, thanks!
