### ISSUE TITLE
rest-assured how do I set the timeout

### ISSUE THREAD

**Issue by GreatAsia** [rest-assured/rest-assured#1444]
I  use more thread run http request,  error info ：
java.net.ConnectException: Connection timed out: connect

I want to set  rest-assured  timeout, but i don,t konw.

**Comment by tomaszwojciechowski** [comment]
You can do it by:

**Comment by GreatAsia** [comment]
thanks

**Comment by mcraj4u** [comment]
It worked for me:
TestNG version 7.4.0 with RestAssured 5.3.0

			//timeout for 
			RestAssuredConfig newConfig = RestAssured.config().
					httpClient(HttpClientConfig.httpClientConfig().setParam("http.connection.timeout", 20000));

			response = RestAssured.given().config(newConfig).contentType("application/json")
				.headers(authHeader, accessToken).with().body(gsonObj).when().post(URL).then().extract().response();


Thank you [tomaszwojciechowski](https://github.com/tomaszwojciechowski)

**Comment by holasharma** [comment]
> It worked for me: TestNG version 7.4.0 with RestAssured 5.3.0
> 
> ```
> 		//timeout for 
> 		RestAssuredConfig newConfig = RestAssured.config().
> 				httpClient(HttpClientConfig.httpClientConfig().setParam("http.connection.timeout", 20000));
> 
> 		response = RestAssured.given().config(newConfig).contentType("application/json")
> 			.headers(authHeader, accessToken).with().body(gsonObj).when().post(URL).then().extract().response();
> ```
> 
> Thank you [tomaszwojciechowski](https://github.com/tomaszwojciechowski)

It is throwing error --> 

 sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Andro999b** [comment]
There is should be much easy way to do this.
