### ISSUE TITLE
body(InputStream) does not work

### ISSUE THREAD

**Issue by honza-zidek** [rest-assured/rest-assured#1480]
The same error as reported fixed in the closed issue https://github.com/rest-assured/rest-assured/issues/1040.
I am using `rest-assured` **4.3.3** (the version is forced by the newest Spring Boot 2.5.0).

My code:

``` lang-java
class MyTest  {
    @Value("classpath:/valid-request.xml")
    private Resource validRequest;
    ....
    @Test
    void myTest() {
        given()
                .header("Content-Type", "text/xml; charset=UTF-8")
                .header("SOAPAction", "myService")
                .body(validRequest.getInputStream())  // this does not work
//              .body(validRequest.getFile())  // this works
        .when()
                .post("/myApi")
        .then()
                .log().ifValidationFails()
                .statusCode(200)
                .contentType("text/xml")
        ;
        
    }
}
```

Rest-assured interprets the `InputStream` as an Object and cannot handle it.

However, when I replace `getInputStream()` with `getFile()`, it works.

Error message:

```
java.io.BufferedInputStream@6ceb953
2021-06-11 17:35:47.083 ERROR [,628aa0b986fe0c98,628aa0b986fe0c98] 11428 --- [o-auto-1-exec-1] com.sun.xml.messaging.saaj.soap          : SAAJ0511: Unable to create envelope from given source
```

**Comment by honza-zidek** [comment]
Have you had time to look at it?

**Comment by snowbldr** [comment]
I observed the same issue using restAssured. It seems that it's calling .toString() somewhere on the inputStream and sending the string instead of the contents of the InputStream...

**Comment by fedinskiy** [comment]
Issue, described by snowbldr still persists in 4.5.1. Instead of sending _content_ of InputStream, current implementation sends a name of Java object.

**Comment by johanhaleby** [comment]
Please help out and provide a PR.

**Comment by fedinskiy** [comment]
@johanhaleby done:
https://github.com/rest-assured/rest-assured/pull/1574

BTW, I would recommend to add some kind of CONTRIBUTING.md. For example, current version cannot be built with Java 11 and older, but this is not described anywhere.

**Comment by johanhaleby** [comment]
@fedinskiy You're right, I should do that.
