### ISSUE TITLE
JsonPath does not support  the key include special char

### ISSUE THREAD

**Issue by phfnjcqscott** [rest-assured/rest-assured#1501]
My Rest-assured version is 4.3.0

The body contain fllowing json string:
{
  "LKJLKKJ;FC|||HJKLK|USD|None|1/1/0001 12:00:00 AM|5/1/2021 12:00:00 AM|7/31/2021 12:00:00 AM|NH004||m|True|||": [
    {
      "DataKey": "InvestmentId:HJKLK[*DataId:UY3[*IsCumulativeContribution:False[*CalId:0[*End:-693595",
      "EarliestDateIndex": 988,
      "LatestDateIndex": 9090,
      "MinValue": 30603103.9929508,
      "MaxValue": 235579875.019039,
      "TSData": [
        {
          "DateIndex": 25656,
          "Date": "2018-12-31",
          "DataType": "double",
          "Value": 119458046.950913
        },
        {
          "DateIndex": 988,
          "Date": "2019-03-31",
          "DataType": "double",
          "Value": 121991488.062055
        },
        {
          "DateIndex": 8989,
          "Date": "2019-06-30",
          "DataType": "double",
          "Value": 120135106.9412
        },
        {
          "DateIndex": 898,
          "Date": "2019-09-30",
          "DataType": "double",
          "Value": 116750530.8924
        },
        {
          "DateIndex": 909,
          "Date": "2019-12-31",
          "DataType": "double",
          "Value": 120744670.99146
        }
      ]
    }
  ]
}

when I use following json path to get string

response.extract().response().jsonPath().getString("['LKJLKKJ;FC|||HJKLK|USD|None|1/1/0001 12:00:00 AM|5/1/2021 12:00:00 AM|7/31/2021 12:00:00 AM|NH004||m|True|||']")

It will throw a exception:
    Method threw 'java.lang.IllegalArgumentException' exception.

Does the jsonpath support this kind of path:
  ['key1'].['key2']

**Comment by johanhaleby** [comment]
The JsonPath in rest assured is not the same thing as the json-path "specification". The json-path in rest assured uses groovy gpath, which I believe preceeds json path. So you should probably something like this instead: `'LKJLKKJ;FC|||HJKLK|USD|None|1/1/0001 12:00:00 AM|5/1/2021 12:00:00 AM|7/31/2021 12:00:00 AM|NH004||m|True|||'. DataKey`. That should return "InvestmentId:HJKLK[*DataId:UY3[*IsCumulativeContribution:False[*CalId:0[*End:-693595"
