### ISSUE TITLE
serialization of java.time.Instant

### ISSUE THREAD

**Issue by gcaccia2** [rest-assured/rest-assured#1511]
I have a POJO that has a field of type java.time.Instant.  If I try to use rest-assured for a POST call with the POJO as body, the call fails.  Looking at the JSON body in the failed request, it has converted the field into...

    "fieldForDate": {
        "seconds": -1424119832,
        "nanos": 0
    },

whereas I was expecting it to convert it into a UTC time string like "1935-11-13T03:18:00Z".

Is there a way to get this to work?

**Comment by johanhaleby** [comment]
Yes! You need to configure Jackson. Something like this: https://github.com/rest-assured/rest-assured/wiki/Usage#configuration
