### ISSUE TITLE
"No signature of method: io.restassured.internal.http.HTTPBuilder.parseResponse() is applicable"

### ISSUE THREAD

**Issue by soc** [rest-assured/rest-assured#1537]
```
groovy.lang.MissingMethodException: No signature of method: io.restassured.internal.http.HTTPBuilder.parseResponse() is applicable for argument types: (io.restassured.internal.http.HttpResponseDecorator, io.restassured.http.ContentType) values: [io.restassured.internal.http.HttpResponseDecorator@153740c7, ...]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:72)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:148)
	at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.parseResponse(RequestSpecificationImpl.groovy:2154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2090)
```

Fails with versions: RestAssured 4.4.0, Groovy 4.0.0-rc2
Works with versions: RestAssured 4.4.0, Groovy 3.0.9

Nothing exotic required to reproduce:

```
    Headers headers = given()
        .header(new Header(HEADER_NAME, headerValue))
            .when().get(baseUrl)  // <-- fails here
            .then().statusCode(200).extract().headers();
```

**Comment by soc** [comment]
Perhaps it would be an option to migrate .groovy code outside json-path and xml-path back to Java, to avoid the Groovy for the core library completely? Upon inspection, most .groovy classes make no or only minor use of Groovy features.

**Comment by soc** [comment]
@johanhaleby Groovy 4 has been released, how can I help fixing this?

**Comment by 379753498** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by soc** [comment]
@379753498 nice holidays!

**Comment by soc** [comment]
@johanhaleby I'm debugging it on Groovy 4.0 now, and it seems that the operation fails here

```
    private static Method findGetLookupMethod(Class<?> groovyObjectClass) throws NoSuchMethodException {
        return groovyObjectClass.getDeclaredMethod("$getLookup");
    }
```
with

`java.lang.NoSuchMethodException: io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.$getLookup()`

**Comment by wilkinsona** [comment]
I've also seen this while trying to upgrade Spring Boot to use Groovy 4.0.x. As part of that, I want to get Spring REST Docs' REST Assured support working with Groovy 4.0.x but a number of tests fail with the error reported in this issue.

**Comment by johanhaleby** [comment]
Please try the latest version, that should work, hopefully :)

**Comment by soc** [comment]
It did, thank you, @johanhaleby!

**Comment by luciano-mota** [comment]
Resolvi da seguinte forma:


        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>5.5.1</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.groovy</groupId>
                    <artifactId>groovy-json</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.groovy</groupId>
                    <artifactId>groovy-xml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.groovy</groupId>
                    <artifactId>groovy</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <version>5.5.1</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.groovy</groupId>
                    <artifactId>groovy-json</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.groovy</groupId>
                    <artifactId>groovy</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>xml-path</artifactId>
            <version>5.5.1</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.groovy</groupId>
                    <artifactId>groovy-xml</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy</artifactId>
            <version>3.0.9</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-xml</artifactId>
            <version>3.0.9</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-json</artifactId>
            <version>3.0.9</version>
            <scope>test</scope>
        </dependency>
