### ISSUE TITLE
rest-assured-4.5.0 should not require jakarta.xml.bind when invoking  new ObjectMapperConfig().jackson2ObjectMapperFactory

### ISSUE THREAD

**Issue by dantran** [rest-assured/rest-assured#1542]
we are using  new ObjectMapperConfig().jackson2ObjectMapperFactory setup object mapper, we only use Json for payload.

However, that invocation looks for jakarta jaxb 3.x in classpath and bails with

    java.lang.ExceptionInInitializerError
    ....
    java.lang.NullPointerException: JakartaEEObjectMapperFactory cannot be null

please allow that method to be compatible with jakarta jaxb-runtime 2.x

**Comment by famod** [comment]
In Quarkus, the dependabot PR failed CI big time with the same error: https://github.com/quarkusio/quarkus/pull/23114

**Comment by geoand** [comment]
FWIW, I did not see any indication anywhere that JakartaEE is necessary. I assume [this](https://github.com/rest-assured/rest-assured/blob/rest-assured-4.5.0/rest-assured/src/main/java/io/restassured/config/ObjectMapperConfig.java#L97) is just an overzealous check?

**Comment by UllasaSrinivasa** [comment]
I am getting ClassNotFound error in below line. Should I import the Jakarta dependency?
`RestAssured.baseURI="*url*"`
Error-
Caused by: java.lang.ClassNotFoundException: io.restassured.path.xml.mapper.factory.JakartaEEObjectMapperFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:422)

**Comment by patrykks** [comment]
We have the same problem. In the release notes of rest-assured 4.5.0 there is information that dependency for jakarta and jaxb is no longer required which I believe is step in right direction (https://github.com/rest-assured/rest-assured/wiki/ReleaseNotes45). As developers we don't want to fetch dependencies to classpath we don't use. However many of us are using `jackson2ObjectMapperFactory`. Often we don't handle xml at all in our projects so we don't need to have jaxb in our classpath. The jakarta case is analogous


I think the problem is constructor of ObjectMapperConfig we are forced to use when we want to use custom jackson object mapper.

```
ObjectMapperConfig objectMapperConfig = new ObjectMapperConfig().jackson2ObjectMapperFactory(
            (type, s) -> <PROVIDE_YOUR_JACKSON_OBJECT_MAPPER_HERE>
        );
        return RestAssuredConfig.config().objectMapperConfig(objectMapperConfig);
```

In such case we are forced to use following constructor:

```
    private ObjectMapperConfig(ObjectMapper defaultObjectMapper, ObjectMapperType defaultObjectMapperType,
                               GsonObjectMapperFactory gsonObjectMapperFactory, Jackson1ObjectMapperFactory jackson1ObjectMapperFactory,
                               Jackson2ObjectMapperFactory jackson2ObjectMapperFactory, JAXBObjectMapperFactory jaxbObjectMapperFactory,
                               JohnzonObjectMapperFactory johnzonObjectMapperFactory, JsonbObjectMapperFactory jsonbObjectMapperFactory,
                               JakartaEEObjectMapperFactory jakartaEEObjectMapperFactory, boolean isUserConfigured) {
        Validate.notNull(gsonObjectMapperFactory, GsonObjectMapperFactory.class.getSimpleName() + " cannot be null");
        Validate.notNull(jackson1ObjectMapperFactory, Jackson1ObjectMapperFactory.class.getSimpleName() + " cannot be null");
        Validate.notNull(jackson2ObjectMapperFactory, Jackson2ObjectMapperFactory.class.getSimpleName() + " cannot be null");
        Validate.notNull(jaxbObjectMapperFactory, JAXBObjectMapperFactory.class.getSimpleName() + " cannot be null");
        Validate.notNull(jakartaEEObjectMapperFactory, JakartaEEObjectMapperFactory.class.getSimpleName() + " cannot be null");
        this.defaultObjectMapperType = defaultObjectMapperType;
        this.defaultObjectMapper = defaultObjectMapper;
        this.gsonObjectMapperFactory = gsonObjectMapperFactory;
        this.jackson1ObjectMapperFactory = jackson1ObjectMapperFactory;
        this.jackson2ObjectMapperFactory = jackson2ObjectMapperFactory;
        this.jaxbObjectMapperFactory = jaxbObjectMapperFactory;
        this.johnzonObjectMapperFactory = johnzonObjectMapperFactory;
        this.jsonbObjectMapperFactory = jsonbObjectMapperFactory;
        this.jakartaEEObjectMapperFactory = jakartaEEObjectMapperFactory;
        this.isUserConfigured = isUserConfigured;
    }
```

**Comment by fabian-froehlich** [comment]
We also use a custom mapper to allow unknown properties
```
        RestAssured.config =
            RestAssured
                .config()
                .objectMapperConfig(
                    new ObjectMapperConfig()
                    .jackson2ObjectMapperFactory(
                            (cls, charset) -> {
                                ObjectMapper om = new ObjectMapper().findAndRegisterModules();
                                om.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
                                return om;
                            }
                        )
                );
```

=> `java.lang.NullPointerException: JakartaEEObjectMapperFactory cannot be null`

Putting jaxb as maven-dependency did not solve the issue
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.3</version>
        </dependency>

**Comment by patrykks** [comment]
@fabian-froehlich did you tried to use version from relase notes of rest-assured: `jakarta.xml.bind:jakarta.xml.bind-api:3.0.1 and org.glassfish.jaxb:jaxb-runtime:3.0.2`?

**Comment by fabian-froehlich** [comment]
@patrykks yes I did that a minute after that post. And I got a little bit down the rabbit-hole

We are calling` ObjectMapperConfig.jackson2ObjectMapperFactory(Jackson2ObjectMapperFactory jackson2ObjectMapperFactory)`. That method uses a big constructor with null checks. But two of them seem to be to be mutually exclusive: `jaxbObjectMapperFactory` and `jakartaEEObjectMapperFactory`. Because in the end there are two methods called
`existInCP("jakarta.xml.bind.Binder")` and `existInCP("javax.xml.bind.Binder")`.
And I would guess that we do not want `both variants in the classpath.

**Comment by patrykks** [comment]
Ok, so its seems that without modification on rest-assured side you are locked :( Did you use rest-assured before 4.5.0? I was quite sure that only thing that changed are dependencies (classpath) but not source code of library

**Comment by fabian-froehlich** [comment]
Yes, I guess so. And yes I am using 4.4 currently and the upgrade was not as flawless as expected ;-)

**Comment by famod** [comment]
@johanhaleby looking at this change:

https://github.com/rest-assured/rest-assured/commit/4e69b3fea59743ee72aa12bd0583ba77b54e3a81#diff-39f37af857b5898f927c0a8c1fd23209e32fa995cbee6d1fb6da094093109df0

The result of `newJakartaEEObjectMapperFactoryOrNullIfNotInClasspath()` is passed to the main constructor which is then calling `Validate.notNull(...)` on that very parameter, which looks like a mismatch of expectations.

**Comment by shavo007** [comment]
i got that error also https://github.com/shavo007/spring-integ-demo/runs/5014896057?check_suite_focus=true#step:6:475

its just a sandbox project I use for spring integ tests. With that latest update, it fails.

**Comment by johanhaleby** [comment]
Gah! Sounds like a bug indeed, I'll try fix and publish a new snapshot.

**Comment by johanhaleby** [comment]
@fabian-froehlich Thanks for trying it out. I would love if someone else could verify as well before I make a new release (because releasing is pretty cumbersome still).

**Comment by MediaMarco** [comment]
@johanhaleby I also tried the latest 4.5.1-SNAPSHOT, it solves the issue for me! With 4.5.0 I also had the "java.lang.NullPointerException: JakartaEEObjectMapperFactory cannot be null" error.

**Comment by johanhaleby** [comment]
@MediaMarco Thanks, then I'll make a new release today.
