### ISSUE TITLE
jsonPath should return 'null' if array expression in jsonPath does not exist in input json document

### ISSUE THREAD

**Issue by kool79** [rest-assured/rest-assured#1543]
By default jsonPath returns `null` if some object in a chain does not exist.
For example if we have a json:
```
 { 
   "root":{}
 }
```
Then json-path `root.object.subobject` will return `null` because `object` does not exist under `root`.
But this rule does not applied to json-pathes which contains arrays:
`root.objects[0].subobject`
In such case instead of "null" we'll have exception:
_Cannot invoke method getAt() on null object_
This behavior is inconsystent: in a firt and later cases ojects are absent but we have null result for objects but exception for arrays.

Workaround is to use ?[] form:
`root.objects?[0].subobject`
BUT this form is NOT required for objects.

**Comment by anfan1956** [comment]
https://learn.microsoft.com/en-us/sql/relational-databases/json/include-null-values-in-json-include-null-values-option?view=sql-server-ver16

SELECT name, surname  
FROM emp  
FOR JSON AUTO, INCLUDE_NULL_VALUES
