### ISSUE TITLE
Cast to ResponseSpecificationImpl in RequestSpecificationImpl 

### ISSUE THREAD

**Issue by cliviu** [rest-assured/rest-assured#1573]
Hi @johanhaleby ,

   in RequestSpecificationImpl, in the latest version, line 1153 is a cast of the responseSpecification to  ResponseSpecificationImpl.
even if the variable is defined as FilterableResponseSpecification. 
`private FilterableResponseSpecification responseSpecification`

`
def http = new RestAssuredHttpBuilder(responseSpecification as ResponseSpecificationImpl, requestHeaders, queryParameters, targetUri, assertionClosure, urlEncodingEnabled,
        config, requestSpecification.getHttpClient() as AbstractHttpClient, allowContentType, responseSpecification.rpr.defaultParser)
`

In order to keep clean the reference to FilterableResponseSpecification interface and to make RestAssuredHttpBuilder use the FilterableResponseSpecification, this interface should be extended with the method hasBodyAssertionsDefined(). 
     
   I am prepared to make a PR for this, will this be ok for you ?
 
   Thanks !

**Comment by johanhaleby** [comment]
How do you use this?

**Comment by cliviu** [comment]
Hi, we are directly using it here : https://github.com/serenity-bdd/serenity-core/blob/master/serenity-rest-assured/src/main/java/net/serenitybdd/rest/decorators/ResponseSpecificationDecorated.java by implementing FilterableResponseSpecification. When trying to upgrade to the latest rest-assured version got a ClassCastException.

**Comment by johanhaleby** [comment]
I see. I've now deployed a new snapshot that should address this issue. Could you please try version `5.01-SNAPSHOT` after having added the following Maven repository to see if it works for you:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by cliviu** [comment]
Thank you so much, I will try it over the weekend.

**Comment by cliviu** [comment]
I have tested and the ClassCastException is gone ... Waiting forward for the version 5.0.1 to be released...
Thank you so much again!

**Comment by johanhaleby** [comment]
@cliviu Great to hear, I'll make a new release soon!
