### ISSUE TITLE
Error creating endpoint path with path parameters

### ISSUE THREAD

**Issue by fgolygo** [rest-assured/rest-assured#1624]
Version: rest-assured-5.1.1 (but same happens in 5.2.0)

class: RequestSpecificationImpl.groovy
method: `get(String path, Object... pathParams)` and finally `newFilterContext(assertionClosure, filters, properties)`
line: `def unnamedPathParamValues = unnamedPathParamsTuples.findAll { it.v2 != null }.collect { it.v2 }`

`unnamedPathParamsTuples` variable is of type `List<Tuple2<String, String>>`

Error:
```
groovy.lang.MissingPropertyException: Exception evaluating property 'v2' for groovy.lang.Tuple2, Reason: groovy.lang.MissingPropertyException: No such property: v2 for class: java.lang.String
```

It looks like it tries to invoke `v2` method on an object that does not have it

**Comment by lucas-nguyen-17** [comment]
@fgolygo Could you add sample code to reproduce the problem?

**Comment by lucas-nguyen-17** [comment]
@fgolygo Humm, I tested your code with both version `5.1.1` and `5.2.0`. Cannot reproduce the problem.

```
RequestSpecification requestSpecification = RestAssured.given().when();
Response response = requestSpecification.log().all().get("https://reqres.in/api/users/{id}", 2);
response.prettyPrint();
```
Result:
```
Request method:	GET
Request URI:	https://reqres.in/api/users/2
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=*/*
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
{
    "data": {
        "id": 2,
        "email": "janet.weaver@reqres.in",
        "first_name": "Janet",
        "last_name": "Weaver",
        "avatar": "https://reqres.in/img/faces/2-image.jpg"
    },
    "support": {
        "url": "https://reqres.in/#support-heading",
        "text": "To keep ReqRes free, contributions towards server costs are appreciated!"
    }
}
```

**Comment by fgolygo** [comment]
@lucas-nguyen-17 thats odd. I run your snippet and it fails. I will dig into it more on my side and update if I find anything.. Thanks for checking

**Comment by fgolygo** [comment]
@lucas-nguyen-17 after all it turned out we had a different groovy dependency that was overriding the one used by rest assured and the failure happens because of that. Closing
