### ISSUE TITLE
Method Response.asPrettyString() destroys binary responses

### ISSUE THREAD

**Issue by BChabowski** [rest-assured/rest-assured#1638]
Behaviour of `Response.asPrettyString()` seems to be different than `Response.asString()`. Regular `asString` method just returns response as String, wheras `asPrettyString` also saves string version of response as new body and - in process - destroys binary data. Please consider following code:

```java
public static void main(String[] args) throws IOException {
        //download dummy pdf
        RestAssured.baseURI = "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf";

        //this will work fine
        Response firstResponse = given()
                .contentType(ContentType.BINARY)
                .when()
                .get();

        firstResponse.asString();
        parsePdf(firstResponse.asInputStream());

        //this will result in exception since asPrettyString converts response body
        Response secondResponse = given()
                .contentType(ContentType.BINARY)
                .when()
                .get();

        secondResponse.asPrettyString();
        parsePdf(secondResponse.asInputStream());
    }

    private static void parsePdf(InputStream inputStream) throws IOException {
        PDDocument document = PDDocument.load(inputStream);
        if (!document.isEncrypted()) {
            PDFTextStripper stripper = new PDFTextStripper();
            String text = stripper.getText(document);
            System.out.println("Successfully parsed pdf from input stream:" + text);
        }
        document.close();
    }
```

In `RestAssuredResponseOptionsGroovyImpl.groovy` string is explicitely saved as new body:
```groovy
  String asPrettyString(ResponseOptions responseOptions, ResponseBody responseBody) {
    def body = new Prettifier().getPrettifiedBodyIfPossible(responseOptions, responseBody)
    content = body
    body
  }
  ```
  Why is that? Is this intentional to convert the body only in this method? There is no info about that in documentation, and the bahaviour is unexpected. 
  The problem arose in our project, where we log every response before using it. It seems easy to repoduce, so it's likely we are not the first or last to encounter it.
  
  Please advice whether it is a bug or something we need to live with.

**Comment by lucas-nguyen-17** [comment]
Pls calm down. It's open source, you can expect it MUST support all people needs.

Back to the problem, I don't see any different from both methods. I tested your code as well, and no exception.
- `getPrettifiedBodyIfPossible` will make string pretty if it has content-type which is one of JSON, XML, HTML.
- If not (no defined content-type or not define content-type at all), it will fall back to `.asString()`

You can take a look the code here: class Prettifier

```
String getPrettifiedBodyIfPossible(ResponseOptions responseOptions, ResponseBody responseBody) {
    def contentType = responseOptions.getContentType()
    def responseAsString = responseBody.asString()
    if (isBlank(contentType) || !(responseOptions instanceof RestAssuredResponseOptionsImpl)) {
      return responseAsString
    }

    RestAssuredResponseOptionsImpl responseImpl = responseOptions as RestAssuredResponseOptionsImpl
    def rpr = responseImpl.getRpr()
    def parser = rpr.getParser(contentType)
    prettify(responseAsString, parser)
  }

  String prettify(String body, Parser parser) {
    String prettifiedBody
    try {
      switch (parser) {
        case Parser.JSON:
          prettifiedBody = JsonPrettifier.prettifyJson(body)
          break
        case Parser.XML:
          prettifiedBody = XmlPrettifier.prettify(new XmlParser(false, false), body)
          break
        case Parser.HTML:
          prettifiedBody = XmlPrettifier.prettify(new XmlParser(new org.ccil.cowan.tagsoup.Parser()), body)
          break
        default:
          prettifiedBody = body
          break
      }
    } catch (Exception e) {
      // Parsing failed, probably because the content was not of expected type.
      prettifiedBody = body
    }
    return prettifiedBody
  }
```

**Comment by BChabowski** [comment]
>I don't see any different from both methods.

There is extra assignment to `content` variable in `asPrettyString`, my thought was it's because of that:
```groovy
 String asPrettyString(ResponseOptions responseOptions, ResponseBody responseBody) {
    def body = new Prettifier().getPrettifiedBodyIfPossible(responseOptions, responseBody)
    content = body //<-here
    body
  }
```
vs
```groovy
  String asString(boolean forcePlatformDefaultCharsetIfNoCharsetIsSpecifiedInResponse) {
    charsetToString(findCharset(forcePlatformDefaultCharsetIfNoCharsetIsSpecifiedInResponse))
  }
```

>I tested your code as well, and no exception.

That's weird - did you also get the correct message twice? I used `org.apache.pdfbox` v.2.0.27, maybe it's library issue then? What version did you use?

>It's open source, you can't expect it MUST support all people needs.

I really don't ;) It's just inconsistency - if it works like I presented it - and I thought of pointing that out.

**Comment by lucas-nguyen-17** [comment]
@BChabowski Oh, I got you wrong. It does change the `content`
- `asString` remains `content` as byte array
- `asPrettyString` changes `content` to String.

That's why you get exception. You can provide a pull request to fix this issue. I don't know when @johanhaleby can come back this project.

![image](https://user-images.githubusercontent.com/44698518/196310103-18861464-9701-4907-9184-183d68fb875d.png)

**Comment by BChabowski** [comment]
PR created
