### ISSUE TITLE
Unexpected logic in PathSupport.getPath()

### ISSUE THREAD

**Issue by fucct** [rest-assured/rest-assured#1682]
While developing an OAuth authentication server, I discovered unexpected behavior when the query parameter in the path contains an http scheme. 

As shown in the following example, when the targetUri is `/oauth/authorize?client_id=clientId&redirect_uri=https://sample.com&response_type=code&login_type=token`, the code at line 61 searches for the index of "://" and treats it as the host's scheme. Consequently, when attempting to find the index of "/", the path is not found, resulting in a bug where the path is "/".

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/48818566/225687970-19cc10e9-d7cb-46d2-9c87-3d025a2e3b4f.png">

To address this issue, either the path should be encoded before being evaluated if the content type is application/x-www-form-urlencoded, or the logic of the method needs to be modified.

My current rest assured version is 5.2.1. Please let me know if this has been fixed in a different version.

**Comment by KIMSIYOUNG** [comment]
i need to fix this too
