### ISSUE TITLE
Unable to use jakarta.mail-api if rest-assured added in the dependency 

### ISSUE THREAD

**Issue by fayizkc** [rest-assured/rest-assured#1690]
I am using  jakarta.mail-api to send email from my maven java project. If i have rest-assured  added in the pom, I am getting expectation as below. If I comment the rest-assured libraries, my email code is working fine. Please help me to resolve this isssue.

```
java.lang.ClassCastException: class com.sun.mail.handlers.text_html cannot be cast to class jakarta.activation.DataContentHandler (com.sun.mail.handlers.text_html and jakarta.activation.DataContentHandler are in unnamed module of loader 'app')
	at jakarta.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:601)
	at jakarta.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:554)
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:590)
	at jakarta.activation.DataHandler.writeTo(DataHandler.java:289)
	at jakarta.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1551)
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2246)
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2206)
	at jakarta.mail.Transport.send(Transport.java:99)
```

I am using below dependencies in my pom.xml

```
 <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>    
        <rest-assured.version>5.3.0</rest-assured.version>
    </properties>

---
  <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${rest-assured.version}</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <version>${rest-assured.version}</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>${rest-assured.version}</version>
        </dependency>

  <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>jakarta.mail</artifactId>
            <version>2.0.1</version>
        </dependency>

        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by basdijkstra** [comment]
Hey @fayizkc, it's likely that the problem is a transitive dependency that's causing the conflict.

You can exclude transitive dependencies as described [here](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)

And [here's a tutorial on the subject](https://www.digitalocean.com/community/tutorials/maven-dependency-tree-resolving-conflicts). It seems like running `mvn dependency:tree` is a good starting point.

**Comment by german-chacon** [comment]
@fayizkc I solved the problem by putting the following dependencies before the rest-assured dependencies in the POM file:

<dependencies>
	<dependency>
		<groupId>com.sun.mail</groupId>
		<artifactId>jakarta.mail</artifactId>
		<version>2.0.1</version>
	</dependency>
	<dependency>
		<groupId>com.sun.activation</groupId>
		<artifactId>jakarta.activation</artifactId>
		<version>2.0.1</version>
	</dependency>
	<dependency>
		<groupId>io.rest-assured</groupId>
		<artifactId>rest-assured</artifactId>
		<version>5.3.1</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>io.rest-assured</groupId>
		<artifactId>json-schema-validator</artifactId>
		<version>5.3.2</version>
	</dependency>
</dependencies>

Hope it works as well for you

**Comment by fayizkc** [comment]
Thank you @basdijkstra  and @german-chacon . Issue has been resolved with below update
`       
 <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>${rest-assured.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.mail</groupId>
                    <artifactId>mailapi</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
`
