### ISSUE TITLE
SVG file upload - fatal error :1:1: content is not allowed in prolog

### ISSUE THREAD

**Issue by twodulls** [rest-assured/rest-assured#1707]
I call the API to upload the SVG file as follows: RestAssured(5.3.1)

```
given()
.multiPart("files", file, mimeType)
.when()
.post("/contents/upload")
.then()
.extract().response();
```
The test succeeds however it logs the following to console:
```
[Fatal Error] :1:1: Content is not allowed in prolog.
```
The File upload was successful and the image nothing wrong.
I want to know why an error occurred.

thanks

**Comment by TheConen** [comment]
I'm having the same problem - multipart request with a perfectly fine and valid XML file logs that error. Did you find a solution?

**Comment by beng9re** [comment]
I've added fix for this issue.
