### ISSUE TITLE
PathParams encoding in 5.3.2

### ISSUE THREAD

**Issue by Hatelix** [rest-assured/rest-assured#1733]
Hello, after upgrading from 5.3.1 to 5.3.2 (via spring-boot-dependencies 3.1.3 -> 3.1.4) in our Spring Boot 3 application, we encounter a test failure in a test using `RestAssuredMockMvc` where a path param (added with `get(String path, Object... pathParams)`) including spaces is encoded _two_ times, resulting in the string `%2520` in the request URI. This, in turn, will then be decoded to `%20` resulting in the test to fail.

I did some investigating and I think this problem was introduced with the solution of https://github.com/rest-assured/rest-assured/issues/1720. [Here in the diff](https://github.com/rest-assured/rest-assured/pull/1723/files?diff=unified&w=0#diff-79fa6f5d38775011fc151e09807e2b8cac13d44bc0c3a1173f533958694f4fd5R336) (`modules/spring-mock-mvc/src/main/java/io/restassured/module/mockmvc/internal/MockMvcRequestSenderImpl.java:336`) you can see that this call to `uriComponentsBuilder.build().toUriString()` is now done _after_ any path params are added to the URI, leading to them being encoded an additional time. Later in our setup, they will be encoded a second time by `MockHttpServletRequestBuilder` (from spring-test 6.0.12) which is unchanged behaviour regarding this upgrade as far as I understand it.

I'm not exactly sure if this is a bug, but at least the behaviour of RestAssured seems to have changed insofar as the request URI now includes encoded path params, whereas with version 5.3.1 it did not.

Can you give us some insights?

**Comment by dkaukov** [comment]
Hi, we alo see issue with double-encoding of the url parameters. This is especially visible with Spring Security as generated requests are rejected by `StrictHttpFirewall` with message:
```
Rejecting request due to: The request was rejected because the URL contained a potentially malicious String "%25"
```

**Comment by mikebell90** [comment]
#1756 fixed it for me!
