### ISSUE TITLE
Issue with RestAssured API returning 500 Internal Server Error when sending XML body and receiving JSON response

### ISSUE THREAD

**Issue by KyrillosNageh** [rest-assured/rest-assured#1805]
**Description:**
While attempting to send an XML request body using RestAssured for the /booking endpoint on restful-booker.herokuapp.com, the server consistently returns a 500 Internal Server Error. The same XML body works perfectly when using Postman, returning the expected JSON response.

In Postman, I set the Content-Type to application/xml and the Accept header to application/json, and the response is successfully returned as a 200 OK with the expected body. The issue arises only when using RestAssured.

**Steps to Reproduce:**

1. Set up Rest-Assured for sending API requests.
2. Create a test case that sends a POST request to the https://restful-booker.herokuapp.com/booking API with the following XML body:
```
<booking>
  <firstname>John</firstname>
  <lastname>Doe</lastname>
  <totalprice>150</totalprice>
  <depositpaid>true</depositpaid>
  <bookingdates>
    <checkin>2024-09-10</checkin>
    <checkout>2024-09-15</checkout>
  </bookingdates>
  <additionalneeds>Breakfast</additionalneeds>
</booking>
```
3. The test code in Java using Rest-Assured:
```

public class BookingTest {
    @Test
    public void createBooking() {
        String xmlRequestBody = "<booking>" +
                                "<firstname>John</firstname>" +
                                "<lastname>Doe</lastname>" +
                                "<totalprice>150</totalprice>" +
                                "<depositpaid>true</depositpaid>" +
                                "<bookingdates>" +
                                "<checkin>2024-09-10</checkin>" +
                                "<checkout>2024-09-15</checkout>" +
                                "</bookingdates>" +
                                "<additionalneeds>Breakfast</additionalneeds>" +
                                "</booking>";
        
        Response response = given()
            .header("Content-Type", "application/xml")
            .header("Accept", "application/json")
            .body(xmlRequestBody)
            .post("https://restful-booker.herokuapp.com/booking");
        
        System.out.println(response.getBody().asString());
    }
}
```

**Expected output:**
The API request should return a 200 OK status code and successfully create a booking with the provided XML payload. The response should contain the booking details in the JSON format.
![image](https://github.com/user-attachments/assets/840047a8-eb5b-448b-a443-e36f8a2d9ceb)

**Actual output:**
The API request returns a 500 Internal Server Error. The response body indicates an internal server issue, but the payload and headers are seemingly correct.

**Comment by pranavjandu** [comment]
Hi @KyrillosNageh 

I tried to replicate the issue. I am getting the same Internal Server Error even from Postman.
Can you please attach the curl from postman.

<img width="886" alt="Screenshot 2024-09-10 at 3 17 21 PM" src="https://github.com/user-attachments/assets/acae1fb4-66e0-4bd8-8e66-595a384bfa2f">

**Comment by KyrillosNageh** [comment]
Hi @pranavjandu 

```
curl --location 'https://restful-booker.herokuapp.com/booking' \
--header 'Content-Type: text/xml' \
--data '<booking>
  <firstname>John</firstname>
  <lastname>Doe</lastname>
  <totalprice>150</totalprice>
  <depositpaid>true</depositpaid>
  <bookingdates>
    <checkin>2024-09-10</checkin>
    <checkout>2024-09-15</checkout>
  </bookingdates>
  <additionalneeds>Breakfast</additionalneeds>
</booking>'
```

**Comment by pranavjandu** [comment]
Hi @KyrillosNageh 

I suspect your server expects a very specific header content-type i.e. text/xml.
By default, REST Assured automatically appends a charset to the Content-Type header if it's not already specified. This is typically done to ensure proper encoding of the request body.
In cases like yours, this automatic addition of charset information can cause issues with servers that are expecting a very specific Content-Type header, hence the Server Error.

I was able to resolve the issue by below code.

```
    @Test
    public void createBooking() {
        String xmlRequestBody = "<booking>" +
                "<firstname>John</firstname>" +
                "<lastname>Doe</lastname>" +
                "<totalprice>150</totalprice>" +
                "<depositpaid>true</depositpaid>" +
                "<bookingdates>" +
                "<checkin>2024-09-10</checkin>" +
                "<checkout>2024-09-15</checkout>" +
                "</bookingdates>" +
                "<additionalneeds>Breakfast</additionalneeds>" +
                "</booking>";

        Response response = given()
                .config(RestAssured.config().encoderConfig(
                        EncoderConfig.encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false)))
                .header("Content-Type", "text/xml")
                .header("Accept", "application/json")
                .body(xmlRequestBody)
                .post("https://restful-booker.herokuapp.com/booking");

        System.out.println(response.getBody().asString());
    }
```


I also verified the headers by REST Assured using a proxy as attached in the screenshot.
<img width="715" alt="Screenshot 2024-09-10 at 11 34 47 PM" src="https://github.com/user-attachments/assets/e05bdcdb-aa4c-444b-bfb1-3a15786571f7">

**Comment by pranavjandu** [comment]
@KyrillosNageh Please close the issue if query is resolved.

**Comment by KyrillosNageh** [comment]
Resolved
