### ISSUE TITLE
Unknown status code throws when using ResponseLogFilter

### ISSUE THREAD

**Issue by johanhaleby** [rest-assured/rest-assured#537]
_From [eskato...@gmail.com](https://code.google.com/u/115671622875546989676/) on January 10, 2015 12:07:23_

What steps will reproduce the problem? 1. Use rest-assured@2.4.0
2. Call RestAssured.enableLoggingOfRequestAndResponseIfValidationFails()
3. Invoke HTTP resource that return an unknown code, like 601 What is the expected output? What do you see instead? java.lang.IllegalArgumentException: Status code must be greater than 100 and less than 600, was 601.
        at com.jayway.restassured.builder.ResponseBuilder.build(ResponseBuilder.java:175)

Without logging enabled things works well.

Enabling logging should not fail tests that pass without it.

From my understanding, HTTP RFCs do not forbid usage of status codes >599, they are simply unspecified.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=382_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 16, 2015 11:06:28_

You're right. Thanks for reporting.

**Status:** Accepted

**Comment by macmon** [comment]
Hi,

I created a pull request [1773](https://github.com/rest-assured/rest-assured/pull/1773) where I removed the check from the Builder class. We really need this fix to check our application because we're using "911" as application specific error code.
