### ISSUE TITLE
It is incredibly hard to remove a header in a Filter

### ISSUE THREAD

**Issue by johanhaleby** [rest-assured/rest-assured#539]
_From [kna...@gmail.com](https://code.google.com/u/114839085625274533849/) on February 11, 2015 04:42:38_

What steps will reproduce the problem? 1. Try to implement a RemoveHeaderFilter class What is the expected output? What do you see instead? The only way to remove a header is to copy the whole collection of headers, filter out the one you don't want, and then set all headers again with headers(Headers) or headers(Map<String, ?>). What version of the product are you using? On what operating system? Version: 2.4.0
OS: OS X Please provide any additional information below. N/A

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=384_

**Comment by johanhaleby** [comment]
_From [kna...@gmail.com](https://code.google.com/u/114839085625274533849/) on February 11, 2015 23:08:51_

Actually, I don't think the code I wrote even works. It looks like headers can only be added and never removed?? This makes Filters much less powerful and RequestSpecification much less composable.

**Comment by johanhaleby** [comment]
_From [kna...@gmail.com](https://code.google.com/u/114839085625274533849/) on February 11, 2015 23:11:49_

This means I can't even modify an existing header—instead, another copy of the existing header gets added.

**Comment by johanhaleby** [comment]
_From [kna...@gmail.com](https://code.google.com/u/114839085625274533849/) on February 11, 2015 23:19:12_

One last comment: This functionality does exist in JerseyTest's ClientRequestFilter and spring-test's RestTemplate.

**Comment by johanhaleby** [comment]
_From [kna...@gmail.com](https://code.google.com/u/114839085625274533849/) on February 11, 2015 23:28:17_

Nevermind about modifying headers! I found overwriteHeadersWithName. The original issue still stands, though.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 12, 2015 10:35:43_

**Status:** Accepted

**Comment by johanhaleby** [comment]
I've now implemented "removeHeader" method to allow for this. Better late than never...

**Comment by thokari** [comment]
How to use this?

This is not working:
```
    @Override
    public Response filter(FilterableRequestSpecification requestSpec, FilterableResponseSpecification responseSpec, FilterContext ctx) {
        requestSpec.removeHeader(headerName);
        return ctx.next(requestSpec, responseSpec);
    }
```

**Comment by johanhaleby** [comment]
Could you please be more specific?

**Comment by tedcasey** [comment]
This doesn't appear to work for me:

```
builder
        .setConfig(RestAssuredConfig.config()
        .headerConfig(HeaderConfig.headerConfig().overwriteHeadersWithName(header.toString())))
        .addHeader(header.toString(), headerValue);
```

The header info in the RequestSpecBuilder appears correct (i.e. it has the change in requestHeaders) as I step through in Eclipse (including through the following):
```
RequestSpecification req = builder.build();
given(req).expect().spec(expectedResponse).log().all().when().delete(restAPI);
```
But when the call is actually fired, the log in the console shows that call happens as though I hadn't changed the header value.  Stepping through the RestAssured code does not appear to reveal anything substantive, although I am hitting some "line number unknown" lines when stepping.

Is there something I'm missing?

Btw, I would like to +1 thokari's comment above about there not being a .removeHeader() method on the requestSpecBuilder, like there is for removeParam(), removeFormParam(), removePathParam(), removeQueryParam().  Even if the workflow I laid out above worked, it's not as straighforward as these other remove methods.

**Comment by sfeinstein** [comment]
In support of this feature:  it is a nice test-writing style to be able to say "take this thing which was working in our happy path test and make this one change to it and see it fail".  In this case the one change is removing a required header.  Would love to see this supported in a nice style.
