### ISSUE TITLE
auth().basic() doesn't work with DELETE

### ISSUE THREAD

**Issue by johanhaleby** [rest-assured/rest-assured#541]
_From [jacek.ku...@gmail.com](https://code.google.com/u/106130598148880712553/) on February 19, 2015 09:55:10_

What steps will reproduce the problem? 1. given().auth().basic('foo', 'bar').delete('something') What is the expected output? What do you see instead? The Authorization header is not sent, while the same authorization works fine with POST and GET. To have authorization working with DELETE, I need to manually set a proper Authorization header. What version of the product are you using? On what operating system? rest-assured 2.4.0
OS X Yosemite
java version "1.8.0_05" Please provide any additional information below. When I enable logging with given().log().all().auth().basic(), the Authorization header is not logged even for the GET/POST requests (which may be another bug), but it seems to be sent, since those requests work (and they certainly fail without authorization, which I double checked with curl).

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=386_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 16, 2015 04:10:29_

Does it work with preemptive basic auth?

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [jacek.ku...@gmail.com](https://code.google.com/u/106130598148880712553/) on March 16, 2015 08:10:47_

Yes, preemptive basic auth works fine. Shall we still consider this a bug then?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 16, 2015 08:50:48_

Don't know. Need to read up upon this. Perhaps non-preemptive basic auth shouldn't work with delete or perhaps the challenge is not commenced by the server?

**Comment by johanhaleby** [comment]
_From [jacek.ku...@gmail.com](https://code.google.com/u/106130598148880712553/) on March 16, 2015 09:01:56_

Looks like the server (which is the Bitbucket REST API) indeed doesn't send an authentication request - it immediately sends a 403 instead of a 401 with a WWW-Authenticate header.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 16, 2015 09:14:13_

Ok so that seem explains why it doesn't work. I don't see any reason why basic auth shouldn't work with DELETE requests so I think that perhaps it's an invalid issue? What do you think?

**Comment by johanhaleby** [comment]
_From [jacek.ku...@gmail.com](https://code.google.com/u/106130598148880712553/) on March 17, 2015 03:12:56_

My only concern is why other HTTP methods work with the non-preemptive auth (e.g. GET works even though the server behaves similarly to DELETE, i.e. sends a 403 instead of a 401 if no auth header is present).

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 17, 2015 04:07:38_

Oh sorry I forgot about that. I know this could be a bit much to ask but would it be possible for you to check in wireshark (or something similar) and compare the differences between the REST Assured and the "other framework" request when you try to do basic auth? Couldn't it be that the other frameworks are indeed using preemptive basic auth? It's very hard for me to fix this problem without knowing this. I would kind of tumble in the dark.

**Comment by ferylukacs** [comment]
What was the final solution @johanhaleby ?

**Comment by johanhaleby** [comment]
I don't remember. Try to use preemptive basic auth?
