### ISSUE TITLE
ResponseSpecBuilder Logging

### ISSUE THREAD

**Issue by fmag7** [rest-assured/rest-assured#579]
RequestSpecBuilder allows setting logging details e.g.:
`new RequestSpecBuilder().log(LogDetail.BODY);`
The ResponseSpecBuilder however does not provide such functionality. Do I miss something?

**Comment by johanhaleby** [comment]
Unfortunately I don't think you're mistaken. I remember I had some problems implementing support for that in the response specification but I don't remember exactly what it was... Perhaps it's not even a problem anymore. Would you like to help out and try to implement it? I would very much appreciate a pull request.

**Comment by Helmsdown** [comment]
Just ran into this. +1 for this request.

**Comment by tomasbjerre** [comment]
Would also like to have this! +1

**Comment by apodkutin** [comment]
@johanhaleby could you please assign it to me?
If it's still relevant.

**Comment by johanhaleby** [comment]
@apodkutin Sure! Thanks for wanting to help out.

**Comment by johanhaleby** [comment]
@apodkutin Hmm doesn't seem like it's possible to assign you, not sure why.

**Comment by apodkutin** [comment]
NP, I've just wanted to highlight that I will work on it. 
I will let you now when PR will be created.

**Comment by johanhaleby** [comment]
@apodkutin Thanks, really appreciated!

**Comment by apodkutin** [comment]
Hi @johanhaleby, sorry for delay with PR. 
Here it is #1096, could you please check it?

**Comment by johanhaleby** [comment]
I merged to PR now! Thanks a lot for the help.
