### ISSUE TITLE
Add assert message to test

### ISSUE THREAD

**Issue by miwashiab** [rest-assured/rest-assured#679]
given()
    .log().all()
.when()
    .get("/path")
.then()
    .statusCode(HttpStatus.SC_OK).assertMessage("Get /path must return statuscode OK!")
    .body("size()", greaterThan(0)).assertMessage("Get /path must return atleast one item!")

to get similar behaviour as
assertTrue("Must be true", condition);

**Comment by johanhaleby** [comment]
Interesting idea. It'll probably not read like that though, more likely something like this:

```java
.. .body("size()", withDescription("Get /path must return atleast one item!"), greaterThan(0)). ..
```

Implementation note:

Expand "Argument interface" (`withArgs`) concept to be broader. Maybe "Argument interface" should extend from "Option" Interface or something.. Q: What about both `withArgs` and `withDescription`?

**Comment by maciejsobala** [comment]
Any progress on this feature?

**Comment by johanhaleby** [comment]
Sorry not yet :(

**Comment by vvingolds-allpago** [comment]
Any news?

**Comment by techbecca** [comment]
Know that this is a wanted feature! I am desperate to combine the customised error message with the logging on failed validation. The only solution I've come up with so far is to write my own assert class, which tries and catches the assertion errors from response validations and then adds the personalised message by throwing a new assertion errors.

**Comment by MaciejWysocki** [comment]
I would like to have message code in
`then().statusCode(403)`
like this example:
`then().statusCode("Setup test user.", 403)`
or on different level like this:
`given().onFailMessage("Setup test user.")`

**Comment by tsuhachev** [comment]
It would be also helpful in case I would like to extract a business failure message from the response body and include it into the assertion message, rather than search for it in the log.

**Comment by Frechet** [comment]
Hi everyone. I would like to add another reason for this request.
Our  tests should be done in parallel, so we want to see a log with assert. 

Now it looks like this:
//log with another execution
java.lang.AssertionError: 1 expectation failed.
XML path items.size doesn't match.
Expected: is <3>
  Actual:  4
//log with another execution

So we should do this:
response.then()
.body("items.size"), describedAs("Expected 3. Fail. Request=" +  request  + ". Response="  + response, is(3)))
.body("items[0].name"), describedAs("Expected Kenobi. Fail. Request=" +  request  + ". Response=" +  response, is(3)))
... // about 10 -20 same lines

But a good solution for me should looks like this:
response.then()
.body("items.size"), is(3))
... // about 10 -20 same lines without repeat "describeAs" with expected value
.onFailMessage("Fail. Request=" +  request +  "Reesponse="  + response)

java.lang.AssertionError: Fail. Request="some request". Response="some response".
1 expectation failed.
XML path items.size doesn't match.
Expected: is <3>
  Actual:  4

I want to realize it for this project, that you think abot this?

**Comment by Frechet** [comment]
I have created pull request, could you look it please?
I chose the next solution: it was added on fail message builder for response specification that add user message to final mismatch description. For message of every matcher I support the idea of using Hamcrest.

**Comment by johanhaleby** [comment]
@Frechet Thanks! I'll take a look!

**Comment by marvedly** [comment]
How's it going for ye folks? :)

**Comment by Frechet** [comment]
@marvedly Hello, you can check my pull request (https://github.com/rest-assured/rest-assured/pull/1131) and vote for this feature. Now this fix is not actual for me, but i think something like this can be useful.

**Comment by arsh711** [comment]
Can we add the same logic for rest-assured library for java in
ValidatableResponseOptionsImp class?
