### ISSUE TITLE
asInputStream can never return CloseHTTPClientConnectionInputStreamWrapper if content==null

### ISSUE THREAD

**Issue by viralkamdar** [rest-assured/rest-assured#685]
RestAssuredResponseOptionsGroovyImpl:asInputStream() method is defined as below:
============================================================================
InputStream asInputStream() {
    if (content == null || content instanceof InputStream) {
      new CloseHTTPClientConnectionInputStreamWrapper(config.getConnectionConfig(), connectionManager, content)
    } else {
      content instanceof String ? new ByteArrayInputStream(convertStringToByteArray(content)) : new ByteArrayInputStream(content)
    }
  }
============================================================================

RestAssuredResponseOptionsGroovyImpl:charsetToString(charset) : is defined as below
============================================================================
def charsetToString(charset) {
    if (content == null) {
      return ""
    }
============================================================================

So if I invoke getBody() or body() method on a response, the response String can never be null.
For my HTTP request, I get HTTP error 415 and response is null. For this response, I want to close the InputStream as it is not closed automatically.
With the above code, asInputStream() method returns me an instance of ByteArrayInputStream which is of no use to me as the response is "" (null converted to ""). The actual stream is never closed.

If I invoke asInputStream() before body(), I get an instance of CloseHTTPClientConnectionInputStreamWrapper which wraps the content. I still cannot call inputStream.close() because CloseHTTPClientConnectionInputStreamWrapper:close() method delegates the call to ((InputStream) content).close(). The content is null in this case. So I get NullPointerException. This condition should be handled gracefully.

**Comment by viralkamdar** [comment]
Sure I will fix it.

**Comment by johanhaleby** [comment]
How's it going?

**Comment by johanhaleby** [comment]
Fixed the NPE CloseHTTPClientConnectionInputStreamWrapper

**Comment by manoj7shekhawat** [comment]
Hey Johan,

Under which version your fix is available?

**Comment by johanhaleby** [comment]
3.0.0
