### ISSUE TITLE
Is it possible to depth search on Json ?

### ISSUE THREAD

**Issue by mukul4u2005** [rest-assured/rest-assured#689]
`"details": { [ {
    "storeA":
    {
        "book":
        [ 
            { "category": "reference",
              "author": "Nigel Rees",
              "title": "Sayings of the Century",
              "price": 8.95
            },
            { "category": "fiction",
              "author": "Evelyn Waugh",
              "title": "Sword of Honour",
              "price": 12.99
            },
            { "category": "fiction",
              "author": "Herman Melville",
              "title": "Moby Dick",
              "isbn": "0-553-21311-3",
              "price": 8.99
            },
            { "category": "fiction",
              "author": "J. R. R. Tolkien",
              "title": "The Lord of the Rings",
              "isbn": "0-395-19395-8",
              "price": 22.99
            }
        ],
        "bicycle":
        {
            "color": "red",
            "price": 19.95
        }
    },
	
	  "storeB":
    {
        "book":
        [ 
            { "category": "reference",
              "author": "Nigel Rees",
              "title": "Sayings of the Century",
              "price": 8.95
            },
            { "category": "fiction",
              "author": "Evelyn Waugh",
              "title": "Sword of Honour",
              "price": 12.99
            },
            { "category": "fiction",
              "author": "Herman Melville",
              "title": "Moby Dick",
              "isbn": "0-553-21311-3",
              "price": 8.99
            },
            { "category": "fiction",
              "author": "J. R. R. Tolkien",
              "title": "The Lord of the Rings",
              "isbn": "0-395-19395-8",
              "price": 22.99
            }
        ],
        "bicycle":
        {
            "color": "red",
            "price": 19.95
        }
    }
	
	
} ] }`

`with(Object).get("details.storeA.book.findAll {book -> book.price < 10}");`

`with(Object).get("details.storeB.book.findAll {book -> book.price < 10}");`

 What I have to do I have to give full path here for both store A and B . Is there way like wild char expression  to return the json string in one line. becuase the json can be dynamic means there can be multiple store.

And response should be like as:

`{
    "storeA":
    {
        "book":
        [ 
            { "category": "reference",
              "author": "Nigel Rees",
              "title": "Sayings of the Century",
              "price": 8.95
            },
           
            { "category": "fiction",
              "author": "Herman Melville",
              "title": "Moby Dick",
              "isbn": "0-553-21311-3",
              "price": 8.99
            }
        ],
        "bicycle":
        {
            "color": "red",
            "price": 19.95
        }
    },
	
	  "storeB":
    {
        "book":
        [ 
            { "category": "reference",
              "author": "Nigel Rees",
              "title": "Sayings of the Century",
              "price": 8.95
            },
            
            { "category": "fiction",
              "author": "Herman Melville",
              "title": "Moby Dick",
              "isbn": "0-553-21311-3",
              "price": 8.99
            }
            
        ],
        "bicycle":
        {
            "color": "red",
            "price": 19.95
        }
    }
	
	
}`

Please suggest about this.

**Comment by johanhaleby** [comment]
No this is (unfortunately) not possible afaik. This is a limitation in
groovy json slurper.

Regards
/Johan
