### ISSUE TITLE
Feature request: ability to use ResponseAwareMatcher for headers

### ISSUE THREAD

**Issue by sebster** [rest-assured/rest-assured#692]
The ValidatableResponseOptions class has body(...) methods that allow the use of ResponseAwareMatchers. However, similar header(...) methods are not available.

In many REST APIs when you do a POST to a collection resource a 201 Created response is returned with a Location header containing the URL of the newly created resource. Many times this has the form http://host:port/collection/{id}. I would be able to verify that the URL in the location is consistent with the "id" path in the body. header(...) methods for ResponseAwareMatchers would allow this. Another case in which this is useful is for validating HTTP Link headers.

**Comment by johanhaleby** [comment]
Interesting. Could you see this being used everywhere? For example cookies and statusCode!?

**Comment by sebster** [comment]
No, I don't really see either as a very common use case.

For status codes I can imagine them being repeated in the body in case of an error response (in fact Spring Boot does this by default, returning a JSON error object with the status code, error message and other stuff), but if you really wanted to test this it seems more logical to me to simply use the ResponseAwareMatcher in the body(...) method and check that the value is the same as response.statusCode(). I can't really think of any other use case.

For cookies I'm less sure except that I don't see cookies used much with REST services at all (as it's common to design them to be stateless). And if you use cookies for auth tokens I would also expect them to be random strings or somesuch, and not be repeated in the body. 

So for me it's really only the headers that I'm missing the ResonseAwareMatcher for.

**Comment by johanhaleby** [comment]
Thanks for your feedback. I think it's better to start with headers then and if people are request it elsewhere we could implement it later.

**Comment by johanhaleby** [comment]
This has now been implemented in master and will be a part of the next release
