### ISSUE TITLE
Proxy Authentication with https - 407 - Proxy Credentials not being passed to HTTP CONNECT

### ISSUE THREAD

**Issue by robertgates55** [rest-assured/rest-assured#693]
Am trying to GET an https website (facebook in the example below), going via a proxy that requires authentication. I'm getting a 407 (authentication required) response code when making the call with rest assured.

Doing the same using firefox and analysing the packet capture in wireshark, I see the following call being made:
![image](https://cloud.githubusercontent.com/assets/7437497/15292343/998a4136-1b7a-11e6-881f-fd662d9aedd9.png)

The proxy passes this through, and the page is successfully retrieved.

In Rest Assured (v2.9.0) I'm making the following call:
```
   given().proxy(host("pxy.int.ws.blah.net").withPort(3128).withAuth("user_blah@blah.com","Password1"))
                .log().everything()
                .when().get("https://facebook.com")
                .then().statusCode(200);
```

and the equivalent CONNECT message being sent is:
![image](https://cloud.githubusercontent.com/assets/7437497/15292351/9fd8573a-1b7a-11e6-9d31-060025d55235.png)
(note - no proxy authentication section, despite the `withAuth` in my call)

The response received is then 407 - "Proxy Authentication Required"

I've tried http calls, and these work fine. I've also tried adding `.withScheme('https')` to my proxy spec, but this then calls an https:// version of the proxy - which gives me a connection refused. The correct call should be a CONNECT to the http:// proxy, with credentials, to instantiate a tunnel through which secure traffic will then flow.

Is there any way to get this to work? I've tried providing headers etc in my calls, but these seem to be being ignored for the initial CONNECT call!

**Comment by johanhaleby** [comment]
Thanks for a detailed repor,  looks like be a bug. To be honest we only have tests for with a http proxying and I've not tested https proxying. Are you familiar a free proxy I can use to verify this?

**Comment by robertgates55** [comment]
I'll try & get you access to an instance of our project's proxy today [and send via DM], but for future testing we're using squid (Which I believe is free?)

Was also trying to work around it by providing a custom httpclient with the proxy settings configured. When I do the following:

```
        given()
                .config(RestAssured.config().httpClient(HttpClientConfig.httpClientConfig().httpClientFactory(() -> {
                    DefaultHttpClient client = new DefaultHttpClient();
                    HttpHost proxy = new HttpHost("proxy.int.ws.blah.net", 3128);
                    ConnRouteParams.setDefaultProxy(client.getParams(), proxy);

                    UsernamePasswordCredentials credentials = new UsernamePasswordCredentials("proxy_user_blah@blah.com","Password1");
                    AuthScope scope = new AuthScope("proxy.int.ws.blah.net", 3128);
                    client.getCredentialsProvider().setCredentials(scope, credentials);
                    return client;
                })))
              //.proxy(host("pxy.int.ws.blah.net").withPort(3128).withAuth("proxy_user_blah@blah.com","Password1"))
                .log().everything()
                .when().get("https://facebook.com")
                .then().statusCode(200);
```
(nb - have commented out the standard proxy spec but left it there for reference) the calls are not going via the proxy any more:

```
08:54:17.678 [main] INFO  - starting com.smc.tests.web.HttpsTest.instantiationTest_https
Request method:	GET
Request path:	https://facebook.com
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:		<none>
Headers:		Accept=*/*
Cookies:		<none>
Body:			<none>
08:54:21.784 [main] INFO  - PASS com.smc.tests.web.HttpsTest.instantiationTest_https
```

What am I doing wrong, and why isn't RA picking up my custom httpclient?

**Comment by robertgates55** [comment]
Out of interest, I've tried making the call directly with HttpClient, and it works as expected:

```
        DefaultHttpClient client = new DefaultHttpClient();
        HttpHost proxy = new HttpHost("pxy.int.ws.streamshield.net", 3128);
        ConnRouteParams.setDefaultProxy(client.getParams(), proxy);

        UsernamePasswordCredentials credentials = new UsernamePasswordCredentials("user_384364539@wtqt.com", "Password1");
        AuthScope scope = new AuthScope("pxy.int.ws.streamshield.net", 3128);
        client.getCredentialsProvider().setCredentials(scope, credentials);

        HttpGet request = new HttpGet("https://facebook.com");

        HttpResponse response = client.execute(request);
```
Gives a 200 response, and I can see the correct calls being made in Wireshark:

CONNECT (without proxy-authorization header)
407 response from proxy
CONNECT (WITH proxy-authorization header)
....tunnel formed and http get works as expected.

Using RA, either with or without the `.config(` shown above I just get the initial CONNECT and the 407 response.

**Comment by johanhaleby** [comment]
Thanks! The code examples are a great reference. I'll try to see what's going on, but it'll take a couple of days until I find the time to look into it probably.

**Comment by robertgates55** [comment]
Cheers Johan - that's great.

Am trying to work around it for now using the HttpClient approach above - is there any way to cast an HttpResponse back into a restassured Response object? A lot of my tests rely on this call returning a com.jayway.restassured.response.Response object!

**Comment by johanhaleby** [comment]
👍

**Comment by johanhaleby** [comment]
Ok I think I've managed to fix this now. Took me several hours to figure out why it didn't work. The trouble was that REST Assured implements a custom route selector in order to pick up proxy settings defined as JVM arguments. This resolved the host name to its IP which meant that http client auth didn't match the hostname defined in the `ProxySpecification` and thus http client didn't provide the authentication details. But I'm not 100% sure why it didn't work before since I didn't use the http client features to send the proxy authorization header. It does now though (which is probably for the better) so I think it should work.

I've now deployed a new snapshot that should address this issue. Please try version `2.9.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

I'll close the issue for now. Tell me if it doesn't work.

**Comment by sofiamferreira** [comment]
Could you please clarify what should be the maven dependency to be added in the pom 
 <dependency>
            <groupId></groupId>
            <artifactId></artifactId>
            <version></version>
        </dependency>
regarding the 2.9.1-SNAPSHOT version that you make reference in your last comment? @johanhaleby 

Many thanks
