### ISSUE TITLE
restassured 2.9.0 installed via grape (@Grab in groovy) works only with groovy 2.4.4, old restassured 1.7 works fine with many different groovy versions 

### ISSUE THREAD

**Issue by luv** [rest-assured/rest-assured#697]
Following groovy script works like a charm:
```
@Grab("com.jayway.restassured:rest-assured:1.7")

import com.jayway.restassured.RestAssured

RestAssured.get("http://example.com")
```

but after updating 1.7 to 2.9.0 
```
@Grab("com.jayway.restassured:rest-assured:2.9.0")

import com.jayway.restassured.RestAssured

RestAssured.get("http://example.com")
```

grape install fails with 

"General error during conversion: Error grabbing Grapes -- [download failed: org.apache.httpcomponents#httpclient;4.5.1!httpclient.jar, download failed: org.apache.httpcomponents#httpcore;4.4.3!httpcore.jar]"

but nevermind, nothing you can do about this I suppose. Moreover, it works after commenting out some magic XML 

```<ibiblio name="localm2" root="file:${user.home}/.m2/repository/" checkmodified="true" changingPattern=".*" changingMatcher="regexp" m2compatible="true"/>``` in grapeConfig.xml specifically. Don't ask.

But the issue I'd like to report is this:

```
Caught: java.lang.IncompatibleClassChangeError: the number of constructors during runtime and compile time for com.jayway.restassured.internal.RequestSpecificationImpl$EncodingTarget do not match. Expected -1 but got 2
java.lang.IncompatibleClassChangeError: the number of constructors during runtime and compile time for com.jayway.restassured.internal.RequestSpecificationImpl$EncodingTarget do not match. Expected -1 but got 2
	at com.jayway.restassured.internal.RequestSpecificationImpl$EncodingTarget.$INIT(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$EncodingTarget.<clinit>(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$_partiallyApplyPathParams_closure31.doCall(RequestSpecificationImpl.groovy:1676)
	at com.jayway.restassured.internal.RequestSpecificationImpl.partiallyApplyPathParams(RequestSpecificationImpl.groovy:1679)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1039)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1594)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:160)
	at com.jayway.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.RestAssured.get(RestAssured.java:808)
```

Looks like restassured 2.9.0 is not compatible with groovy 1.8.6 ?

**Comment by luv** [comment]
Yup, using restassured 2.9.0 with groovy "Grape" functionality works *only* with groovy 2.4.4.

Groovy 2.4.6 fails with
```
General error during conversion: Conflicting module versions. Module [groovy-xml is loaded in version 2.4.6 and you are trying to load version 2.4.4
```

**Comment by luv** [comment]
I have tested `@Grab("com.jayway.restassured:rest-assured:1.7")` and `@Grab("com.jayway.restassured:rest-assured:2.9.0")` with groovy 1.8.6, 2.4.4 and 2.4.6 and rest-assured 1.7 works with each one. rest-assured 2.9.0 only with 2.4.4

**Comment by luv** [comment]
Alright, I got it figured out :). This works:

```
@Grab("com.jayway.restassured:rest-assured:2.7.0")
@GrabExclude("org.codehaus.groovy:groovy-xml")
@GrabExclude("org.codehaus.groovy:groovy-json")
```

maybe this would deserve a note in the docs :)

**Comment by johanhaleby** [comment]
Thanks for sharing, this is also included in the [FAQ](https://github.com/rest-assured/rest-assured/wiki/FAQ).

**Comment by luv** [comment]
Thanks johan. It's actually two unrelated problems.

I am sorry I caused confusion by my original report with groovy 1.8.6 and "IncompatibleClassChangeError". I should have *not* reported that, it is no surprise latest rest-assured does not work with such an old version of groovy. 

The real issue is "General error during conversion: Conflicting module versions. Module [groovy-xml is loaded in version 2.4.6 and you are trying to load version 2.4.4". This happens when running rest-assured 2.9.0 in a groovy script with any recent version of groovy except 2.4.4.

*That* can be solved by the two @GrabExclude lines. I think it could benefit other end users to mention this in the docs explicitly as well, but it's up to you, of course.

(if you are just too busy, I don't mind writing that paragaph myself to help others (and possibly myself in the future ;) ))

sorry about the confusing original bug report, I just ran into too many seemingly related problems at once

**Comment by johanhaleby** [comment]
Sorry that I've been so short but I am indeed quite busy :)

Is rest-assured depending on different versions of groovy and groovy-xml and groovy-json!? If not why do we get a transitive dependency to 2.4.4 *and* 2.4.6? If so it's something that must be addressed in the build?

**Comment by luv** [comment]
It rather seems this is caused by dependency on groovy-xml and groovy-json *at all*. Because of that rest-assured can not be used in a groovy script when executed with any another groovy version than the version rest-assured was built against (unless groovy is instructed not to load groovy-json and groovy-xml bundled in rest-assured jar with the @GrabExclude annotations). 

That's because when **used as a script** groovy loads its own groovy-xml.jar, groovy-json.jar etc. (as defined in groovy-starter.conf). That causes both groovy-xml-2.4.4 (required by rest-assured) and groovy-xml-2.4.x loaded in ... groovy does not like that and exits with `General error during conversion: Conflicting module versions. Module [groovy-xml is loaded in version 2.4.6 and you are trying to load version 2.4.4`.

Does not happen when building with maven or gradle, because in this case users do include "groovy-all" and not the individual groovy modules.

**Comment by johanhaleby** [comment]
Ah ok I didn't know that, interesting. In a much earlier release of REST Assured it depended on `groovy-all` but I removed this to cut down on the dependency size.

But how should we solve this? Is adding your solution to the FAQ the best we can do?

**Comment by luv** [comment]
Yeah it took me a while to understand why I'm getting the error.

And yes, I am afraid adding this to the FAQ is the best that can be done :/.

**Comment by johanhaleby** [comment]
Added it to the FAQ now. Thanks for helping out.

**Comment by luv** [comment]
great, thanks.
