### ISSUE TITLE
It is NOT possible to set "Content-Type" header to exact value

### ISSUE THREAD

**Issue by luv** [rest-assured/rest-assured#698]
```
 given()
            .header("Content-Type", "text/csv")
            .put("/foo")
```

will not make a request with header "Content-Type: text/csv" but with header "Content-Type: text/csv; charset=ISO-8859-1". I haven't found a way how to disable this behaviour.

In certain use-cases, for example AWS, it is necessary to send *exact* Content-Type header.

**Comment by johanhaleby** [comment]
https://github.com/rest-assured/rest-assured/wiki/Usage#avoid-adding-the-charset-to-content-type-header-automatically

**Comment by luv** [comment]
thanks
