### ISSUE TITLE
No queryParam method set to queryString in url

### ISSUE THREAD

**Issue by LEEMYEONGHYEON** [rest-assured/rest-assured#699]
I want to add queryParams in sending request url. but, queryParam method isn't set to url.
test :
``` java
given().log().all()
	.queryParam("projectId", "project")
	.queryParam("page", 0)
	.queryParam("size", 3)
.when()
	.get("/api/posts")
.then().log().all()
```
request log is :
```
Request method:	GET
Request path:	http://localhost:8080/api/posts?projectId=project&page=0&size=3
Proxy:			<none>
Request params:	<none>
Query params:	projectId="project"
				page=0
				size=3
```

log is ok. 
but if I get the requestURI from **HttpServletRequest** i couldn't find queryString in url
``` java
String url = ServletUriComponentsBuilder.fromCurrentRequest().build().toString();
assertTrue(url, is("http://localhost:8080/api/posts");
```

I think **MockMvcRequestSenderImpl.sendRequest()** should make uri with **queryParams** before building **MockHttpServletRequestBuilders** for setting queryString in **MockHttpServletRequest**

**Comment by johanhaleby** [comment]
Is this how vanilla MockMvc does things? Could you help out and provide a pull request if so?

**Comment by LEEMYEONGHYEON** [comment]
I just used **com.jayway.restassured.module.mockmvc.RestAssuredMockMvc.webAppContextSetup()** for spring-mock-mvc.
https://github.com/rest-assured/rest-assured/wiki/Usage#using-spring-security-test

I'll try fix it and provide pull request.

**Comment by johanhaleby** [comment]
Thanks! I'll hopefully make a new release soon and it would be nice to include this fix.
