### ISSUE TITLE
Could not parse content-type: Response does not have a content-type header

### ISSUE THREAD

**Issue by tramstheman** [rest-assured/rest-assured#701]
Expected Result:
Success response from apple.

Actual Result:
com.jayway.restassured.internal.http.ResponseParseException: Apple WebObjects

Steps to Recreate:

RestAssured
                .given()
                .body(String.format("{ \"receipt-data\": %s}", _testReceipt))
                .contentType("application/json")
                .headers(headers)
                .post("https://buy.itunes.apple.com/verifyReceipt").prettyPrint();

getting no response and this error: 
com.jayway.restassured.internal.http.ResponseParseException: Apple WebObjects

**Comment by johanhaleby** [comment]
Thanks. The reason is the Apple doesn't return an integer cookie version. I've improved the code and committed to master.

**Comment by tramstheman** [comment]
It is still breaking, except now I also get "Caused by: java.lang.IllegalArgumentException: Version cannot be less than 0" 

Since its a non integer cookie, it is setting it to -1 which forces that error. Is there to allow non integer cookie version?

**Comment by johanhaleby** [comment]
Hmm no.. This convince me that cookie version parsing is wrong and cannot be an integer.. BTW are you using version 3.0.0?

**Comment by tramstheman** [comment]
Yes, Im using 3.0.1-SNAPSHOT. 
Other than the error being thrown, everything looks good in the response in debugging.

**Comment by johanhaleby** [comment]
Please try the 3.0.0 release first (non snapshot version). And no, I won't remove parsing of the cookie version but if you still have problems in 3.0.0 I think we shouldn't try to force it to be an integer.

**Comment by tramstheman** [comment]
yep its working now. Sorry about that, i thought you when you said you moved it to master that I should use the snapshot. Thanks again!

**Comment by johanhaleby** [comment]
Ok glad to hear it. If you run into a similar problem again then please let us know.

**Comment by kkashyap1707** [comment]
**Request** 
Response res = RestAssured.given()
								  .headers("accesstoken",TestBase.Access_Token)	
								  .contentType("application/json")
								  .body(this)
								  .when()
								  .get()
								  ;

and I got Response :- 

testNotificationsNumber(com.api.truValue.test.notifications.NotificationsTest)  Time elapsed: 1.86 sec  <<< FAILURE!
java.lang.IllegalStateException: 
Cannot invoke the path method because no content-type was present in the response and no default parser has been set.

You can specify a default parser using e.g.:
RestAssured.defaultParser = Parser.JSON;

	at com.api.truValue.test.notifications.NotificationsTest.testNotificationsNumber

**Comment by johanhaleby** [comment]
@kkashyap1707 I don't understand what's going on. I suspect that what you've pasted here is not the actual code you're using?

**Comment by venkywarriors619** [comment]
> Please try the 3.0.0 release first (non snapshot version). And no, I won't remove parsing of the cookie version but if you still have problems in 3.0.0 I think we shouldn't try to force it to be an integer.

if i add 3.0.0 it is showing missing artifact 
<dependency>
    <groupId>com.jayway.restassured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>3.0.0</version>
    <scope>test</scope>
</dependency>
