### ISSUE TITLE
Best practises - Usage of JsonPath vs Marshalling strongly typed objects

### ISSUE THREAD

**Issue by mattadamson** [rest-assured/rest-assured#705]
Hi,

We really like the framework however I was considering best practises and guidance around which of the two approaches to use when asserting responses against expectations

1) Using JsonPath to query the JSON returned e.g. to extract inner attributes
2) Retrieving and marshalling a strongly typed object e.g. JAXB object or standard Java POJO

Whilst 1 is very flexible 2 seems preferable because you are working on the object reference returned directly. If the interface changes slightly e.g. attributes / types renamed or new structures added to you can easily detect this through a compiler error. You also get compiler checking eg. when asserting a property rather than using a string literal.

Appreciate your thoughts

**Comment by johanhaleby** [comment]
Hi. Please use the mailing list when asking these questions.
