### ISSUE TITLE
Unable to store the sessionid from a post to next get request

### ISSUE THREAD

**Issue by DivyaGN** [rest-assured/rest-assured#706]
Hi I am trying to write this code for the first time to use the same session for multiple rest calls.

my application has a autentication url and the same sessiln i have to use to do get requests further.

Please help me out......

package API;

import org.junit.Test;

import io.restassured.RestAssured;
import io.restassured.filter.session.SessionFilter;

import static org.junit.Assert.*;

public class Sample {
    @Test
    public void testLogin() {
    	String myJson = "{\"AuthenticateUserRequest\":{\"user\":{\"userName\":\"divya\",\"password\":\"***********!\"}}}";
        SessionFilter session1 = new SessionFilter();
        String sessionId = session1.getSessionId();

        RestAssured.given().
                filter(session1).
                contentType("application/json").body(myJson).
                when().
                post("http://as-rtp-infra-virl-dev-web01.cisco.com:8080/netsim/authenticate").
                then().
                statusCode(200);

        RestAssured.given().
                filter(session1).
                when().
                get("http://as-rtp-infra-virl-dev-web01.cisco.com:8080/netsim/projects").
                then().
                statusCode(200);

    }
}
 also tried

package API;

import org.junit.Assert;
import org.junit.Test;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import io.restassured.filter.Filter;
import java.io.FileInputStream;
import java.util.Properties;

import org.hamcrest.Matchers;

public class ProjectInfo {
 
	@Test
	public void RestSession_basicauth() {
				
		String myJson = "{\"AuthenticateUserRequest\":{\"user\":{\"userName\":\"Divya\",\"password\":\"*********!\"}}}";
		System.out.println(System.getProperty("user.dir"));
		Properties prop = new Properties();
		FileInputStream file;
		try {
			file = new FileInputStream(System.getProperty("user.dir")+"//ConfigFile//TestData.properties");
			prop.load(file);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		String URL1 = prop.getProperty("AuthenticateURI");	
		String URL2 = prop.getProperty("ProjectDetailsURI");	
		
		
		Response response=RestAssured.given().contentType("application/json").body(myJson).expect().statusCode(200).log().ifError().when().post(URL1);
		
		String sessionId = response.sessionId();
		
		response = RestAssured.given().
                contentType("application/json").cookie("JSESSIONID=" + sessionId).when().get(URL2);

		String Body =response.getBody().asString();
		System.out.println(Body);
		
		Assert.assertThat(response.getStatusCode(), Matchers.equalTo(200));
		
		
		  
		
		
}
	
	
}

**Comment by johanhaleby** [comment]
Is the name of the cookie JSESSIONID? If not may can configure the SessioFilter to use another name. Maybe you can also use the new CookieFilter (version 3.0.0) and see if that works?

**Comment by DivyaGN** [comment]
Hey that worked thank u

**Comment by johanhaleby** [comment]
Did you change the session id name or just used the CookieFilter?

**Comment by DivyaGN** [comment]
I have done a CookieFilter

**Comment by MirekSh** [comment]
@DivyaGN Hey, how You managed to extract String value from CookieFilter?
