### ISSUE TITLE
Add feature: request and response detail from REST Assured test to Surefire report

### ISSUE THREAD

**Issue by sargue** [rest-assured/rest-assured#707]
I do need a feature from REST Assured. I [asked how to do it on SO](http://stackoverflow.com/questions/37876826/add-request-and-response-detail-from-rest-assured-test-to-surefire-report) to no avail. I think it just can't be done currently.

So this is a formal request to add it as a new feature to REST Assured.

Thank you.

-------------

One of the useful features of the library is the ability to [log the request and response in case of a failed test](https://github.com/rest-assured/rest-assured/wiki/Usage#logging) so you can check what was sent to the REST service.

## Request example ##

An example of a failing test which logs both the request and the response

    import io.restassured.RestAssured;
    import org.junit.Before;
    import org.junit.Test;
    
    import static io.restassured.RestAssured.*;
    import static org.hamcrest.Matchers.*;
    
    public class TestRestAssured {
      @Before
      public void setUp() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
      }
    
      @Test
      public void exampleFailingTest() {
        String json = "{\n" +
            "  \"title\": \"foo\",\n" +
            "  \"body\": \"bar\",\n" +
            "  \"userId\": 1\n" +
            "}";
        given()
            .contentType("application/json; charset=UTF-8")
            .body(json)
            .post("http://jsonplaceholder.typicode.com/posts")
            .then()
            .body("userId", equalTo(2));
      }
    }

This test fails because the returned `userId` is 1. This is what's printed on the console when executing the test.

    Request method:	POST
    Request URI:	http://jsonplaceholder.typicode.com/posts
    Proxy:			<none>
    Request params:	<none>
    Query params:	<none>
    Form params:	<none>
    Path params:	<none>
    Multiparts:		<none>
    Headers:		Accept=*/*
    				Content-Type=application/json; charset=UTF-8
    Cookies:		<none>
    Body:
    {
        "title": "foo",
        "body": "bar",
        "userId": 1
    }
    
    HTTP/1.1 201 Created
    Server: Cowboy
    Connection: keep-alive
    X-Powered-By: Express
    Vary: Origin, X-HTTP-Method-Override, Accept-Encoding
    Access-Control-Allow-Credentials: true
    Cache-Control: no-cache
    Pragma: no-cache
    Expires: -1
    X-Content-Type-Options: nosniff
    Content-Type: application/json; charset=utf-8
    Content-Length: 65
    Etag: W/"41-+JqcAMRWkzuXd+uFDZdzIA"
    Date: Fri, 17 Jun 2016 08:18:59 GMT
    Via: 1.1 vegur
    
    {
        "title": "foo",
        "body": "bar",
        "userId": 1,
        "id": 101
    }
    
    java.lang.AssertionError: 1 expectation failed.
    JSON path userId doesn't match.
    Expected: <2>
      Actual: 1
    
    
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        [rest of the stacktrace]

## The problem ##

It is a great feature as it allows to report more contextful bug reports. Under the hood it uses a [`LogConfig`](http://static.javadoc.io/io.rest-assured/rest-assured/3.0.0/io/restassured/config/LogConfig.html) which you can configure to write to any `PrintStream` defaulting to `System.out`.

The [Maven Surefire plugin](http://maven.apache.org/surefire/maven-surefire-plugin/index.html) reports errors on two files (text and XML). But on these files it **only includes the content from the exception thrown by the test method**. So the detail from the report looks like this:

    java.lang.AssertionError: 1 expectation failed.
    JSON path userId doesn't match.
    Expected: <2>
      Actual: 1
    
    
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        [rest of the stacktrace]

Which is nice but could be nicer.

## The request ##

Should be pretty obvious by now.

An option to include the request and response detail from REST Assured on the Surefire report.

**Comment by johanhaleby** [comment]
If I remember it correctly surefire also generates other files that includes more than just the exceptions. And even if this is not the case I think it would be wrong to make some specific integrations in REST Assured for Surefire since that would couple RA with Surefire.

**Comment by sargue** [comment]
Not sure about Surefire generating any other files. I've checked and I can't find any.

I wasn't looking for any specific integration for Surefire, far from it! It seems that Surefire just captures the exception so I though maybe there could be any way to add the request and response detail to the exception message.

Currently the exception message is already pretty long and multiline because it's build up on the multiple expectations failed. The request and response detail are just thrown to a PrintWriter (System.out by default). Maybe an option would be to put them **inside** the exception message.

**Comment by johanhaleby** [comment]
Hmm... Need to think about it a bit. Perhaps it would be possible to create an "ExceptionConfig" where one could configure this. Not sure how hard it'll be to implement either though.

But when it comes to Surefire it should (if I'm not mistaken) provide text files ending with "-output.txt" that should contain the console logs.

**Comment by sargue** [comment]
Sorry, not a clue about those "-output.txt" files. Can't find them on my `target` directory from Maven. Maybe you see it with some custom plugin?

The [standard Maven Surefire plugin](http://maven.apache.org/surefire/maven-surefire-plugin/index.html) just outputs two formats of the same information.

Of course there is a lot of information on the console when you execute the `mvn test` task. The problem is that the output there gets mixed with logs and a lot of other information. And it becomes almost impossible to correlate to any individual test.

Anyway thanks for considering it.

**Comment by jcechace** [comment]
@sargue  Perhaps `<system-out>` element in *.xml report files is what you are looking for?

**Comment by sargue** [comment]
@jcechace That's EXACTLY what I was looking for. Missed it completely, thank you man. Now how to put those on the report, but that is another completely different problem.

**Comment by anilkulkarni87** [comment]
@sargue What was solution for this? Were you able to get the request and response onto the reports?

**Comment by sargue** [comment]
Sorry, didn't really remember how I closed this issue. I've finished the project shortly after and moved along.

**Comment by RocketRaccoon** [comment]
@anilkulkarni87 take a look onto Allure Report, which supports request and response details.

**Comment by anilkulkarni87** [comment]
@sargue If you recollect please do post the answer here.
@RocketRaccoon  Thanks I will check it out,. The allure reports look cool.

**Comment by RocketRaccoon** [comment]
@anilkulkarni87, not sure about that, but anyway it would be better to raise an issue in allure-java repo, it has rest-assured 3.0.2 version in dependencies

**Comment by tausif29** [comment]
I am also facing the same problem. Does anyone has solution for this?

@sargue @anilkulkarni87

**Comment by RocketRaccoon** [comment]
@tausif29 if you could provide an example to debug I may spend some time on it

**Comment by tausif29** [comment]
@RocketRaccoon 

Hi,

I want to show up rest assured logs (Request & Response both) in my reports (Surefire/ TestNG) for all the failed test cases.

I am able to print the logs (both request & response) in console whenever failure occurs using below Rest Assured inbuilt method:

``
given().config(RestAssured.config().logConfig(logConfig().enableLoggingOfRequestAndResponseIfValidationFails())).
``
But not able to integrate with my reports, Reports only shows the partial logs like below

``
createTestAction(com.restapitest.actions.TestAction)  Time elapsed: 1.102 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <201> but was <500>.

    at com.restapitest.actions.createTestAction.(TestAction.java:45)
``

**Comment by tausif29** [comment]
@RocketRaccoon 

Its not possible for me to share example to reproduce as all REST calls required authentication details to pass.

I can share what is being printed in surefire-reports
`1 expectation failed.
Expected status code <201> but was <400>.`  

But I want to show request & response of failed tests both under my reports (Which I am able to print under console logs)

**Comment by RocketRaccoon** [comment]
Ok, let's see...
If you can use Allure as a report have you tried this filter - https://github.com/allure-framework/allure-java#rest-assured ? 
When we are talking about your current implementation - Surefire/ TestNG, what exactly report are you using? Surefire Report?

**Comment by tausif29** [comment]
@RocketRaccoon  Currently I am using reportNG,

Ok let me also try allure reports, thanks!

**Comment by vovambo** [comment]
Any news on this? :) Also cannot get the response body, only this ```Expected status code <200> but was <400>.```

found a workaround, but seems ... weird. works though: 
```

public static Response postTest(Object body, String service, int statusCode) {

        ValidatableResponse response = given()
                .contentType(ContentType.JSON)
                .filter(new RequestLoggingFilter())
                .body(body)
                .log()
                .all()
                .post(service)
                .then()
                .log().body();

        int actualSC = response.extract().statusCode();
        assertEquals(response.extract().body().jsonPath().getString(""), statusCode, actualSC);

        return response.extract().response();
    }
```
