### ISSUE TITLE
Wiki: scala-support's groupId is missing the "-"

### ISSUE THREAD

**Issue by AnnaSkawinska** [rest-assured/rest-assured#708]
In [Wiki > Usage Guide > Scala Support Module](https://github.com/rest-assured/rest-assured/wiki/Usage#scala-support-module) the SBT and Gradle code snippets are missing their dash in groupId.

Patch:

`
Usage.md | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/Usage.md b/Usage.md
index 655f01f..175fe81 100644
--- a/Usage.md
+++ b/Usage.md
@@ -2636,7 +2636,7 @@ To use it do like this:
 
 #### SBT:
 ```scala
-libraryDependencies += "io.restassured" % "scala-support" % "3.0.0"
+libraryDependencies += "io.rest-assured" % "scala-support" % "3.0.0"
 ```
 
 #### Maven:
@@ -2651,7 +2651,7 @@ libraryDependencies += "io.restassured" % "scala-support" % "3.0.0"
 
 #### Gradle:
 ```xml
-testCompile 'io.restassured:scala-support:3.0.0'
+testCompile 'io.rest-assured:scala-support:3.0.0'
 ```
 
 ### No build manager:
@@ -2713,4 +2713,4 @@ You can also have a look at some code examples:
 
 If you need support then join the [mailing list](http://groups.google.com/group/rest-assured).
 
-For professional support please contact [johanhaleby](https://github.com/johanhaleby).
\ No newline at end of file
+For professional support please contact [johanhaleby](https://github.com/johanhaleby).
-- 
1.9.1
`

**Comment by johanhaleby** [comment]
Thanks, well spotted! I've fixed it now.

**Comment by AnnaSkawinska** [comment]
Wasn't me, it was my gradle build ;)

**Comment by johanhaleby** [comment]
What? :) How does that work?

**Comment by AnnaSkawinska** [comment]
Well, it won't build if you paste a dependency with a wrong groupId ;)

**Comment by johanhaleby** [comment]
Ah that makes sense :)

Thanks again.
