### ISSUE TITLE
GroovyCastException: InternalHttpClient to class AbstractHttpClient

### ISSUE THREAD

**Issue by manoj7shekhawat** [rest-assured/rest-assured#709]
Hi,

I'm using rest-assured (3.0.0) & httpclient (4.5.2). And I'm trying to configure properties for the HTTP Client instance that REST Assured will be using when executing requests as below:
```
static {
    RestAssured.config = newConfig().httpClient(httpClientConfig().httpClientFactory(() -> {
    PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
    connectionManager.setMaxTotal(100);
    connectionManager.closeExpiredConnections();
    connectionManager.closeIdleConnections(60, TimeUnit.SECONDS);
    return HttpClientBuilder.create().setConnectionManager(connectionManager).build();
    }).reuseHttpClientInstance());
}
```

But I'm getting below Class Class Exception when running my application:
```
Cannot cast object 'org.apache.http.impl.client.InternalHttpClient@4241e0f4' with class 'org.apache.http.impl.client.InternalHttpClient' to class 'org.apache.http.impl.client.AbstractHttpClient'
[13:23:14][:generateAccessTokenTask] 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405)
```

rest-assured should handle this cast exception. Anyways AbstractHttpClient should not be needed as HttpClientBuilder itself returns HttpClient.

**Comment by manoj7shekhawat** [comment]
Looks like I just opened a duplicate issue. This enhancement was requested earlier too:
#704 #497 
and here too: https://groups.google.com/forum/#!topic/rest-assured/cvnBgh_ErAY

As I can see that this requires major refactoring is necessary to support the HttpClient interface and developers have their other priorities as well.

I myself don't have any experience in contributing to open-source community, but I love to learn it if somebody can help me.

**Comment by johanhaleby** [comment]
Hi, 

Yes this is a known issue that has been bugging us for a long time. "Unfortunately" I think the easiest way to learn how the code  works is to just dig in. I would appreciate all the help I can get :)

Regards,
/Johan

**Comment by manoj7shekhawat** [comment]
Hey @johanhaleby. Could be silly question but from where should I start digging?

**Comment by johanhaleby** [comment]
@manoj7shekhawat See https://github.com/rest-assured/rest-assured/issues/497#issuecomment-143404851. I.e. the creating of the HttpClient instance must be delayed until the request is being made. This will affect a lot of things in RA since it assumes that the (Abstract)HttpClient is mutable. The HttpClient interface doesn't support changing attributes after it has been created (which typically is a good thing).

**Comment by manoj7shekhawat** [comment]
@johanhaleby, thanks for showing me direction to explore.

I'll dive-in into code/concepts to understand how things work. I'll get in touch with you if I have some questions.

**Comment by johanhaleby** [comment]
great!

**Comment by RohanPalkar** [comment]
@manoj7shekhawat, @johanhaleby, is there a workaround available for this issue at the moment. If you could please share the same.

**Comment by abhijith-prabhakar** [comment]
any workaround for this issue?  Please share as I am facing same issue

**Comment by YogeshBathri** [comment]
may I know what is the solution provided for this issue? 

also, if possible can somebody link the original defect for reference.
