### ISSUE TITLE
Logging request / response when a unit test assertion fails

### ISSUE THREAD

**Issue by mattadamson** [rest-assured/rest-assured#710]
Team,

Whilst this looks useful 

https://github.com/rest-assured/rest-assured/wiki/Usage#request-logging

I assume it only works if the assertions fail when called through the rest assured library with the response. 

I enabled using

		RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();

However we often add a separate assertion after extracting the Response object directly then use assertThat calls such as 

			response = expect().statusCode(200).with().spec(CsrfSessionRequestSpec).body(listViewRequest).when().post("http://myapp/myurl"));

we then have multiple calls such as 

			assertThat(response.getBody().jsonPath()
				.getString("rows[0].columns.find { it -> it.fieldName == 'MYFIELD' }.fieldValue"))
					.isEqualTo("100");

However if the response is incorrect the assertThat will throw a standard AssertionError exception, the test method exit and nothing will be logged

How do others handle this? Given REST assured has no control over the calls you make outside it's entirely reasonable it can't do anything. Perhaps we simply need to log all request / responses regardless. Then if tests do fail we can look through the logs as required.

**Comment by johanhaleby** [comment]
It can only support rest assured validations:

```java
..then().statusCode(200).body("x.y", equalTo("z"));
```

Once you leave the rest assured DSL you're on your own and there's nothing RA can do.

The only way you might get something like this to work would be to implement something like a JUnit rule and do some sort of soft assertions (like assertj). But this is out of scope of the REST Assured project.
