### ISSUE TITLE
Show multiple expectations for chained ValidatableResponse methods

### ISSUE THREAD

**Issue by RocketRaccoon** [rest-assured/rest-assured#711]
Hi,

In 2.5.0 following feature was introduced:

> REST Assured now show all failing body assertions when using multiple expectations in the same body clause. For example:
`.. then().body("x.y", equalTo("z"), "y.z", is(2)). ..`

It would be useful to have same functionality for the chained methods e.g. `then().body().body()` will fail at the end and print all failed assertions.

**Comment by johanhaleby** [comment]
Yeah that would be nice but this is impossible unless we do some deeper integrations with the test frameworks (which is out of scope for RA "core"). This is why `expect` still exists.

**Comment by RocketRaccoon** [comment]
I do not expect that it will collect exceptions from whole test methods in tests, only per one chained call. I suppose it could be done without invoking test framework.

**Comment by johanhaleby** [comment]
Hmm not quite sure what you mean. If one do `then().body(1).body(2).body(3).body(4)` and `body(3)` fails then 1 and 2 are correct and it won't continue to 4. I suppose you mean that it should continue to 4 now? But this is what I think is impossible, because how do you know that 4 is the last statement and that NOW it's time to print the error messages?

**Comment by RocketRaccoon** [comment]
May be it could be done as soft asserts in TestNG? `then().softAssertThat().body(1).body(2).body(3).body(4).assertAll()`

**Comment by johanhaleby** [comment]
Yes, but this requires changing the API (and you wouldn't need to depend on TestNG to do this) and this is not something I want to do. You can already do what you're asking if you're using expect:

```java
given().param("x", 1).
expect().body(1).body(2).
when().get("/x");
```

You can also do like this:
```java
given().param("x", 1").
when().get("/x").
then().body("x", equalTo(1),
                   "y", equalTo(2));
```

**Comment by RocketRaccoon** [comment]
Yeah, but in that case I can't use `root()`, `appendRoot()`, etc.

**Comment by johanhaleby** [comment]
You can use `appendRoot` and `root` when you use `expect` and you can use before the body expectations when using `then`:

```java
given().param("x", 1").
when().get("/x").
then().
       root("z.w").
       body("x", equalTo(1),
            "y", equalTo(2));
```

You can also create a `ResponseSpecification` and if so all expectations will succeed or fail "atomically":

```java
ResponseSpecification spec = new ResponseSpecBuilder(). ..build();

given().param("x", 1").
when().get("/x").
then().spec(spec);
```

**Comment by RocketRaccoon** [comment]
Ok, I suppose it will be enough
