### ISSUE TITLE
Issues with several matchers in body() - only last matcher is used

### ISSUE THREAD

**Issue by RocketRaccoon** [rest-assured/rest-assured#714]
Hi,

It seems like a bug:
```java
given().param("x", 1").
when().get("/x").
then().
       root("z.w").
       body("x", greaterThan(1),
            "x", equalTo(5),
            "x", lessThan(3));
```
If `x = 2`, no assertion errors would be thrown. If `x = 6`, only last error would be thrown. It works fine (all expected assertions are failing) when `expect()` or `ResponseSpecification` are used.

Is it expected behaviour or something go wrong?

**Comment by johanhaleby** [comment]
Sounds like a bug, I need to look into it. Thanks for reporting.

**Comment by johanhaleby** [comment]
I've now deployed a new snapshot that should address this issue. Please try version `3.0.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by johanhaleby** [comment]
As a workaround until 3.0.1 you can compose Hamcrest matchers instead:

```java
when().get("/x").
then().body("z.w.x", allOf(greaterThan(1), equalTo(5), lessThan(3)));
```

Also note that this was only and issue if you specified three or more multi-expectations with the key (x in this case).

**Comment by RocketRaccoon** [comment]
Ok, thanks
