### ISSUE TITLE
how to ignore missing response content-type header warnings

### ISSUE THREAD

**Issue by tique** [rest-assured/rest-assured#715]
Hi, 
I am testing a REST service that have responses that do not have a content-type header.

I get this warning: 

`com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder parseResponse
WARNING: Could not parse content-type: Response does not have a content-type header`

I am expecting to have no content-type in the header. 

Is there a way to ignore this warning?
I don't want it to pollute my results. 

i have tried: 

`.then()
            .contentType(isEmptyOrNullString())`

to no avail. 

Thanks

**Comment by johanhaleby** [comment]
This warning is a remnant from the HTTPBuilder fork many years ago and you're right that it shouldn't be there. I've now deployed a new snapshot that should address this issue. Please try version `3.0.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by tique** [comment]
thanks for that, 
excuse my ignorance but should i then change my rest-assured dependancies to version 3.0.1-SNAPSHOT?
for example: 
`
<dependency>
    <groupId>com.jayway.restassured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>3.0.1-SNAPSHOT</version>
</dependency>
`

after of course adding the repository as you mentioned. 

I get dependancy 3.0.1-SNAPSHOT not found. 

thanks again.

**Comment by johanhaleby** [comment]
Group id is now `io.rest-assured`, see [release notes](https://github.com/rest-assured/rest-assured/wiki/ReleaseNotes30#highlights)
