### ISSUE TITLE
dependancy 3.0.1-SNAPSHOT not found

### ISSUE THREAD

**Issue by tique** [rest-assured/rest-assured#716]
After adding the repository to the top of my maven pom file: 

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```
when i adjust the dependancy to use the version 3.0.1-SNAPSHOT: 

```xml
<dependency>
    <groupId>com.jayway.restassured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>3.0.1-SNAPSHOT</version>
</dependency>
```

I get dependancy 3.0.1-SNAPSHOT not found. 
`Failure to find com.jayway.restassured:rest-assured:3.0.1-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/snapshots/`
Any ideas as to why?

Sorry for creating another issue but noticed the one I originally created was closed and couldn't re-open. 
I can close this and add the comment to the original issue if that is better.

thanks.

**Comment by johanhaleby** [comment]
See https://github.com/rest-assured/rest-assured/wiki/ReleaseNotes30#highlights

**Comment by tique** [comment]
is this snapshot still available?
