### ISSUE TITLE
Cannot invoke method select() on null object error

### ISSUE THREAD

**Issue by akeluskar** [rest-assured/rest-assured#725]
I have tried versions 2.8 and 2.9 and keep running into the same issue.  Some of the Junit 12 parameterized test classes fail with the below error when running on teamcity build server.  I was also able to replicate this when running locally using command line.  Project is maven based and using surefire plugin version 19.1.  Here is the error:

java.lang.NullPointerException: Cannot invoke method select() on null object
    at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at com.jayway.restassured.internal.proxy.RestAssuredProxySelector.select(RestAssuredProxySelector.groovy:38)
....  (there are more lines of code so do let me know if you require them)
Sample code below where I had to omit some stuff.   I have confirmed the getUserId() and url are correct as I get values when printing.  First suite of the tests work fine but later in the build process, tests error out with the above message.  There is no proxy setup and the url has SSL.  Please let me know if you need anymore information.  I have tried using RestAssured.baseURI to set url as well as specification which had no effect.

private static RequestSpecification spec;
String url = "https://....";
public void restAssuredSetup(){
spec = new RequestSpecBuilder().setBaseUri(url + "/api").build();
RestAssured.useRelaxedHTTPSValidation();
}
public void resetAllStandards() {
RestAssured.given().spec(spec).delete("/MasteryTestingApi/" + getUserId());
}

@Before
public void setup(){
resetAllStandards();
......
..
}

**Comment by johanhaleby** [comment]
I would suspect that you're using an incompatible version of Groovy. Are you using maven or gradle or any other build tool?

**Comment by akeluskar** [comment]
I am using maven.  Maven surefire plugin 2.19.1 (I tested version 2.14/2.15 and ran into same above error).  Is there a version of groovy that I can explicitly specify in the pom file that might work?

**Comment by johanhaleby** [comment]
See [FAQ](https://github.com/rest-assured/rest-assured/wiki/FAQ) 1. You might also have something else in your classpath that transitively depend on another version of Groovy?

**Comment by akeluskar** [comment]
It was indeed soapui maven plugin which has a version of groovy which conflicted.  The above mentioned solution did not work, I just configured the soapui tests to run at the very end and that seems to take care of this.  Thanks for your help, going to close this issue.

**Comment by MaxMaeder** [comment]
@johanhaleby How would one fix this error in 2020? The FAQs want you to import `groovy-all`, but the library depends on `groovy`.

Whenever I try the FAQ fix but importing `groovy` instead of `groovy-all` I get:
```shell
[00:24:47] Caused by: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
```
