### ISSUE TITLE
config.getDecoderConfig().defaultContentCharset("UTF-8") is not respected for JSON parser

### ISSUE THREAD

**Issue by rophy** [rest-assured/rest-assured#728]
Version: 3.0.0

I have configured the following:

```
		RestAssuredConfig config = RestAssuredConfig.newConfig();
		config = config.encoderConfig(config.getEncoderConfig().defaultContentCharset("UTF-8").defaultCharsetForContentType("UTF-8", "application/json"));
		config = config.decoderConfig(config.getDecoderConfig().defaultContentCharset("UTF-8").defaultCharsetForContentType("UTF-8", "application/json"));
		RestAssured.config = config;
```

When response body contains Unicode chars in UTF-8, and content-type is `application/json` (without explicit charset), rest-assured throws exception:

```
groovy.json.JsonException: Lexing failed on line: 1, column: 183, while reading 'i', no possible valid JSON value or punctuation could be recognized.
```

Trying to step into debugger, I noticed that at io.restassured.internal.ResponseParserRegistrar.getParser(String):

```
      switch (parser) {
        case JSON:
          def slurper = new ConfigurableJsonSlurper(config.getJsonConfig().numberReturnType())
          if (parseAsString) {
            content = slurper.parseText(response.asString(true))
          } else {


```
you can see that it's calling response.asString(platformDefaultCharsetIfCharsetIsNotSpecified=true), which ignores decoderConfig.

Expected behavior:  decoderConfig should be respected in all cases.

Workaround:  add jvm arg `-Dfile.encoding=UTF-8` to force platformDefaultCharset to UTF-8.

**Comment by johanhaleby** [comment]
I think this is wrong:

>  RestAssuredConfig config = RestAssuredConfig.newConfig();
        config = config.encoderConfig(config.getEncoderConfig().defaultContentCharset("UTF-8").defaultCharsetForContentType("UTF-8", "application/json"));
>      config = config.decoderConfig(config.getDecoderConfig().defaultContentCharset("UTF-8").defaultCharsetForContentType("UTF-8", "application/json"));
        RestAssured.config = config;

Since the config is immutable. You should probably do something like:

```java
RestAssuredConfig config = RestAssuredConfig.config().encoderConfig(encoderConfig().defaultContentCharset("UTF-8").defaultCharsetForContentType("UTF-8", "application/json")).decoderConfig(decoderConfig().defaultContentCharset("UTF-8").defaultCharsetForContentType("UTF-8", "application/json"));
```

but it looks like you're right about `io.restassured.internal.ResponseParserRegistrar. getParser(..)`. I've now deployed a new snapshot that should address this issue. Please try version `3.0.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by rophy** [comment]
3.0.1-SNAPSHOT worked perfectly, thanks!

**Comment by johanhaleby** [comment]
Thanks for trying it out
