### ISSUE TITLE
header in requestspecification class is adding charset=UTF-8

### ISSUE THREAD

**Issue by bubun1985** [rest-assured/rest-assured#729]
Hi , 

We are planning to implement rest assure but while passing the header the content type "Accept","application/Json" is appending charset=UTF-8 . 
Please suggest to resolve the issue.

Sample code used :+1: 
RestAssured.given().request().and().header("Accept, "application/Json")

**Comment by johanhaleby** [comment]
See [docs](https://github.com/rest-assured/rest-assured/wiki/Usage#avoid-adding-the-charset-to-content-type-header-automatically)

**Comment by fendoujie** [comment]
Hi Johan,

    The code on your docs "		EncoderConfig.encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false);
"
    Does not work, I tried it, but I still get "Content-Type=application/json; charset=UTF-8"
   Can you help to look at this?
