### ISSUE TITLE
Multiple RestAssured.config

### ISSUE THREAD

**Issue by Anishohri** [rest-assured/rest-assured#731]
Hi,

I am running a test and want to set multiple configs in the Test but when i use them like
RestAssured.config = (com.jayway.restassured.RestAssured.config().encoderConfig(com.jayway.restassured.config.EncoderConfig.encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false)));
	    RestAssured.config = (com.jayway.restassured.RestAssured.config().encoderConfig(com.jayway.restassured.config.EncoderConfig.encoderConfig().encodeContentTypeAs("application/zip", ContentType.TEXT)));

The one that executes in the last overrides the first, Please let me know if there is any way to use multiple Configs

My Test is

Response upload = RestAssured.given().log().all().body("{\"file\":\n\"Users/Downloads/Testing_file_automation.zip\"\n}").contentType("application/zip").header(uploadheader2).urlEncodingEnabled(false).when().put(AWSsignedURL);

**Comment by johanhaleby** [comment]
The configuration is immutable so you have to do something like this:

```java
RestAssured.config = RestAssured.config().encoderConfig(encoderConfig().appendDefaultContentCharsetToContentTypeIfUndefined(false)).encodeContentTypeAs("application/zip", ContentType.TEXT)));)
```

Also please use the mailing list when asking questions in the future.

**Comment by karthiksml** [comment]
Hi,

I am using the rest assured along with TestNG. I set the log config in beforeclass and running multiple classes in parallel. I don't see the logs are written to its respective classses instead data's are collapsed. can someone explain how to achieve it
