### ISSUE TITLE
Getting exception when cookie max age is -1

### ISSUE THREAD

**Issue by dhirenmudgil** [rest-assured/rest-assured#732]
Hi,

I have a following request to my server and it returns a set cookie parameter where some cookie value is less than -1.

HttpOnlyuser_id=0; expires=Mon, 01-Aug-2016 14:43:47 GMT; Max-Age=-3600; 

In this case i am getting an error. What exactly this means do i have a problem at my server end. I am new to rest-assured. Please help.

**Comment by dhirenmudgil** [comment]
@johanhaleby Please help! is there any way i can override this. I do not want rest assured to check for max-age for one of my request, can i do it with a workaround.

**Comment by johanhaleby** [comment]
What version of rest assured are you using? This should work in 3.0.0.

**Comment by dhirenmudgil** [comment]
@johanhaleby i am using 3.0.0.

 In 3.0.0 also
 public Builder setMaxAge(int maxAge) {
            if(maxAge < -1) {
                throw new IllegalArgumentException("Max-Age cannot be less than -1");
            }
            this.maxAge = maxAge;
            return this;
        }

As you can see my cookie value is -3600, in that case also the condition is true and i am getting this exception. Is there a way i can override this check and proceed it with response.

**Comment by johanhaleby** [comment]
Hmm unfortunately I don't think there's a way to avoid this in the current version :( I've now deployed a new snapshot that should address this issue. Please try version `3.0.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```
