### ISSUE TITLE
Example to set proxy host , proxy port with proxy Auth (user & pwd) ?

### ISSUE THREAD

**Issue by lovetemple** [rest-assured/rest-assured#734]
This is an Info request to help how to specify proxy host , proxy port with proxyUser & proxyPassword.

Trying with below doesn't work and may be some one can help to provide the syntax for setting all 4 parameters please?

****\* below is not working from a coporate proxy and requests auth info.
  System.setProperty("http.proxyHost", "proxy.xyz.com.au");
            System.setProperty("http.proxyPort", "80");
            System.setProperty("http.proxyUser", "Test@xyz.com.au");
            System.setProperty("http.proxyPassword", "Password");
            System.getProperties().put("https.proxySet", "true");

**Comment by johanhaleby** [comment]
What about [proxy configuration](https://github.com/rest-assured/rest-assured/wiki/Usage#proxy-configuration) in the docs?

**Comment by timrsfo** [comment]
you may want to try this:
`RestAssured.proxy = host("127.0.0.1").withPort(8888);`
I use it for running thru fiddler.

**Comment by johanhaleby** [comment]
@timrsfo thanks for sharing your example

**Comment by Saxsgunt** [comment]
RestAssured.proxy = host("127.0.0.1").withPort(8888);
will work but if your organization use specific proxy such as "xxxorgcproxy.yy.org.com" and port xxxx. You will need to replace the "127.0.0.1" with "xxxorgcproxy.yy.org.com"
RestAssured.proxy = host("1xxxorgcproxy.yy.org.com").withPort(xxxx);
