### ISSUE TITLE
PathParamITest JsonPath.from(response) change to from(response)

### ISSUE THREAD

**Issue by vikramvi** [rest-assured/rest-assured#742]
Please change all instances of      JsonPath.from(response)     - >    from(response)

Thanks,
Vikram

**Comment by johanhaleby** [comment]
What do you mean!?! Where should this be changed?

**Comment by vikramvi** [comment]
PathParamITest.java 

public void supportsPassingPathParamsToGet()

public void supportsPassingPathParamsAsMapToGet()

These 2 test cases needs to be updated.

**Comment by johanhaleby** [comment]
Why do you think this must change? These are internal tests.

**Comment by vikramvi** [comment]
instead of className.methodName , why can't we just call methodName ? As this is static method anyways ? Please clarify

**Comment by johanhaleby** [comment]
Well you're welcome to do that. Why does it matter to you that some internal tests in REST Assured doesn't use static imports?
