### ISSUE TITLE
is 3.0.1-SNAPSHOT still available?

### ISSUE THREAD

**Issue by tique** [rest-assured/rest-assured#743]
is 3.0.1-SNAPSHOT still available?
as per: 
https://github.com/rest-assured/rest-assured/issues/715
https://github.com/rest-assured/rest-assured/issues/716

I see there is no rest-assured directory in: 
https://oss.sonatype.org/content/repositories/snapshots/io/rest-assured/

Is there a maven dependancy for version 3?
https://mvnrepository.com/artifact/com.jayway.restassured/rest-assured

As I'd like to ignore missing response content-type header warnings. 

Thanks

**Comment by johanhaleby** [comment]
Hi, 

REST Assured 3.0.1 is released so you should just use that. I'm not exactly sure where the SNAPSHOT version ends up but it feels strange that it's not available at the URI you're pointing to. I'll have to keep an eye out next time I deploy a snapshot.
