### ISSUE TITLE
Post request failing for JSON created from a HashMap

### ISSUE THREAD

**Issue by vikramvi** [rest-assured/rest-assured#744]
server is throwing 400 for blow 
          given().
            		     header("Accept", "application/json; version=1.0").
            		     header("Authorization", "JWT "+ token ). 
            		     contentType(ContentType.JSON).
            		     body(new HashMap<String,Object>() {{
            	             put("organization", "test");
            	             put("severity", "high");
	                     put("context", new HashMap<String,String>() {{
            	                 put("description", "test_desc");
            	             }});
            	             
            	        }}).
             when().

but passing for below

Map<String, Object>  jsonAsMap = new HashMap<>();
	    jsonAsMap.put("test");
            jsonAsMap.put("severity", "high");
	    jsonAsMap.put("context", new HashMap<String,String>() {{  
	                        put("description", "test_desc");
	                        }});

given().
            		header("Accept", "application/json; version=1.0").
            		header("Authorization", "JWT "+ token ). 
            		contentType(ContentType.JSON).
            		body(jsonAsMap).
when().

Please review if this is a bug ?

**Comment by johanhaleby** [comment]
You have different contents in your hashmap so I doubt that this is a REST Assured issue.

**Comment by vikramvi** [comment]
oops sorry it was my mistake while describing bug; but the content was same in both places.
