### ISSUE TITLE
Unable to do relative xpath extract

### ISSUE THREAD

**Issue by spartanglady** [rest-assured/rest-assured#764]
Hey.. I have a scenario where i get the xml response and i want to extract the value of a specific tag but the tag's path will vary everytime. So i wanted to use relative xpath but it is not working.

String x = given().request().contentType("application/xml").body(bdy).when().post("sdf").then().extract().path(".//xyz")

But this is actually returning me all the values of the header tags.

**Comment by johanhaleby** [comment]
"path" doesn't support xpath. Rest Assured doesn't have a way to extract xpath, only validate xpath. You'd have to return the body as for example a string and then apply xpath to that string.
