### ISSUE TITLE
xml path not working .

### ISSUE THREAD

**Issue by johnmorrisQADeveloper** [rest-assured/rest-assured#765]
When I send a request

```java
 Response resp = given()
                            .contentType(ContentType.XML)
                            .body("
<oxip version="6.0">
    <request>
        <reqClientAuth>
            <user>admini</user>
            <password>admini</password>
        </reqClientAuth>
        <reqAccountAdd>
            <dob>1924-12-16</dob>
            <addrStreet1>UZtNXgoW</addrStreet1>
            <addrCity>lCNDrqBm</addrCity>
            <addrPostcode>yWcQuXJb</addrPostcode>
            <email>vLCJmUcL@iwcRvLkd.com</email>
            <telephone>0764497156</telephone>
            <contactable>N</contactable>
            <partnerContactable>N</partnerContactable>
            <ipAddress>14.11.17.33</ipAddress>
            <channel>I</channel>
            <affId/>
            <regCombi>P</regCombi>
        </reqAccountAdd>
    </request>
</oxip>").when()
                            .post(endPoint);

              System.out.println("res " +  resp.asString()); // this prints the below xml response
```

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE oxip SYSTEM "oxip.dtd">
<oxip version="6.0">
    <response requestTime="0.1151">
        <returnStatus>
            <code>001</code>
            <message>success</message>
            <debug>11/07-08:41:50 </debug>
        </returnStatus>
        <respAccountAdd>
            <userName>fdgdf</userName>
            <accountNo>dfg5erd</accountNo>
            <custId>456</custId>
            <status>PENDING</status>
            <token>ewtX/dfgujsfdfdhtaxcrtgxxxxx==</token>
        </respAccountAdd>
    </response>
</oxip>
```

Issue: 
 String token = with(resp.asString()).get("oxip.response.respAccountAdd.token");
        System.out.println("token " +  token);

[Fatal Error] :2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

com.jayway.restassured.path.xml.exception.XmlPathException: Failed to parse the XML document

**Comment by johanhaleby** [comment]
Please try version 3.0.1

**Comment by johnmorrisQADeveloper** [comment]
I tried with all different versions <artifactId>xml-path</artifactId> <version>2.9.0</version> 
and <artifactId>rest-assured</artifactId> <version>2.9.0</version> , also including 2.4.0.. No luck. Any idea?

**Comment by johanhaleby** [comment]
Configure XmlPath to `disableLoadingOfExternalDtd()`

Standalone:
```java
XmlPath xmlPath = new XmlPath(xml).using(new XmlPathConfig().disableLoadingOfExternalDtd());
```

REST Assured DSL:

```java
given().config(RestAssuredConfig.config().xmlConfig(XmlConfig.xmlConfig().disableLoadingOfExternalDtd())). ...
```

**Comment by johnmorrisQADeveloper** [comment]
cheers. it's working when disabling disableLoadingOfExternalDtd().

**Comment by emilshina** [comment]
Hi @johanhaleby!

I have the same issue. My code is: 

```
String response = given().
      config(RestAssuredConfig.config().xmlConfig(XmlConfig.xmlConfig().disableLoadingOfExternalDtd())).
                get(request).andReturn().body().asString();
String title = from(response).getString("html.head.title");
```

And I get the error:

```
[Fatal Error] :5:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

io.restassured.path.xml.exception.XmlPathException: Failed to parse the XML document
```

Could you help me with it, please?

**Comment by johanhaleby** [comment]
@emilshina If `from` is from XmlPath you need to configure the XmlConfig for the XmlPath and not for REST Assured. Something like: 

```java
XmlPath.using(XmlConfig.xmlConfig().disableLoadingOfExternalDtd())). ..
```

**Comment by emilshina** [comment]
Thanks for your answer, helped me.

**Comment by johannesn** [comment]
I had to add allowDocTypeDeclaration(true) as well to make it work. Using version 3.2.0 of rest-assured.

**Comment by alaamhmd** [comment]
If any one still facing this error and above solutions didn't solve it,
I manage to solve it by Upgrade  java JDK to corretto amazon java 11

**Comment by repon06** [comment]
`        XmlPath xmlPath = new XmlPath("<bookstore><book category=\"cooking\"><title lang=\"en\">The</title></book></bookstore>")
                .using(new XmlPathConfig().disableLoadingOfExternalDtd());
        var str = xmlPath.getString("bookstore.book.title");`

fail: 

> io.restassured.path.xml.exception.XmlPathException: Failed to parse the XML document
	at io.restassured.path.xml.XmlPath$LazyXmlParser.invoke(XmlPath.java:1039)

**Comment by repon06** [comment]
`XmlPath xmlPath = new XmlPath("<bookstore><book><title lang=\"en\">The</title></book></bookstore>")`
wtihout category=\"cooking\" - its worked (((
