### ISSUE TITLE
What happened to Rest Assured's requestContentType default value

### ISSUE THREAD

**Issue by restagner** [rest-assured/rest-assured#767]
I'm using Rest Assured v3.0.1.  In the documentation (https://github.com/rest-assured/rest-assured/wiki/Usage#default-values), it lists `requestContentType` as a possible default value.  I don't see this available from within the RestAssured class as noted in docs.

**Comment by johanhaleby** [comment]
It's been removed in version 3.0.0 (see [changelog](https://github.com/rest-assured/rest-assured/blob/master/changelog.txt)). As mentioned there as well you should now use a `io.restassured.builder.RequestSpecBuilder`, set the content-type and apply it to `io.restassured.RestAssured.requestSpecification`. Please help out and provide a pull request with updated javadoc.

**Comment by restagner** [comment]
@johanhaleby thanks for the clarification.  You refer to providing a pull request and updating the javadoc.  I had a look into the `io.restassured.builder.RequestSpecBuilder` class and the javadoc associated with the `setContentType()` method looks complete.

Did you mean to help out with a pull request that updates the wiki documentation at https://github.com/rest-assured/rest-assured/wiki/Usage#default-values ?

**Comment by johanhaleby** [comment]
Oh sorry I thought you meant on the javadoc. I'll fix it, thanks!
