### ISSUE TITLE
Best practices and fluent builders

### ISSUE THREAD

**Issue by kobbikobb** [rest-assured/rest-assured#768]
I would appreciate some guidance as you must have written a lot of Rest Api acceptance or end-to-end tests.

1. Would you reference production code to re-use beans defined there how would you create the json required to post to an endpoint?

2. I am doing experiments on a fluent builder for my tests. Have you done something similar and how would you implement it?
 
Example 1 using a fluent builder:
```
given().
       body(someMessage().withText("SomeText").asJson())
when().
      post("/message");
```
Example 2 using a bean with a fluent interface:
```
given().
       body(someMessage().withText("SomeText"))
when().
      post("/message");
```
3. Could you point to me to any public/open source projects using rest-assured?

Some of this could be in the documentation but maybe you think it is out of scope.

**Comment by johanhaleby** [comment]
Please use the mailing list when asking questions in the future.

1. No I would try to avoid that. Many times I've seen issues where people are just using the same DTO's in their tests as in their production code which has lead to a sense of false security. I've seen on multiple occasions that this has lead to bugs in production.
1. That's one way to go, but I usually just create a [HashMap](https://github.com/rest-assured/rest-assured/wiki/Usage#create-json-from-a-hashmap).
1. Unfortunately I can't point you to any open source projects but I suppose you should be able to google for it or search for it on github.

**Comment by kobbikobb** [comment]
@johanhaleby Think you for you advice, it's real helpful.
