### ISSUE TITLE
No Custom Error Messaging capabilities

### ISSUE THREAD

**Issue by JasonSmiley208** [rest-assured/rest-assured#770]
I could be wrong (couldn't find an example or figure it out from the code), but, it seems there is no way to add custom error messaging on the validation side of things.

For example, if I cannot say:
```
given()
.get("some url")
.then()
.body("Response came back null",  //want custom error message
 "response", notNullValue());
```

It would be nice if we could mimic the JUnit functionality for Assertions.

**Comment by johanhaleby** [comment]
There's currently no such option. I'm going to close this because it has been discussed in another issue (unfortunately I wasn't able to find it quickly but you should be able to find it if you browse through the issues).

**Comment by JasonSmiley208** [comment]
Well, glad the other one is open :)

Just gave a quick scan, but glad its being discussed. Thanks
