### ISSUE TITLE
How to pass the ID in the URL

### ISSUE THREAD

**Issue by garimacha** [rest-assured/rest-assured#772]
Hi,

I am retiveing the ID from the property file that is to be supplied with the URL while making the call. This is the code -

`RestAssured.baseURI=properties.getProperty("baseurl");
        RestAssured.oauth2(properties.getProperty("appId"));`

The second line is not correct. What else can I use so that the URL and ID are passed when the final call is made?

**Comment by johanhaleby** [comment]
What do you mean by final call? What is it that is not correct?! (sure the syntax is not correct but I don't suppose that's the question?)

Also please use the mailing list when asking questions in the future.

**Comment by garimacha** [comment]
what is the address of the mailing list?
