### ISSUE TITLE
Decoding cp850

### ISSUE THREAD

**Issue by jmNJ** [rest-assured/rest-assured#773]
Hi,
i have the following json response in cp850 charset when calling an api with curl (< HTTP/1.1 200 OK
< Content-Type: application/json; charset=cp850) :
"detailLabel":"CONSULTATION GéNéRALISTE"

When i call it with rest-assured with the following config :
config(RestAssured.config().decoderConfig(DecoderConfig.decoderConfig().defaultContentCharset("cp850")).sslConfig(SSLConfig.sslConfig().relaxedHTTPSValidation())).
i have got the following result with response.asString() :
"detailLabel":"CONSULTATION G├®N├®RALISTE"

I don't understand why rest-assured can't decode it like curl.

Thanks for your help

JM

**Comment by johanhaleby** [comment]
RA tries to decode after what's stated in the content-type header so it should work unless you've overwritten something in the configuration. JSON should always be encoded as UTF-8 and this is the default setting in RA. You can override this by specifying the content type for application/json explicitly by using the `defaultCharsetForContentType` method in [DecoderConfig](https://github.com/rest-assured/rest-assured/wiki/Usage#decoder-config).
