### ISSUE TITLE
Unable to send "id_token token" as one word to request expecting an array

### ISSUE THREAD

**Issue by reddrums808** [rest-assured/rest-assured#787]
Using latest (3.0.1) RestAssured, if I make a POST call using the method formParams and one of my request parameters is response_types (which allows multiple values) my value of id_token token gets send as two separate values in an array.

Here is what I'm sending, some of it might be generic values:

	private static final String REDIRECT_URIS_KEY = "redirect_uris";
	private static final String CLIENT_NAME_KEY = "client_name";
	private static final String RESPONSE_TYPE_KEY = "response_types";

	public static final String RESPONSE_TYPE_CODE = "code";
	public static final String RESPONSE_TYPE_ID_TOKEN = "id_token";
	public static final String RESPONSE_TYPE_ID_TOKEN_TOKEN = "id_token token";

	Map<String, Object> requestParameters = new HashMap<>();
		requestParameters.put(REDIRECT_URIS_KEY, redirectUri);
		requestParameters.put(CLIENT_NAME_KEY, testName);
		requestParameters.put(RESPONSE_TYPE_KEY,
				Arrays.asList(RESPONSE_TYPE_ID_TOKEN_TOKEN));

Response response = RestAssured.given().formParams(requestParameters)
				.and().contentType("application/json").when()
				.post(MessageFormat.format(registrationUrl, testName)).peek();

This is what the server receives when I send a POST request using RestAssured.
response_types": [ "[\"id_token", "token\"]" ] } when I intended it to be id_token token

**Comment by johanhaleby** [comment]
Yes this is a known issue, see [here](https://github.com/rest-assured/rest-assured/issues/238). Work around is to not use a hashmap but rather specify each form parameter like this:

```java
given().formParam(REDIRECT_URIS_KEY, redirectUri).formParam(CLIENT_NAME_KEY, testName).. ..
```

**Comment by reddrums808** [comment]
This still doesn't work when one of my parameters is multi-word, in my case "id_token token" it still sends it as two items "id_token", "token"

**Comment by johanhaleby** [comment]
Hmm, are you saying that "id_token token" isn't URL encoded properly in the request?

**Comment by reddrums808** [comment]
The request ends up being:
1484845929.729 Init ===========================================
1484845929.729 HTTP request {
   "endpoint": "registration",
   "method": "POST"
}
1484845929.729 Request {
   "name": "ClientRegistration"
}
1484845929.729 Request args redirect_uris=https%3A%2F%2Flocalhost%3A9031%2Fsp%2FeyJpc3MiOiJodHRwczpcL1wvcnAuY2VydGlmaWNhdGlvbi5vcGVuaWQubmV0OjgwODBcL3BpbmdmZWRlcmF0ZS5pZF90b2tlbi10b2tlblwvcnAtcmVzcG9uc2VfdHlwZS1pZF90b2tlbit0b2tlbiJ9%2Fcb.openid&client_name=rp-response_type-id_token%2Btoken_709490&response_types=id_token%20token
1484845929.73 RegistrationRequest {
   "application_type": "web",
   "client_name": "rp-response_type-id_token+token_709490",
   "redirect_uris": [
       "https://localhost:9031/sp/eyJpc3MiOiJodHRwczpcL1wvcnAuY2VydGlmaWNhdGlvbi5vcGVuaWQubmV0OjgwODBcL3BpbmdmZWRlcmF0ZS5pZF90b2tlbi10b2tlblwvcnAtcmVzcG9uc2VfdHlwZS1pZF90b2tlbit0b2tlbiJ9/cb.openid"
   ],
   "response_types": [
       "id_token",
       "token"
   ]
}


RestAssured separated my id_token token request parameter which was supposed to be one value into two when it sent the request.

**Comment by reddrums808** [comment]
I was able to get it to work when I used the hash map of parameters in the body but not in the formParams part of the rest assured call, thanks for looking into it.
