### ISSUE TITLE
Emphasize in the exception that 'Jackson (databind)' is required

### ISSUE THREAD

**Issue by vbachurin** [rest-assured/rest-assured#788]
Hi,

I was about to submit an issue saying that Jackson doesn't work with RestAssured. But figured out the cause by double-checking the documentation. :)

Before including any JSON serializer into the class path I had seen the exception:

> java.lang.IllegalStateException: Cannot serialize object because no JSON serializer found in classpath. Please put either Jackson or Gson in the classpath.

Then googled by 'Jackson', found and added dependency to 'jackson-core'

        dependencies {  
          testCompile 'io.rest-assured:rest-assured:3.0.1'  
          testCompile 'com.fasterxml.jackson.core:jackson-core:2.8.6'  
        }  
  
which apparently wouldn't work. To make it work the dependency should have been
> 'com.fasterxml.jackson.core:jackson-databind:2.8.6'   

I suppose it may save few people some time if the exception text says that RestAssured requires exactly 'Jackson (databind)', not anything else.  
This is mentioned in the documentation, but not in the exception.

Thanks in advance!

**Comment by johanhaleby** [comment]
Thanks for the advise, I've fixed this in master now. The message now reads:

> Cannot serialize object because no JSON serializer found in classpath. Please put either Jackson (Databind) or Gson in the classpath.

**Comment by GhabriA** [comment]
Hello, I'm having the same exception :Cannot deserialize object because no JSON deserializer found in classpath. Please put either Jackson (Databind) or Gson in the classpath.

How how to add JSON deserializer in classpath ?
And according to your answer : You added dependency to 'jackson-core', how can I find this file?

Thank you in advance .

**Comment by RodolfoDodo** [comment]
@vpedash 
thank you helped a lot

**Comment by 856shailesh** [comment]
Thanks for this , instead of Jackson Databind I added Jackson core and was getting the error . this was the first result on the search , thank to you and google search indexing :)

**Comment by Alexander-Averko** [comment]
@vpedash
Thanks! I love you!!

**Comment by andres4715-gif** [comment]
Thanks, it works

**Comment by PrasanaJP** [comment]
> @GhabriA You need a `jackson-databind` dependency. Here is the link to the latest version: https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.9.5 There choose the build tool you use in your project (Maven, Gradle, etc.) and copy it to your build file.

Thank you so much.. you just saved my day.

**Comment by RemTech** [comment]
**Thanks for the clear info.** 
```
You need a jackson-databind dependency. Here is the link to the latest version:
https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.9.5
There choose the build tool you use in your project (Maven, Gradle, etc.) and copy it to your build file.
```

**Comment by fercassia** [comment]
@vpedash
thank you helped a lot
