### ISSUE TITLE
response cookies are not copied

### ISSUE THREAD

**Issue by andihit** [rest-assured/rest-assured#791]
I cannot access the cookies from the response:
```
Map<String,String> cookies = given()
                .when()
                .get("/?lang=de")
                .then()
                .statusCode(HttpStatus.OK.value())
                .extract().cookies();
```

The `cookies` map is always empty.

I traced the bug to the file https://github.com/rest-assured/rest-assured/blob/6b5fea6a281fd45e2bf19121a726c8ea1ec7b7a0/modules/spring-mock-mvc/src/main/java/io/restassured/module/mockmvc/internal/MockMvcRequestSenderImpl.java#L182 - it seems that the cookies from the `MockHttpServletResponse` object aren't copied into the `MockMvcRestAssuredResponseImpl` object.

**Comment by johanhaleby** [comment]
Looks like a bug indeed. Care to provide a pull request and test?

**Comment by GangadharanS** [comment]
@johanhaleby 
I am facing the same issue now with "io.rest-assured:rest-assured:3.2.0" version. Is this issue fixed?
