### ISSUE TITLE
pass apikey in header for restassured test is not working

### ISSUE THREAD

**Issue by seema-realforce** [rest-assured/rest-assured#792]
I am trying to pass api key in restassured. From postman, i got the repsonse data using 'X-Api-Key' with value. But with rest assured, i am seeing null pointer exception

Response res = given()      
        .header("key","55af7bc105c9c2ee98e2abb32979fee")
        .when()
    .get ("https://mbaseurl/api/v1/search-listings/").then().
    extract().response();

I tried passing key value with .header("X-Api-Key", "value") but was not successful

**Comment by johanhaleby** [comment]
What exception to you see?

**Comment by seema-realforce** [comment]
testStatusCode:56 NullPointer

**Comment by seema-realforce** [comment]
What is the key name for passing apikey in restassured?

**Comment by johanhaleby** [comment]
Could you please provide the full stacktrace?

> What is the key name for passing apikey in restassured?

Your question doesn't make sense this is specific to your service (or an authentication scheme that it uses). It's the same thing as asking "what's the way to get an entity out of a database". There's no one way, it depends on which database you're using.

**Comment by seema-realforce** [comment]
The key name i am using in Postman to get the response is 'X-Api-Key' and value of API key. This fetches Json body along with url. Similarly whats the key name i need to use in header declaration of restassured
.header("???","xyz")
I hope the question is clear now

**Comment by johanhaleby** [comment]
You should use the same header as in postman. But if it's not working with rest assured I suspect that postman sends additional data to the server. Use wireshark to see the differences.

**Comment by seema-realforce** [comment]
Is there a way i can check from restassured to see what is being passed like a log data?
Also is my syntax correct by placing the api key in header?

 Response res = given()
.header("key","55af7bc105c9c2ee98e2abb32979fee")
.when()
.get ("https://mbaseurl/api/v1/search-listings/").then().
extract().response();

**Comment by johanhaleby** [comment]
https://github.com/rest-assured/rest-assured/wiki/Usage#logging

**Comment by seema-realforce** [comment]
Restassured Request data:
Request method:	GET
Request path:	https://myurl/api/v1/search-listings
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:		<none>
Headers:		X-Api-Key=xyzee
				Accept=*/*
Cookies:		<none>
Body:			<none>

Jmeter Request data(fetched the response):

GET https://myurl/api/v1/search-listings/
GET data:
[no cookies]
Request Headers:
Connection: keep-alive
X-Api-Key: xyzee
Content-Length: 0
Content-Type: text/plain; charset=ISO-8859-1
Host: listings-xyz.ch
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_111)

**Comment by johanhaleby** [comment]
You see that there's a difference right? (path, content-length and content-type for example). Try to mimic the jmeter request in RA exactly.

**Comment by seema-realforce** [comment]
Now, the issue is resolved and i am getting the values of response.  Also please let me know how can i verify all the key names are present in the response. Like say i have response body
{
  "count": "15",
  "page": 1,
  "per_page": 100,
  "data": [
    {
      "id": "2b81c208a35ce",
      "reference": "sergerg123",
      "bedrooms": null,
      "bathrooms": null,
      "habitable": "1'000",
      "weighted": "1'000",
      "land": null,
      "description": {
        "en": {
          "title": "",
          "description": "",
          "summary_title": "",
          "summary_description": "",
          "seo_title": "",
          "seo_keywords": "",
          "seo_description": ""
        }
      },
      "photo": "",
      "main_category": "Flat",
      "sub_category": "Flat",
},

Now i need to verify say data[0] and fetch all the values of first data in array. How can i use restassured to fetch them?

**Comment by johanhaleby** [comment]
Use json schema validation and read the documentation. And please use the mailing list for asking questions in the future.

**Comment by sanjay058** [comment]
Hi seema-realforce , could you please help how did it? I m also facing the same issue. Getting status code :401

**Comment by AjmalIdeas** [comment]
@sanjay058 Did you resolve this issue? I am getting same 401 now. Can you pls help me in this regard.

**Comment by AjmalIdeas** [comment]
@seema-realforce Can you pls help us to resolve this issue?
