### ISSUE TITLE
Introduce remove node method

### ISSUE THREAD

**Issue by suratdas** [rest-assured/rest-assured#793]
I want to do a PUT request. So, this is what I do in sequence.
1. First I do a GET request and store the body in a variable so that I know the state before I modify data.
2. Then do a PUT request (actual test)
3. Now, I want to undo my modification above with another PUT. This is to ensure we leave the data in same state. In most cases, I cannot use the GET variable I got (in step 1 above) for the PUT body without removing some node(s). Example: CreatedDate or other values which server will not allow to change etc.

The question is, is it possible to easily remove node/nodes in the response.body without having to do complex serialization or String manipulation ? If not, do you think it is useful to bring this feature into rest-assured ?

**Comment by johanhaleby** [comment]
I would say that this is outside of the scope of rest assured. You can use various JSON libraries (such as [Jayway's jsonpath](https://github.com/jayway/JsonPath)) to change the JSON structure if you like..

Usually I'd just wrap the call in a transaction that is rolled back or simply drop the entire database between each test.
