### ISSUE TITLE
support for headers with signature Map<String, Object>

### ISSUE THREAD

**Issue by braghome** [rest-assured/rest-assured#794]
Sometimes for automation at certain shops required headers with String and raw int values

`"somekey": "string value"`
 `"secondkey": 23112 `

can we add support for headers with Object value on the Map signature

**Comment by johanhaleby** [comment]
Hmm what do you mean? This should work:

```java
Map<String, Object> parameters = new HashMap<>();
parameters.put("name", "John");
parameters.put("age", 23);

given().params(parameters). ..
```

**Comment by braghome** [comment]
Really! So are we overloading the params for headers also, 😞 this is confusing

**Comment by johanhaleby** [comment]
Sorry @braghome I don't understand what you mean. What is confusing, could you give me a full example?

**Comment by braghome** [comment]
I am talking about the headers in Rest calls seems like  `Map<String, Object>` signature is working fine for me
