### ISSUE TITLE
Can't overwrite the query param values

### ISSUE THREAD

**Issue by JasonSmiley208** [rest-assured/rest-assured#802]
I noticed that if I want to re-use a built Request, it will no overwrite a previously defined Query Param

For example:

RequestSpecification requestBuilder = given();
 requestBuilder.param("json", "{}");
 requestBuilder.param("json", "{newValue:true}");

requestBuilder.get();

When I check to see the query params for this request, I see both are actually being added to the request.

Looks like a bug? Or maybe, this is working as intended?

**Comment by johanhaleby** [comment]
See [ParamConfig](https://github.com/rest-assured/rest-assured/wiki/Usage#param-config), it allows you to control how parameters are updated.
