### ISSUE TITLE
How to add Array of String as parameter in Post Request with multipart?

### ISSUE THREAD

**Issue by bilalsha** [rest-assured/rest-assured#803]
I am trying to add array of string as parameter in Post Request with multipart. But I got this exception

`java.lang.IllegalArgumentException: Cannot serialize because cannot determine how to serialize content-type multipart/form-data`

my request:
```java
Response response = given()
                .parameter(REQUEST_PARAM_DATA_SET_ID, new String[]{"-1", "-2", "-3"})
                .multiPart(dataFile)
                .expect()
                .when()
                .post(restApi);```

**Comment by johanhaleby** [comment]
Hmm, what are you trying to do? Is this the goal?

```
REQUEST_PARAM_DATA_SET_ID=-1&REQUEST_PARAM_DATA_SET_ID=-2&REQUEST_PARAM_DATA_SET_ID=-3
```

Is REQUEST_PARAM_DATA_SET_ID supposed to be a multipart parameter as well?

**Comment by bilalsha** [comment]
@johanhaleby.. multiple dataset with multiple files. A file can be in multiple dataset.

* dataset 1
  * file 1 & file 2
* dataset 2
  * file 2 & file 3
* dataset 3 
  * file 4

Yes it should be multipart parameter as well

**Comment by johanhaleby** [comment]
Then, if I understand correctly, you should pass in multiple multi-parts (use multiPart once for each dataset). Not sure what you're trying to achieve with the "parameter".
