### ISSUE TITLE
Error in Eclipse when imported rest-assured-itest-java project

### ISSUE THREAD

**Issue by vikramvi** [rest-assured/rest-assured#806]
After importing rest-assured-itest-java project, getting below error in pom.xml

Missing artifact io.rest-assured.examples:scalatra-webapp:war:3.0.3-SNAPSHOT

Missing artifact io.rest-assured.examples:scalatra-example:jar:3.0.3-SNAPSHOT

Missing artifact io.rest-assured:rest-assured:jar:3.0.3-SNAPSHOT

Tried Maven force update but didn't help either. I'm using Eclipse Neon

Please have a look

**Comment by johanhaleby** [comment]
Why would you import that project?

**Comment by vikramvi** [comment]
For referring & understanding examples in sample project. Please let me know if I'm doing something wrong here

**Comment by johanhaleby** [comment]
Oh, in that case I think the easiest way is to just clone this repository.

**Comment by vikramvi** [comment]
Yes I have cloned it and imported locally, earlier version was working fine but latest one is showing errors. can you please clarify what may be going wrong ?

**Comment by johanhaleby** [comment]
I'm not using Eclipse so I can't help you. When using Intellij you just double click on the pom.xml file.
