### ISSUE TITLE
Problem with § character in PreemptiveAuthSpec.basic()

### ISSUE THREAD

**Issue by gitfan13** [rest-assured/rest-assured#808]
Hello,

I'm calling `given().auth().preemptive().basic("abc", "123§")` and the resulting auth header is `Authorization=Basic YWJjOjEyM6c=`. However `YWJjOjEyM6c=` seems to be equivalent to `abc:123`.

Manual check using Java 1.7: `System.out.println(DatatypeConverter.printBase64Binary("abc:123§".getBytes()))` returns `YWJjOjEyM8Kn`.

The problem seems to be caused by the `§` character, and I guess there is a problem with the character encodings.

I'm using rest-assured, version 3.0.1.

Thanks a lot!

**Comment by johanhaleby** [comment]
Hi,

REST Assured is using charset ISO-8859-1 (which is in accordance with the http spec afaik) to generate the header. And base64 decoding of YWJjOjEyM6c= does indeed return `abc:123§` which is correct.

Regards
/Johan
