### ISSUE TITLE
setParam("CONNECTION_MANAGER_TIMEOUT", 4000) not working as expected

### ISSUE THREAD

**Issue by vikramvi** [rest-assured/rest-assured#809]
Hi,

I've below in BeforeClass junit method

`RestAssured.config = RestAssured.config().httpClient(HttpClientConfig.httpClientConfig().setParam("CONNECTION_MANAGER_TIMEOUT", 4000));`

After this I make multiple GET requests to REST end points.

Some end points are taking more than 10+ minutest to return back ( because of backend bug ) but even with above global time setting, test case doesn't exit after 4 sec.

Please clarify

**Comment by johanhaleby** [comment]
You have to look in the http client documentation in order how to do this. Either by setting parameters like you do or providing a custom instance of (Abstract)HttpClient using [this](https://github.com/rest-assured/rest-assured/wiki/Usage#http-client-config) approach. Also please use the mailing list when asking questions in the future.
