### ISSUE TITLE
there are some package errors in wiki

### ISSUE THREAD

**Issue by binarywang** [rest-assured/rest-assured#817]
https://github.com/rest-assured/rest-assured/wiki/Usage#adding-result-handlers
https://github.com/rest-assured/rest-assured/wiki/Usage#using-result-matchers
In these two sections,  
the package `org.springframework.test.web.server.result` is wrong,
should be `org.springframework.test.web.servlet.result`

**Comment by johanhaleby** [comment]
Thanks, I've fixed it now.
