### ISSUE TITLE
Update Scribe version on Usage Guide

### ISSUE THREAD

**Issue by brunodix** [rest-assured/rest-assured#821]
The scribe version indicated OAuth section of [Usage Guide](https://github.com/rest-assured/rest-assured/wiki/Usage#oauth-1)  is incorrect.
Version 3.0.2 uses scribe 2.5.3, not 1.3.7, also the package is incorrect.

Thanks for this great lib.

**Comment by johanhaleby** [comment]
Thanks  for pointing this out, I've corrected it now.
