### ISSUE TITLE
When setting proxy, it is also used for request against localhost

### ISSUE THREAD

**Issue by ybbus** [rest-assured/rest-assured#827]
Hi.
I need to set a proxy for testing external systems.
But I also test local system running on localhost:8080.

But this does not work when proxy is set. It seems that rest-assured tries to connect even to localhost via proxy. When I disable proxy I can reach localhost, but nocht an external system anymore.

**Comment by johanhaleby** [comment]
How do you define the proxy?

**Comment by ybbus** [comment]
RestAssured.proxy("proxy", 8080);

Do I have the ability to set nonproxy addresses?

**Comment by johanhaleby** [comment]
When you set a proxy like that it'll be used by all requests. If you don't want to use a proxy for all requests and don't define it statically but rather use a [request specification](https://github.com/rest-assured/rest-assured/wiki/Usage#specification-re-use) and apply that to the requests that need it.

**Comment by ybbus** [comment]
My problem is that I only know runtime of the tests if a request is done against local or remote.
Proxies usualy know, that localhost is never requested over a proxy.
This would have solved my problem.

Maybe it would be a good solution to provide a functionality to set nonProxy hosts.

Otherwise one have to do this programatically and check everytime if the request should be proxied or not. This is normally the responsibility of the proxy itself.

Anyway, thanks for your reply.

**Comment by johanhaleby** [comment]
> Proxies usualy know, that localhost is never requested over a proxy.

Do you really mean proxy here or do you mean the client calling the proxy (that would be rest assured in this case)?

**Comment by ybbus** [comment]
Sorry, I meant the client. When the proxy is contacted it is of course to late. :)

But nevermind, I will try to solve this in the client code by checking if request is directed to localhost, and then deactivate the proxy.

**Comment by johanhaleby** [comment]
Yeah I think that's a better approach since otherwise the complexity of RA would increase. For example you could implement a filter that checks if localhost is used and if so don't apply the proxy.

**Comment by ybbus** [comment]
Yes, and I think there is nothing wrong. I was sure that http client libraries know, that localhost requests are not routed to a proxy. I tested it with okhttp and it also forwarded my localhost request to the proxy.

So it does not seem to be the responsibility of the library to check what is a proxy request and what is not.

So everything ok here! :-)

**Comment by icarvalho-tmg** [comment]
I have the same issue. I use RA (as client) to connect with different service providers and just one of them needs a proxy. So, when connecting to the others, the proxy/proxyport configuration are replicated. No problem if I'm connecting to http services because I just set as proxy the same service address/port. But, when I need to connect to a HTTPS service, the things got weird as the proxy is always HTTP.
