### ISSUE TITLE
none of the "matchesJsonSchema" 's work. 

### ISSUE THREAD

**Issue by ferylukacs** [rest-assured/rest-assured#828]
i try typing every kind, and no import option appears.

**Comment by johanhaleby** [comment]
Could you please elaborate?

**Comment by ferylukacs** [comment]
this, does not work at all: https://github.com/rest-assured/rest-assured/wiki/GettingStarted#json-schema-validation

I put the Dependecnies, and try to write matchesJsonSchema..  but it's red, like it doesn't exist.

**Comment by ferylukacs** [comment]
oh, never mind. Just restarted my laptop and intelli-j and it seems to work. Thnaks and sorry

**Comment by johanhaleby** [comment]
Then you've not added the dependencies correctly, it works. As a matter of fact I'm using this feature as we speak.
