### ISSUE TITLE
Suggestion: offer a getBaseUri()

### ISSUE THREAD

**Issue by dialex** [rest-assured/rest-assured#829]
There's already a `setBaseUri` but once you set it there's no way to `getBaseUri`.
That would greatly improve debugging and logging, since at any time I could check where RestAssured is connecting to.

**Comment by johanhaleby** [comment]
The way to do this is from a Filter. From a filter you can get access (and change) to most things configured in the request specification.

**Comment by dialex** [comment]
@johanhaleby Can you give an example for future reference?

Let's say you created some api spec...

```java
public RequestSpecification getApiSpec() {
  RequestSpecBuilder reqSpecBuilder = new RequestSpecBuilder();
  reqSpecBuilder.setBaseUri(PayportApi.getUri());
  reqSpecBuilder.setAuth(RestAssured.basic(user, pass));
  return reqSpecBuilder.build();
}
```

...and you use it as

```java
RestAssured
  .given()
    .spec(getApiSpec())
  .get(...)
    ...
```

...how would you print the URI being called?

```
System.out.print("Calling api at " + "????");
```

**Comment by johanhaleby** [comment]
If you only want to print the URI you can do:

```java
RestAssured
  .given()
    .spec(getApiSpec())
    .log().uri().
  .get(...)
    ...
```

If you want to get a hold of the `baseUri` add a filter:

```java
given().
	    filter((requestSpec, responseSpec, ctx) -> {
	    	String baseUri = requestSpec.getBaseUri();
	        // Do something with baseUri
	        return ctx.next(requestSpec, responseSpec);
	    }).
when().
```
