### ISSUE TITLE
Unexpected Parsing Behavior

### ISSUE THREAD

**Issue by tramstheman** [rest-assured/rest-assured#830]
When I parse a JSON object like the one below, I get two different behaviors that seem to conflict. In this example I am parsing the same JSON object with two different search paths. 

The first string is being set to the results of searching for an element of an array within an array that does not exist. My expectation would be that it should throw some error saying the element doesn't exist, or return an array of null. 

The second string is being set to the results of searching for an element of an element that doesn't exist within the first array. This returns null, which is around what I would expect. 

**Parsing Dummy Example:** 

```
String string = getJsonPath().get("root_array.child_array.item_that_does_not_exist").toString();
String string2 = getJsonPath().get("root_array.item_that_does_not_exist").toString();
```

**JSON Example:** 

```
{
  "root_array":
  [

    {
      "something_else":"awesome",
      "child_array":
      [

      ]
    }
  ]
}
```

**Parsing Result:**

```
string: [[]]
string2: [null]
```

With string returning an "empty string" inside the nested array, I have no way of validating whether or not the element I am searching for exists or if it is an empty string (which may be valid). 

For example, if I am searching for name in the object:

`{ "name": "" } `

Searching for name would return an empty string and that would be up to me to validate. However, if I search that same object for "age", which doesn't exist, It would make sense to throw some sort of checked exception that would let me know that "age" did not exist in the response. Is this a reasonable?

**Comment by johanhaleby** [comment]
Hi, I think this is the way gpath (groovy collections) behaves and I'd like to conform to the way it handles things. If you find out that it's wrong then please tell me :)
