### ISSUE TITLE
Can i post a login and a JSON objects from plain Java maps, at the same time?

### ISSUE THREAD

**Issue by ferylukacs** [rest-assured/rest-assured#831]
So my tests rely on login on every GET test, but with the POST tests it gives me a "Failed to parse login page. Check for errors on the login page or specify FormAuthConfig." error.

 @Test
    public void test1(){
        **given()**.auth().form("user", "user")
                .**when()**.get(url + "my/url")
                .**then()**.statusCode(200).log().body()
                .contentType(ContentType.JSON)
                .body(containsString("value"), notNullValue())

How can i do the same, and also write a POST  line in there?

**Comment by johanhaleby** [comment]
You have to configure FormAuthConfig for this is to work. See docs [here](https://github.com/rest-assured/rest-assured/wiki/Usage#form-authentication) and have a look at the Javadoc for the FormAuthConfig class.
