### ISSUE TITLE
Disable custom logging filters using ifValidationFails()

### ISSUE THREAD

**Issue by RocketRaccoon** [rest-assured/rest-assured#836]
Hi,

I'm using custom logging filters for request and response. And was wondering how is it possible to disable them in case of using log().ifValidationFails()?

	given()
			.filters(new CustomRequestLoggingFilter(LogDetail.ALL)),
					new CustomResponseLoggingFilter(LogDetail.ALL))
			.log().ifValidationFails()
			.get();

Currently it prints log everytime, regardless test failed or not.

**Comment by johanhaleby** [comment]
No I don't think that's possible :/
