### ISSUE TITLE
Allow hamcrest matchers for cookie collection

### ISSUE THREAD

**Issue by teunvanvegchel** [rest-assured/rest-assured#837]
I'd like to assert not just that a cookie is present, but that there aren't any other cookies present.

Something like:

    .cookies(hasSize(2))
    .cookies(hasItems(hasProperty("name", "cookie1"), hasProperty("name", "cookie2"))

**Comment by johanhaleby** [comment]
Maybe you could use the `cookies(Map<String, ?> expectedCookies)` function or extract the cookies (`extract().detailedCookies()`) and use something like Hamcrest or Assertj to validate the it only contains what you expect.
