### ISSUE TITLE
Multipart Content disposition filename with diacritics are replaced by '?'

### ISSUE THREAD

**Issue by zetisam** [rest-assured/rest-assured#844]
I have a Rest-API that allows me to upload files. The response contains (among others) the filename as received by the system. 

One of the requirements of the Rest-API is to be able to cope with filenames with diacritics. 

Let's say for example _cédrìc.jpg_

When sending requests with Postman or jQuery, everything is OK.

I want to write a test in Rest-Assured to make sure this will always remain the case, and that I get notified if the filename isn't correctly escaped anymore.  But the files received from RA get c?dr?c.jpg as filename.

I've checked the actual request using wireshark, and the question marks are sent as literal characters (byte 3F), so somehow the 'é' and 'ì' are replaced by an '?'.

This is my test method:

    @Test
	public void testCreationDiacriticsInFilename() throws IOException, TimeoutException, InterruptedException {
        
        String diacriticsString = "Cédrìc";

        File diacriticsFile = MediaResourceUtil.createTestImage(diacriticsString);
        
		given().
			multiPart(PARAM_FILE, diacriticsFile).
		when().
			post(ENDPOINT_MEDIA).
		then().statusCode(HttpURLConnection.HTTP_CREATED).
            .assertThat().body("originalFileName", Matchers.containsString(diacriticsString));
	}

![image](https://cloud.githubusercontent.com/assets/16835193/24855420/e293e016-1de1-11e7-98a7-d145a743c5f7.png)

The file that is created is Cédrìc.jpg and is inside my temp folder.

As far as I know my system should be fully configured to use UTF-8. I'm running this on Windows 10. And I'm using RA v2.9.0

Is there anything special that I need to configure?

**Comment by johanhaleby** [comment]
Thanks for the detailed error report. I've heard other have problems with this as well. Have you tried to supply a charset explicitly using the `MultiPartBuilder`? If not maybe you can try if that helps?

**Comment by zetisam** [comment]
I didn't do this yet. Will try and let you know.

**Comment by zetisam** [comment]
Hey Johan,

What do you mean exactly by `MultiPartBuilder`. I can't really find any information about it. Can you give a quick example on how to use it?

**Comment by johanhaleby** [comment]
Sorry, I meant `MultiPartSpecBuilder`. See docs [here](https://github.com/rest-assured/rest-assured/wiki/Usage#multi-part-form-data) (scroll down a little bit).

**Comment by zetisam** [comment]
Okay, thx :-)

I've added the following code, but the result is still the same. The special (diacritic) characters are replaced by (literal) question marks.

    MultiPartSpecification multiPartSpec = new MultiPartSpecBuilder(diacriticsFile)
			.charset(Charsets.UTF_8)
			.controlName(PARAM_FILE)
			.fileName(diacriticsFile.getName())
			.build();

**Comment by johanhaleby** [comment]
That's what I expected. Thanks for the investigation, then I think it's something wrong with how Rest Assured encodes the filename. Need to look into this. If you want to help out and investigate why this is happening (and potentially event provide a pull request) that would be extremely helpful!

**Comment by zetisam** [comment]
I don't know enough of groovy and the apache httpcomponents library to fully resolve the issue.

I've debugged the code and found that the filename / multipart data is correct up until the point it is sent through the output buffer.

org.apache.http.impl.entity.EntitySerializer#serialize

When inspecting the output buffer, the charset is set to US_ASCII. Since é and è and the like are non-ascii values, they are likely converted to '?' when writing to the outputstream.

![image](https://cloud.githubusercontent.com/assets/16835193/24907101/0474702c-1ebb-11e7-9d31-ddbc032f4c83.png)

**Comment by johanhaleby** [comment]
This seems to be a mess (as always). See http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http.

**Comment by johanhaleby** [comment]
Ok I've looked into this now. What was confusing to me at first was that Apache HTTP Client was using the charset defined for the entire body (MultiPartEntity) and not for the individual multipart itself. 

So REST Assured already supports this if you specify a content-type manually AND you're not using STRICT mode (which is the default):

```java
given.config(RestAssuredConfig.config().httpClient(HttpClientConfig.httpClientConfig().httpMultipartMode(HttpMultipartMode.BROWSER_COMPATIBLE))).contentType("multipart/form-data; charset=UTF-8").. .. 
```
I've added a setting in the `MultiPartConfig` that allows you to specify defaultCharset (but it'scurrently only be taken into account when `MultiPartMode` is not STRICT):

```java
given.config(RestAssuredConfig.config().httpClient(HttpClientConfig.httpClientConfig().httpMultipartMode(HttpMultipartMode.BROWSER_COMPATIBLE))).contentType("multipart/form-data; charset=UTF-8").. .. 
```

What I could do is to automatically change `HttpMultipartMode` to `BROWSER_COMPATIBLE` *if* the `HttpMultipartMode` has _not_ been explicitly set _and_ a defaultCharset has been explicitly set. Does this make sense? I think it's quite complex but maybe it's ok?!

**Comment by zetisam** [comment]
Hi Johan,

Thanks!

I've just installed 3.0.3 and can confirm that it works on my API.
For me the current solution is more than sufficient.

I think automatically setting HttpMultipartMode to BROWSER_COMPATIBLE when it has not been explicitly set and defaultCharset is defined is a good idea however. Since I think in most cases those two settings belong together anyway. 

But for me this is not strictly necessary and I'm more than happy with the current approach.

**Comment by sen4ik** [comment]
Hi Johan, 

Thanks. It helped me to resolve similar issue today. Cheers.
