### ISSUE TITLE
How to send nested JSON request body and URL in REST ASSURED - Please Help !!!

### ISSUE THREAD

**Issue by shrutiSS** [rest-assured/rest-assured#845]
Request URl - "http://*******/abcd-server/login.xml"
Content-Type: application/json
Request body
{"login":
        {
        	
        "username": "abcd",
        "password": "pass123",
        "override":true,
        "version":"1.3.0.0"	 
        }  
}

----------------------My code----------------
	
String apiURL = "http://*******/abcd-server/login.xml";
String apiBody = "login":\{"username\": \"abcd\",\"password\": \"pass123\",\"override\":true,\"version\":\"1.3.0.0"\} ;
response = given().contentType("application/json").body(apiBody).when().get(apiURL).then().statusCode(200).extract().response();
			
Getting error in apiBody declaration.

**Comment by garimacha** [comment]
what is the error you are getting?

**Comment by johanhaleby** [comment]
Please use the mailing list when asking questions
