### ISSUE TITLE
rest-assured response time for REST APIs seems very high

### ISSUE THREAD

**Issue by KapilShandilya** [rest-assured/rest-assured#846]
I am trying to make use of rest-assured to test our Rest Apis. It seems the response time returned by rest-assured is significantly higher than expected.

I am using Response object (`io.restassured.response.Response`) to get the response time 
`response.getTime()`

As an example, lets take a public REST API 

> https://httpbin.org/get

The response times for this REST API as returned by rest-assured on multiple occasions is as below,
1556ms, 1557ms, 1642ms, 1484ms, 1731ms

The same REST call when hit from say, postman/curl at nearly same point of time gives below response times,
1245ms, 273ms, 264ms, 267ms,  260ms

This makes is difficult to verify the response time for the Rest calls.

**Comment by johanhaleby** [comment]
Yes this is indeed the case, especially when the JVM is cold. Never using `time` when the JVM is cold. REST Assured is NOT designed for performance and should not be used for exact performance measurements. The reason why `time` is available in the API is to catch relative differences. For example if at t1 your test took X milliseconds and you make a change to your code and now the test takes 10*X milliseconds then you might have broken something. See [docs](https://github.com/rest-assured/rest-assured/wiki/Usage#measuring-response-time).
