### ISSUE TITLE
Add websocket support

### ISSUE THREAD

**Issue by redijedi** [rest-assured/rest-assured#850]
I'm trying to test a websocket with restassured. Currently it hangs indefinitely. It would be great to be able to work with web socket data using the RestAssured API.

This code works to get a connection, but hangs regardless of what the server ends up sending or if the server closes the session.

```
RestAssured.given()
            .header("Upgrade", "WebSocket")
            .header("Connection", "Upgrade")
            .header("Sec-WebSocket-Version", 13)
            .header("Sec-WebSocket-Key", "Yx2RoE1qwByK+r3fO25+/Q==")
        .expect()
            .statusCode(200)
            .when()
                .request("GET");
```

**Comment by johanhaleby** [comment]
Websockets is not HTTP so I'm not even sure it it's a good idea?
