### ISSUE TITLE
Handling unparsable Expires Cookie values

### ISSUE THREAD

**Issue by ninjubohra** [rest-assured/rest-assured#856]
Hello all,

Looking at the issue #563 and the comment made by @martingith regarding a desire to handle `Expires=0` made me look back the section of the Cookie spec relating to handling of Expires attribute

https://tools.ietf.org/html/rfc6265#section-5.2.1

The third paragraph of the section says that if the attribute value is NOT parsable into a valid value that it should be ignored.  This means that we should NOT throw a (confusing) "can not be null" exception and stop the response processing

So I propose that the code of the `CookieMatcher.groovy` be adjusted as follows
```groovy
          } else if(equalsIgnoreCase(name, EXPIRES)) {
             value = trim(StringUtils.remove(value, "\""))
             Date parsedDate = DateUtils.parseDate(value)
	     if (parsedDate != null) {
                builder.setExpiryDate(parsedDate)
             } else {
               log.info("Ignoring the following unparsable 'Expires' attribute value: " + value)
             }
          }
```
Note: the logging of the bad value is optional (but helpful) the important item is to avoid the setting of the ExpiryDate on the Builder, when the date is not parsable, thereby avoiding the exception.

And apologizes in advance for not being able to do the change/PR myself.  I am **still** working through my company process for participating in OSS on company time.

**Comment by johanhaleby** [comment]
Thanks for the suggestion.. However I'm not the fond of logging. If this is not what you want it's kind of annoying. Perhaps we could make it configurable from the [HeaderConfig](https://github.com/rest-assured/rest-assured/blob/master/rest-assured/src/main/java/io/restassured/config/HeaderConfig.java)? I.e. one could configure there whether to follow the RFC (and ignore) or try to be flexible? Or is it too fine grained?

**Comment by ninjubohra** [comment]
Skip the logging if you desire...but I think we should follow the RFC and ignore unparsable attribute values.

We need to handle the `null` coming out of DateUtils.parseDate(...) rather than just propogating the `null` to the Builder.setExpiryDate(...) since we have coded that method to fail if `null` is given to it

Since skipping the attribute is permitted by the spec, I don't think we need to enable a configuration for it.

**Comment by jsingh6** [comment]
Do I have to wait for the release version to use this fix?

**Comment by ninjubohra** [comment]
As for "should we log" I am changing my mind on it...

I think logging in this situation is relevant because it lets the user know that we encountered (and are ignoring) some data that was received in the response.  I don't expect this condition to occur frequently but I (personally) would like to know when it did occur in case of where I am building a service and I don't realize that my cookie expires attribute value is not spec-compliant (so that I can fix it :-))

**Comment by johanhaleby** [comment]
ok, I'll add a log statement for now with the condition that it may be removed in the future.
