### ISSUE TITLE
Assert response data without doing actual request.

### ISSUE THREAD

**Issue by hexwit** [rest-assured/rest-assured#857]
Hello, I have following situation: 
In play2.5 framework i can test controller simulating request. So I am not actually doing it, 
but create an appropriate object and fill with necessary payload. And then I got response, 
with body and headers, etc. And I don't have running web server. 

For testing response JSON I supposed to used RestAssured library, but seems to be 
to make it work correctly I have to do actual http requests, and can't just provide payload.

So my question is: is there any way to use rest-assured without doing actual http requests, 
and getting String/JSON as input for doing assertion?  If yes, could you provide some samples? 

Thank you!

**Comment by johanhaleby** [comment]
> For testing response JSON I supposed to used RestAssured library, but seems to be
to make it work correctly I have to do actual http requests, and can't just provide payload.

The whole purpose if REST Assured is to do actual HTTP requests. If you only want to validate JSON should only depend on the [json-path](https://github.com/rest-assured/rest-assured/wiki/GettingStarted#jsonpath) project.
