### ISSUE TITLE
how to get CookieStore

### ISSUE THREAD

**Issue by rubyvirus** [rest-assured/rest-assured#859]
I have a need to get the CookieStore in the httpClientContext.
e.g. httpclient
httpClientContext.getCookisStore.getCookies().

**Comment by johanhaleby** [comment]
You should be able to get it from a [Filter](https://github.com/rest-assured/rest-assured/wiki/Usage#filters), see [this](http://static.javadoc.io/io.rest-assured/rest-assured/3.0.3/io/restassured/specification/FilterableRequestSpecification.html#getHttpClient--) method. You can safely cast it to `AbstractHttpClient`.

**Comment by rubyvirus** [comment]
thanks, but AbstractHttpClient->>getCookieStore Deprecated.

**Comment by johanhaleby** [comment]
True, but REST Assured depends on deprecated methods (unfortunately) so you cannot get around this afaik, see [this](https://github.com/rest-assured/rest-assured/issues/497) thread..
