### ISSUE TITLE
OAuth 1.0 POST with ContentType.URLENC.

### ISSUE THREAD

**Issue by aivancioglo** [rest-assured/rest-assured#868]
As I understand it is bug. Code like this:
```java
given()
                .auth()
                .oauth("customer_key", "customer_secret", "", "", OAuthSignature.HEADER)
                .contentType(ContentType.URLENC)
                .param("email", "email@gmail.com")
                .param("password", "password")
        .when()
                .post("localhost/accounts")
        .then()
                .log()
                .all();
```
gives me: "message": "Request signature mismatch."
So signature generate incorrect.

**Comment by johanhaleby** [comment]
I doubt that it's a bug, it's probably that you've calculated the customer_key and "customer_secret" wrong. See Scribe documentation for how to get ahold of these.

**Comment by AllpowerfulAndrew** [comment]
I do same in Postman. It works! And in Rest Assured is work if I use ContentTypeJSON, but if ContentType.URLENC isn't work. I tested it local and also tried this: http://term.ie/oauth/example/index.php

Thank you for answer!

**Comment by johanhaleby** [comment]
Maybe post man does the OAuth dance? In REST Assured you need to use Scribe (or another library for that). You can compare the HTTP requests using Wireshark to see the difference.

**Comment by AllpowerfulAndrew** [comment]
Request was identical besides authorisation header.

**Comment by johanhaleby** [comment]
And you're using OAuth1 and not 2?

**Comment by AllpowerfulAndrew** [comment]
Yes, only OAuth 1.0.

**Comment by AllpowerfulAndrew** [comment]
As I understand OAuth 1.0 ignore body, if we use JSON, bot it must not ignore body if we use form-url. Possible REST-assured ignore body always, so form-url request doesn't work.

**Comment by johanhaleby** [comment]
Hmm not sure to be honest, would be great if you could help out and investigate it.

**Comment by AllpowerfulAndrew** [comment]
Look at this: [9.1.1.  Normalize Request Parameters](https://oauth.net/core/1.0a/#anchor13)

I suppose the problem can be related to class named AuthConfig.java, in method "process"
in line: `OAuthRequest oauthRequest = new OAuthRequest(verb, requestURI.toString(), null);`.
Maybe the body of the request was ignored, am I right?

**Comment by johanhaleby** [comment]
I don't know why you think the body is missing from `new OAuthRequest(verb, requestURI.toString(), null);`? The third parameter is the name of service.

Do you know of a service where I can try OAuth1 to authenticate? That would make things much simpler.

**Comment by AllpowerfulAndrew** [comment]
You may try it: http://term.ie/oauth/example/index.php

**Comment by AllpowerfulAndrew** [comment]
How's the test going? Tried something?

**Comment by johanhaleby** [comment]
Haven't had time to test it yet

**Comment by AllpowerfulAndrew** [comment]
Our company want to use Rest Assured for testing, but we need URLENC. That is why I wrote you. It will be nice if you will fix it. I would do it, but I don't know how.

**Comment by johanhaleby** [comment]
I need to look into it again, it was a long time ago. I'd like it to be fixed! But it's been hard to debug issues with oauth1 since I haven't known of service to actually test it towards. But the link you provide seems promising.

**Comment by AllpowerfulAndrew** [comment]
My colleague suggested that the problem is ignoring the request body. Unfortunately, I do not know how to help any more.

**Comment by johanhaleby** [comment]
Oh ok, that's good input. REST Assured is based on [Scribe](https://github.com/scribejava/scribejava). Maybe if you could get it working with vanilla Scribe I could have a look at how REST Assured is using it wrongly.

**Comment by AllpowerfulAndrew** [comment]
To understand the problem, it will take a long time. I'am not professional. For now I haven't time, unfortunately. So I can't help you yet...

**Comment by johanhaleby** [comment]
I also have tight time constraints so it could take a while before I have the time to look into this.

**Comment by AllpowerfulAndrew** [comment]
I undurstand.

**Comment by dlenroc** [comment]
@johanhaleby  I checked this and found that OAuth request with ContentType.URLENC do not work because parameters was not added in oauthRequest.

Parameters actually didn't added. I tried to add parameters and seen that it solved the problem.

```JAVA
@Test
public void postRequestWithFormDataAndOauth1() {
    given()
            .contentType(ContentType.URLENC)
            .param("any_parameter", "value")
            .auth().oauth("key", "secret", "", "", OAuthSignature.HEADER)
    .when()
            .post("http://term.ie/oauth/example/request_token.php")
    .then()
            .body(containsString("oauth_token=requestkey&oauth_token_secret=requestsecret"));
}

```
```PATCH
Index: rest-assured/src/main/java/io/restassured/internal/http/AuthConfig.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- rest-assured/src/main/java/io/restassured/internal/http/AuthConfig.java	(revision 698bff4ab5d3b68d43582a5743ffc0929ea96c15)
+++ rest-assured/src/main/java/io/restassured/internal/http/AuthConfig.java	(revision )
@@ -28,12 +28,16 @@
 import org.apache.http.HttpException;
 import org.apache.http.HttpHost;
 import org.apache.http.HttpRequest;
+import org.apache.http.HttpEntity;
+import org.apache.http.NameValuePair;
 import org.apache.http.HttpRequestInterceptor;
 import org.apache.http.auth.AuthScope;
 import org.apache.http.auth.NTCredentials;
 import org.apache.http.auth.UsernamePasswordCredentials;
+import org.apache.http.client.utils.URLEncodedUtils;
 import org.apache.http.conn.ssl.SSLSocketFactory;
 import org.apache.http.conn.ssl.X509HostnameVerifier;
+import org.apache.http.impl.client.EntityEnclosingRequestWrapper;
 import org.apache.http.impl.client.RequestWrapper;
 import org.apache.http.protocol.ExecutionContext;
 import org.apache.http.protocol.HttpContext;
@@ -42,6 +46,7 @@
 import java.net.URI;
 import java.net.URISyntaxException;
 import java.security.KeyStore;
+import java.util.List;
 import java.util.Map;
 
 /**
@@ -259,6 +264,15 @@
                 Verb verb = Verb.valueOf(request.getRequestLine().getMethod().toUpperCase());
                 OAuthRequest oauthRequest = new OAuthRequest(verb, requestURI.toString(), null);
                 this.service = (OAuth10aService) getOauthService(isOAuth1, addEmptyTokenToBaseString);
+
+                HttpEntity entity = ((EntityEnclosingRequestWrapper) request).getEntity();
+                if (entity != null) {
+                    List<NameValuePair> params = URLEncodedUtils.parse(entity);
+                    for (NameValuePair param : params) {
+                        oauthRequest.addBodyParameter(param.getName(), param.getValue());
+                    }
+                }
+
                 service.signRequest((OAuth1AccessToken) token, oauthRequest);
 
                 if (signature == OAuthSignature.HEADER) {

```

**Comment by aivancioglo** [comment]
@dlenroc Thanks for solution. @johanhaleby You can also look at comments [here](http://www.ontestautomation.com/deserializing-pojos-in-rest-assured/), many people have this problem and as I understand we can find the same problem using form data with OAuth 2. Is it possible to fix it now?

**Comment by aivancioglo** [comment]
Thank you  @dlenroc for solution. @johanhaleby look at comments [here](http://www.ontestautomation.com/deserializing-pojos-in-rest-assured/), please. There are many people have this problem and as I understand we can find the same problem using form data with OAuth 2. Is it possible to fix it now?

**Comment by johanhaleby** [comment]
Could anyone please provide a pull request for this? If so I'll include it in the next release which I'm about to release very soon.

**Comment by aivancioglo** [comment]
@johanhaleby We found the solution only using deprecated classes. If it is fine to use deprecated classes, we can open pull request.

**Comment by johanhaleby** [comment]
Yes please do
