### ISSUE TITLE
Logging response if a statusCode assertion exists

### ISSUE THREAD

**Issue by mattadamson** [rest-assured/rest-assured#873]
Team,

I have logging of the response body working fine if the REST assured call succeeds. However if I add an assertion that the status code equals 200 / OK it throws an exception in the test and doesn't log.

.statusCode(HttpStatus.SC_OK)

What's the best way to ensure responses are still logged if assertions fail such as this?

Many thanks

**Comment by johanhaleby** [comment]
See [docs](https://github.com/rest-assured/rest-assured/wiki/Usage#log-if-validation-fails)
