### ISSUE TITLE
NullPointerException when document the response of test

### ISSUE THREAD

**Issue by albertkurnia** [rest-assured/rest-assured#875]
Sorry, I have trouble here. I want to document the rest assured test by putting code below 

       `final Map<String, String> labels = new HashMap<>();
        labels.put("device", "android");
        labels.put("shipping", "aws");

        final HashMap<String, Object> testVoucherRequest = new HashMap<>();
        testVoucherRequest.put("voucher_code", "dummyCode");
        testVoucherRequest.put("amount", 1000);
        testVoucherRequest.put("merchant_user_id", "dummyMerchantUserId");
        testVoucherRequest.put("labels", labels); 
        
       Map<String, Object> response =
            given()
                .auth().preemptive().basic("username", "pass")
            .contentType(ContentType.JSON)
                    .body(testVoucherRequest)I w
                    .filter(document("test-voucher", preprocessRequest(prettyPrint()),
                            responseFields(
                                    fieldWithPath("valid").description("status valid or invalid"),
                                    fieldWithPath("discount_amount").description("Discount Amount remaining"),
                                    fieldWithPath("reason").description("Response reason"),
                                    fieldWithPath("reason_params").description("Reason params"))))
            .when()
                .post("/api/v1/redemptions/test")
            .then()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("valid", equalTo(true))
                .body("discount_amount", equalTo(250))
                .extract().as(Map.class);`

There is NullPointerException when I run this test

`java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:500)
	at java.util.HashMap.<init>(HashMap.java:489)
	at org.springframework.restdocs.restassured3.RestDocumentationFilter.getConfiguration(RestDocumentationFilter.java:74)
	at org.springframework.restdocs.restassured3.RestDocumentationFilter.filter(RestDocumentationFilter.java:56)`

**Comment by johanhaleby** [comment]
Could this be a spring rest docs issue? I'm not maintaining the REST Docs project.

**Comment by albertkurnia** [comment]
is it? well, I'm sorry I thought this is the right room

**Comment by johanhaleby** [comment]
If there's a problem on the rest assured side I'd be happy to fix it.
