### ISSUE TITLE
file upload is not working

### ISSUE THREAD

**Issue by jagdeepjain** [rest-assured/rest-assured#876]
I have below code for file upload test.

`given()
    .multiPart("file", "abc.jpg", "image/jpeg")
    .with()
    .cookie("SESSION", "581a902e-9cb9-4d31-9cc8-c05752af6e10")
    .when()
    .post(url);`

**And below is the Request Payload.**
------WebKitFormBoundarymZN
Content-Disposition: form-data; name="employeeId"

500S0000008vf5uIAA
------WebKitFormBoundarymZN
Content-Disposition: form-data; name="attachment"; filename="abc.jpg"
Content-Type: image/jpeg

------WebKitFormBoundarymZN--

**Below are Request Headers.**
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:846242
Content-Type:multipart/form-data; boundary=----WebKitFormBoundarymZNmNoJQHQ2R9olV
Cookie:_SESSION=581a902e-9cb9-4d31-9cc8-c05752af6e10
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
X-Requested-With:XMLHttpRequest
X-Timezone-Offset:420

I am not able to under stand why I am getting response body and code as:
{
    "message": null
}
application/json 500

My question is what content from Request Payload or Request Header is required for test to run successfully.

**Comment by eganjs** [comment]
@johanhaleby Could this be closed? I imagine the ability to resolve this issue has been lost to time

**Comment by jagdeepjain** [comment]
Yes, we can close this.
