### ISSUE TITLE
Confusion in documentation regarding Gradle setup

### ISSUE THREAD

**Issue by obarcelonap** [rest-assured/rest-assured#877]
Hi,
Reading GettingStarted section there is a note that in my opinion looks confusing:

> You should place rest-assured before the JUnit dependency declaration in your pom.xml / build.gradle in  order to make sure that the correct version of Hamcrest is us

Source: https://github.com/rest-assured/rest-assured/wiki/GettingStarted#maven--gradle-users

Could someone explain a little bit more about this and how this is translated into gradle.build?

Thank you!

**Comment by garimacha** [comment]
Are you looking for an option to how to include rest-assured in gradle.build?

**Comment by johanhaleby** [comment]
This is because junit depended on another version of hamcrest which prevented rest assured from working correctly. Placing rest assured before junit resolves the issue.
