### ISSUE TITLE
How to add pdf or images to request and validate in response using rest assured?

### ISSUE THREAD

**Issue by priyasetty** [rest-assured/rest-assured#885]

**Comment by keetron** [comment]
RestAssured can send and receive text only API messages using the SOAP and REST protocol.
That said, you can send and receive pdf and img files when converting them to binary, some more information is here:
https://stackoverflow.com/questions/34485420/how-do-you-put-an-image-file-in-a-json-object

Now if you have an expected value, such as the file you want to compare with, you can convert this to binary using the same method and have RestAssured compare these two values.
