### ISSUE TITLE
OData Context not getting converted in JSon while using response.asString() method

### ISSUE THREAD

**Issue by Shubh-arya** [rest-assured/rest-assured#887]
I am trying to extract Url from an OData implemented URL i.e. http://services.odata.org/V4/(S(ifawfzcwhgzxo1iyb10fmodt))/TripPinServiceRW/People('russellwhyte') but I am getting null for "@odata.editLink". Response is below:
{
    "@odata.context": "http://services.odata.org/V4/(S(ifawfzcwhgzxo1iyb10fmodt))/TripPinServiceRW/$metadata#People/$entity",
    "@odata.id": "http://services.odata.org/V4/(S(ifawfzcwhgzxo1iyb10fmodt))/TripPinServiceRW/People('russellwhyte')",
    "@odata.etag": "W/\"08D4C93EFA82025B\"",
    "@odata.editLink": "http://services.odata.org/V4/(S(ifawfzcwhgzxo1iyb10fmodt))/TripPinServiceRW/People('russellwhyte')",
    "UserName": "russellwhyte",
    "FirstName": "Russell",
    "LastName": "Whyte",
    "Emails": [
        "Russell@example.com",
        "Russell@contoso.com"
    ],
    "AddressInfo": [
        {
            "Address": "187 Suffolk Ln.",
            "City": {
                "CountryRegion": "United States",
                "Name": "Boise",
                "Region": "ID"
            }
        }
    ],
    "Gender": "Male",
    "Concurrency": 636354719694062171
}

Can you please let me know something else to try or there is no way we can automation ODATA implemented RestApi with Rest Assured?

**Comment by johanhaleby** [comment]
You need to escape property names when they special characters. Instead of `"@odata.editLink"` do `"'@odata.editLink'"`.
