### ISSUE TITLE
How to check if a key exists in json via JsonPath?

### ISSUE THREAD

**Issue by ginccc** [rest-assured/rest-assured#893]
I am trying to figure out how to check if a key is present or not, but couldn't find a way to do so yet.

Assuming scenario a: 
```
JsonPath.from("{\"userInfo\":{\"name\":{\"firstName\":\"John\",\"lastName\":\"Silver\"}}}").get("userInfo.name.firstName");
```
will return "John" as expected.

But, scenario b:
```
JsonPath.from("{\"userInfo\":\"somethingElse\"}").get("userInfo.name.firstName");
```
will throw the follow exception: java.lang.IllegalArgumentException: The parameter "name" was used but not defined.

What I am trying to achieve is to know if "firstName" is present in the given json or not. Ideally, without having to catch an exception for this.

Is this possible? If so, how?

using: 
<dependency>
        <groupId>io.rest-assured</groupId>
        <artifactId>json-path</artifactId>
        <version>3.0.3</version>
</dependency>

Thanks!

**Comment by november1306** [comment]
get("/json").then().assertThat().body("userInfo.any { it.containsKey('name.firstName') }", is(true));
not shure if 'name.FirstName' will work. example from here (#2):
https://github.com/rest-assured/rest-assured/wiki/FAQ

**Comment by ginccc** [comment]
Thanks november1306 for your answer.
i am not planning to use the whole restassured lib, nor make any rest request. just wanted to just the jsonpath in order to validate a json that I already have. 
Also, I don't know the json and the "key" to check should be configurable, so the above solution won't work for me, unfortunately.

**Comment by shrivsk** [comment]
Hi Gregor,

I believe you need to look into the Json body as for its looking like issue
as you can see in your Json that you are not passing any name or first name
but your are requesting for name and first name using Get, i am bit
confused why are you doing that in respect of you can

JsonPath.from("{\"userInfo\":\"somethingElse\"}").get("userInfo.userInfo.somethingElse");


hope this will work


Regards

**Comment by ginccc** [comment]
No,  that's my point, in my scenario b I want to get a null back or something similar, such as "no, the key and respectively the value is not there".
But it looks like this won't work without catching an exception. neither with this library nor with the original one.

But thanks for the trouble shooting! 
this one can be closed.

**Comment by november1306** [comment]
ask google about 'hamcrest JSON', there should be a solution, like this
https://github.com/json-path/JsonPath/tree/master/json-path-assert

**Comment by shrivsk** [comment]
can you pass me the detailed requirement,

if you are passing the header and the value can can get the value using get

so please send me your exact Json and from that Json what you are expecting
for ?
