### ISSUE TITLE
How to assert my own JSON String without request?

### ISSUE THREAD

**Issue by aivancioglo** [rest-assured/rest-assured#897]
I want something like this:
<img width="881" alt="screen shot 2017-08-26 at 10 51 42 am" src="https://user-images.githubusercontent.com/20010228/29739702-a3d8b4dc-8a4c-11e7-9056-86766a7958c3.png">

But actually it works even I try this: 
<img width="1433" alt="screen shot 2017-08-26 at 10 37 41 am" src="https://user-images.githubusercontent.com/20010228/29739641-4ca71826-8a4b-11e7-909d-80f7552856b2.png">

Can you explain me how actually I need to do it, to assert my own json?

**Comment by johanhaleby** [comment]
You should just use JsonPath instead:

```java
String json = ...
JsonPath jsonPath = JsonPath.from(json);
assertThat(jsonPath.getString("video.size")).contains("infinite") // assertj assertion
```
