### ISSUE TITLE
Ability to provide SessionFilter globally

### ISSUE THREAD

**Issue by johno1985** [rest-assured/rest-assured#898]
Hi,

We are making use of the SessionFilter feature in our tests. However, we would like the ability to apply this filter globally rather that having to apply it to each and every test. Is this possible?

**Comment by johanhaleby** [comment]
Yes, use a global [request specification](https://github.com/rest-assured/rest-assured/wiki/Usage#specification-re-use) to which you supply the session filter. Something like:

```java
RestAssured.requestSpecification = new RequestSpecBuilder().addFilter(new SessionFilter(..)).build();
```

Also I would prefer if you would please use the mailing list when asking questions in the future :)

**Comment by johno1985** [comment]
Thanks Johan, and apologies for raising an issue. I'll use the mailing list
in the future.

Kind regards,

Jonathan Stearnes
