### ISSUE TITLE
Question: Security considerations?

### ISSUE THREAD

**Issue by martinbaste** [rest-assured/rest-assured#901]
If we allow a user to specify a valid tested URL, what security considerations are appropriate? Is testing any URL safe?

**Comment by johanhaleby** [comment]
What do you mean?

**Comment by martinbaste** [comment]
I have a form where a user can specify a URL to test. My worry is that a user could specify their URL that had code that could compromise the security of the server. Are there known security issues to have in mind?

**Comment by johanhaleby** [comment]
Yes there might be security concerns, it might depend on how the link is used. But I don't see how this is related to REST Assured?

**Comment by martinbaste** [comment]
The link is just checked to be a URL with JSON content type and fed to REST Assured. But feel free to close the issue if this is not related to REST Assured. Thanks for the feedback!

**Comment by johanhaleby** [comment]
Sorry I really think that this is out of scope and unfortunately I'm a bit short on time :( I'd rather ask someplace else, like stackexchange.
