### ISSUE TITLE
Fail to log to different log files with log4j multiple threads in testng.

### ISSUE THREAD

**Issue by yisake** [rest-assured/rest-assured#904]
I'm writing testing scripts with rest-assured and log4j/testng. 

##suite.xml
suite name="Suite" parallel="methods" thread-count="200"

##BaseTestCase.java
public class BaseTestCase{
	@BeforeMethod
	public void beforeMethod (Method method) throws Exception {
		this.getLogger(method);
		RestAssured.baseURI="http://127.0.0.1";
		RestAssured.port=5000;
		RestAssured.config = RestAssured.config().logConfig(new LogConfig().defaultStream(new ToLoggerPrintStream(this.logger).getPrintStream()));
		System.out.println(RestAssured.config.getLogConfig().isUserConfigured());
	}
}

##TestDemo.java test1 test2 run in different thread
public class TestDemo extends BaseTestCase {
@Test  
public void test1(){
    post("/hello").then().log().all();
}

@Test  
public void test2(){
    post("/hello").then().log().all();
}
}

As RestAssured.config is a static variable in java. So in different thread the logconfig will point to only one logger printstream. So all the log are wiritten to only one log file. It is hard to check the request/response after test case fails.

**Comment by johanhaleby** [comment]
Then you shouldn't use static configuration! Use reusable specifications instead (search for specification re-use in the docs).

**Comment by yisake** [comment]
@johanhaleby  Thanks , I've found the example of load private logconfig as below:
    	given().
    		config(this.getRestAssuredLogConfig()).
