### ISSUE TITLE
Multipart/mix: Allow to provide parameter with mime type or to give content type

### ISSUE THREAD

**Issue by wog48** [rest-assured/rest-assured#908]
Hello,

Using rest-assured was quite handy. Now I try to test my OData-Batch handling. Unfortunately i'm failing.
The[ OData specification requires](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752315) to give as content type including a parameter (_boundary= xyz_). As of now I'm not able to either give the parameter together with the mime type or to provide a ContentType.

See `io.restassured.internal.multipart.MultiPartInternal`  method `returnStringBody`.

It would be great if you can provide a solution.

Regards,
Oliver

**Comment by johanhaleby** [comment]
Can't do that with [MultiPartSpecBuilder](https://github.com/rest-assured/rest-assured/wiki/Usage#multi-part-form-data)?

**Comment by wog48** [comment]
To make a long story short: That doesn't help.

Indeed I'm doing that, but on the one hand the interface of [MultiPartSpecBuilder](https://github.com/rest-assured/rest-assured/blob/master/rest-assured/src/main/java/io/restassured/builder/MultiPartSpecBuilder.java) does not provide a method to set mime type parameter (you can just set the mime type as string) or a content type and on the other hand the multi part processing always ends in MultiPartInternal.

Oliver

**Comment by johanhaleby** [comment]
Hmm you should be able to do like this (if this is what you mean):

```java
given().contentType("multipart/mixed; boundary=abcdef").multiPart(..). ..
```

I.e. you can specify the boundary and content type of the request. You can also specify a default boundary in the `MultiPartConfig`:

```java
given().config(config().multiPartConfig(multiPartConfig().defaultBoundary("abcdef"))). ..
```

This should work as of 3.0.0.

**Comment by wog48** [comment]
Thanks for helping me out.
Using  `given().contentType("multipart/mixed;boundary=batch_abc").body(myString.getBytes())`  without using  `.multiPart(...)` works.

**Comment by koolsurya** [comment]
Hi Johan,

I am new to Rest Assured .Currently i am using Serenity with RestAssured in cucumber for automating the service layer in one of the projects.

In one of the scenarios,we are posting the the below request type in Fiddler
Headers:
ContentType: multipart/mixed;boundary=abc
Content length;234
User Agent:Fiddler
Host:abc.com


Body:
Content Type:application/json
--abc--
{
/*Json request body*/
}
--abc--
Content Type:application/octet-stream
 File upload path
--abc--


Can you please help me in how to post the same in Rest Assured?






Regards,
Surya
