### ISSUE TITLE
Restassured can not use multiple config in given()

### ISSUE THREAD

**Issue by yisake** [rest-assured/rest-assured#909]
As I use code below, I found that the defaultStream is not effective. Only the headerConfig is effective.In my mind, I think the config() method should configured as multiple Config.

		given().
			proxy("localhost", 8888).
			header("header1", "value1").
			header("header1", "value2").
			config(RestAssured.config().logConfig(new LogConfig().defaultStream(fileOutPutStream))).
			config(RestAssured.config().headerConfig(new HeaderConfig().overwriteHeadersWithName("header1"))).
			log().all().
		when().
			get("http://127.0.0.1:5000/hello").
		then().
			log().all().
			assertThat().statusCode(200).
			assertThat();

**Comment by johanhaleby** [comment]
The latter config overrides the first one. Use the same instead:

```java
RestAssured.config().logConfig(new LogConfig().defaultStream(fileOutPutStream))).and().headerConfig(new HeaderConfig().overwriteHeadersWithName("header1")));
```
