### ISSUE TITLE
Streaming poorly managed

### ISSUE THREAD

**Issue by sbuisson** [rest-assured/rest-assured#914]
I test a ws who stream data. Your lib concat all the data in one String. Can you add a method extract.asList who will distinguish the different data of a  stream?

**Comment by johanhaleby** [comment]
You can return the response as an InputStream if you want REST Assured to avoid parsing it to it's internal data structures before returning to you as a user:

```java
InputStream stream = get("/x").asInputStream();
```

Please use the mailing list when asking questions in the future.

**Comment by sbuisson** [comment]
I don't want an inputstream of char! I want a stream of SEPARATED String
