### ISSUE TITLE
Adopt semver

### ISSUE THREAD

**Issue by joebandenburg** [rest-assured/rest-assured#916]
I think REST Assured is excellent and use it regularly. However, I have found the library's use of version numbers confusing and inconsistent with other open source libraries.

Please considering adopting [Semantic Versioning](http://semver.org/) for future releases. This allows your users to recognise just from the version number when breaking changes have been made.

**Comment by johanhaleby** [comment]
I try to adhere to semantic versioning but not 100% so the point is taken. Sometimes I have indeed made breaking changes that I suspect wouldn't affect many users. But it's always documented in the changelog and release notes.
