### ISSUE TITLE
getBody().asString() does not give the correct string for unicode response body

### ISSUE THREAD

**Issue by maesiva** [rest-assured/rest-assured#921]
Call an API, that gives a response body with unicode content (chinese).
Read the string value using myResonse.getBody().asString()

rest-assured version: 3.0.3

Observed:
If the API returns a body: 
{"hello":"微软平板电脑"} 
rest assured's myResonse.getBody().asString() gives:
{"hello":"Ĝu0083\u0083\u0083\u0083\u008........ }

Java Code:
```
RequestSpecification requestSpec;
...
Response myResponse = requestSpec.get("url");
String respBody = myResponse.getBody().asString();
```
Set a breakpoint and observed the contents of respBody : {"hello":"Ĝu0083\u0083\u0083\u0083\u0083\u008........ }
Chinese characters are stored as long repeating patterns of \u0083

**Comment by johanhaleby** [comment]
Is the charset specified in the response correctly?

**Comment by maesiva** [comment]
I've set the request header : Accept-Charset=utf-8.
myResponse.getContentType() is: application/json; charset=utf-8

**Comment by johanhaleby** [comment]
Hmm what JSON mapper do you have in classpath?

**Comment by maesiva** [comment]
Please ignore. It was a false alarm, sorry.

My other test (POST) was currupting the unicode characters. I added the charset=UTF-8 and the POST was properly uploading the json data and the sub-sequent GET recieved the proper json data.

Old:
Content-Type=application/octet-stream

Now:
Content-Type=application/octet-stream; charset=UTF-8

Closing the issue.

**Comment by johanhaleby** [comment]
👍
