### ISSUE TITLE
One of my test stop working after upgrade the Rest Assured version

### ISSUE THREAD

**Issue by pgandarillas** [rest-assured/rest-assured#928]
I'm trying to execute the same code I used to use when using restassured 2.9, but it is failing with the following error:

`java.lang.AssertionError: 1 expectation failed.
XML path root.Cats.Rate.Token doesn't match.
Expected: a string containing "Cg"
Actual: 
CgVI............................etc`

As you can see it fails even though that string is displayed in the Actual part

This is the Response to the request

```json
{
  "Cats": [
        {
        "Code": "XXXX",
        "Ven": {          
            "Description": "Any"
        },

        },
        "Rate": {
            "Actual": {
                "Amount": "XXX",
                "Currency": "USD"
            },
            "Token": "Cg..........................................",

       {
        "Code2": "2XXXX",
        "Vend": {
            "Code": "2X",
            "Description": "aNY2"
        },

            "Token": "Cg...................................",

}
```

And this is my code

```java
Response responseshop = given().header("Authorization", "Basic 
    XXXXXXXXXXX=").header("accept-version","2.0.0").header("Accept", 
    "application/xml").
            param("Location", "Geocode,XX.XXXXXX,-XX.XXXXXX").
            param("Pick", "2017-12-12"). 
            param("Drop", "2017-12-15").            
            get("/cats/shop?AppKey=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"); 
        responseshop.then().log().all().
            statusCode(200).            
                     body("root.Cats.Rate.Token", containsString("Cg")); 
            System.out.println("This is the Response");
            System.out.println(responseshop);             
            String Token =responseshop.path("root.Cats.Rate.Token");
           System.out.println("This is the Token");
           System.out.println(Token);
```

**Comment by johanhaleby** [comment]
Your JsonPath doesn't seem correct, you shouldn't use "root"

**Comment by pgandarillas** [comment]
just tried that and got this error:
`java.lang.AssertionError: 1 expectation failed.
JSON path Cars.Rate.BookToken doesn't match.
Expected: a string containing "Cg"
  Actual: [CgVIRVJUWhIkYmQ2OTU3MmEtNzYxZi00NGIyLWFlYTAtMjQ0NzdiMDkxMjFlGhQyMDE3LTEwLTE4VDE2OjMzOjU2WiICWlQ=, CgVIRVJUWhIkY2QzODk0YzQtMjc5OS00ZDMxLWE3OWQtNmU1Y2E0ZGE2NzFjGhQyMDE3LTEwLTE4VDE2OjMzOjU2WiICWlI=, CgVIRVJUWhIkYzY3ZTc2MzAtNmUzNS00NjM1LWJlOTItNGYzMmE3MGM1YzBhGhQyMDE3LTEwLTE4VDE2OjMzOjU2WiICWkU=]
`

**Comment by johanhaleby** [comment]
That's correct, containsString operates on Strings but your result is a *List* of Strings. You should probably be able to do something like:

```java
body("Cats.Rate.Token", hasItem(containsString("Cg")));
```

**Comment by pgandarillas** [comment]
that worked thanks! It is weird since before the upgrade that code was working just fine.
But please one more question
I used to have this code to print the Token
`String BookToken = responseshop.path("Cars.Rate.BookToken");
		       System.out.println("This is the BookToken from Shop Response");
		       System.out.println(BookToken);`

But now since it is a list...how can I extract only the first one?

**Comment by johanhaleby** [comment]
Please use the mailing list.
