### ISSUE TITLE
Using deprecated AbstractHttpClient does not allow upgrade to Apache HttpClient 4

### ISSUE THREAD

**Issue by lgoldstein** [rest-assured/rest-assured#935]
Any attempt to replace the `HttpClientFactory` with one that creates an Apache _HttpClient_ 4 instance, yields:
```
RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1730)
 - Cannot cast object 'org.apache.http.impl.client.InternalHttpClient@9b3be1c' with class 'org.apache.http.impl.client.InternalHttpClient' to class 'org.apache.http.impl.client.AbstractHttpClient'
```
This means that one cannot use all the advanced features available in version 4 by providing a different factory via
```java
HttpClientConfig httpClientConfig = new HttpClientConfig();
httpClientConfig = httpClientConfig.httpClientFactory(myClientFactory);
```
unless the factory creates a **deprecated** instance of `AbstractHttpClient`

**Comment by johanhaleby** [comment]
This is tracked and discussed here: https://github.com/rest-assured/rest-assured/issues/497
