### ISSUE TITLE
getList() method allows to save Float values in a list of Integers.

### ISSUE THREAD

**Issue by chidusd** [rest-assured/rest-assured#941]
When we create a new JsonPath as follows,
`JsonPath newJson = new JsonPath(new File(System.getProperty("user.dir")+"\\myjson.json"));`

And, when we use getList() method to save json values in a java List<T>,  
                               
                                `List<Integer> myList = newJson.getList("store.book.price");`
				`List<Boolean> myList1 = newJson.getList("store.book.price");`

the getList() method allows the user to save Float values in a list of Integers/Boolean.

Please see the below screenshot:

![restassured](https://user-images.githubusercontent.com/13567422/32645612-1b0cff5c-c60e-11e7-8e41-b3926f6ce239.png)

**Comment by johanhaleby** [comment]
Yes it's not type safe and this is the way Java generics works. This has nothing to do with REST Assured.

**Comment by chidusd** [comment]
Thank you @johanhaleby .
