### ISSUE TITLE
passing null value as parameter throws "java.lang.IllegalArgumentException"

### ISSUE THREAD

**Issue by vikramvi** [rest-assured/rest-assured#942]
I've requirement to check null value for a parameter and this is how I'm passing it

 ```
given().
                contentType("application/json").
                pathParam("NI", 3000).
                pathParam("DP", null).
```

but this code throws error  

`java.lang.IllegalArgumentException: parameterValue cannot be null`

related issue https://github.com/rest-assured/rest-assured/issues/631

**Comment by johanhaleby** [comment]
What do you mean by "check null value"? You cannot pass "null" as a path parameter. It doesn't make sense, perhaps you mean an empty string?

**Comment by vikramvi** [comment]
@johanhaleby this is what I'm doing with cURL

curl -i -H "Content-Type: application/json" -X GET http://end_point/v1/grid?netIncome=3000&downPayment=**null**&loanDuration=**null**

It returns 200 after ignoring values of downPayment, loanDuration. I would like to simulate same with rest-assured library, please clarify.

**Comment by johanhaleby** [comment]
Then pass in a `null` as a string, `"null"`

**Comment by johanhaleby** [comment]
And besides `downPayment` and `downPayment` are query parameters in the REST Assured parlance, not path parameters.

**Comment by johanhaleby** [comment]
So use `queryParam` instead

**Comment by vikramvi** [comment]
Thanks, I tried below with one issue

```
 given().
                contentType("application/json").
                queryParam("netIncome", 3000).
                queryParam("downPayment", "null").
                queryParam("loanDuration", "null").
        when().
                get("http://end_point/v1/grid").
        then().
                statusCode(200);
```
Expected status code <200> but was <400>.

But when I just have empty string `" "` , it works fine.

**Comment by vikramvi** [comment]
@johanhaleby can you please clarify per last comment ?

**Comment by johanhaleby** [comment]
> So use `queryParam` instead

Like you just did, don't use `pathParam` when you mean `queryParam`. Also `"null"` is a string, you probably want to use an empty string ("") or no value at all (e.g. `queryParam("downPayment")`)

**Comment by vikramvi** [comment]
Thanks for clarifications.

**Comment by PaulinSangeetha** [comment]
Hi,
How to pass empty body to post request using  Rest Assured? Help me to resolve this.

**Comment by horuktaras** [comment]
@PaulinSangeetha Im using "{}"
