### ISSUE TITLE
Problem opening a link with json in query params

### ISSUE THREAD

**Issue by BernhardBln** [rest-assured/rest-assured#944]
I'm making a request to a server, and in the response, there is a (full) link with some json payload as query parameter (URL encoded, of course):

    http://localhost:54003/collection?fq=%7B%22type%22%3A%22StringFilter%22%2C%22value%22%3A%22Manufacturer1%22%2C%22filterName%22%3A%22manufacturerName%22%7D&limit=20&offset=0&sort=

The json payload of the fq query param decoded:

    {"type":"StringFilter","value":"Manufacturer1","filterName":"manufacturerName"}

Problem is - when I take this link and make another request using rest assured, I get a 500 on the server as the fq param seems to get double encoded - in the resource method on the server, the string that contains the fq param is the encoded string (but should be decoded already).

When I use a plain jersey client to resolve the link, everything works.

Is this a bug, or am I supposed to use a different method of rest assured when I want to resolve a link that I extracted from a previous response?

**Comment by BernhardBln** [comment]
To clarify a little further - this is my resource method on the server side:

    @GET
    public CollectionResponse getAll(
        @QueryParam("q") final String query,
        @QueryParam("fq") final String filterQuery, ...) {

        // filterQuery should be:
        // {"type":"StringFilter","value":"Manufacturer1","filterName":"manufacturerName"}

When using jersey-client, the filterQuery string is set as expected. 


But when using rest assured, it is still encoded:
    %7B%22type%22%3A%22StringFilter%22%2C%22value%22%3A%22Manufacturer1%22%2C%22filterName%22%3A%22manufacturerName%22%7D

**Comment by johanhaleby** [comment]
REST Assured performs url encoding by default, but you can easily disable it, see [docs](https://github.com/rest-assured/rest-assured/wiki/Usage#url-encoding). And please use the mailing list when asking questions in the future.
