### ISSUE TITLE
Add support for body content length assertions

### ISSUE THREAD

**Issue by dmak** [rest-assured/rest-assured#952]
Currently the expression `...then().statusCode(200).body(greaterThan(5))` does not work as it expects that body is a number. The only possible way to check body size is to extract body byte array and check the length like this:

    Response response = given()...when().get(...);
    assertTrue(response.asByteArray().length > 5);

Maybe API could be extended for specific handling of matchers that require a number or additional method `bodyLength(greaterThan(5))` is added to API?

**Comment by johanhaleby** [comment]
Can't you do:

```java
...
then().
           header("Content-Length", Integer::parseInt, greaterThan(5))
```

**Comment by dmak** [comment]
We have considered that option but unfortunately `Content-length` header is not provided by the service.

**Comment by johanhaleby** [comment]
Then I think this is quite a limited use case. You could simply create your own custom Hamcrest matcher for this. Something like this:

```java
package org.hamcrest.core;

import org.hamcrest.Description;
import org.hamcrest.Factory;
import org.hamcrest.Matcher;
import org.hamcrest.TypeSafeMatcher;

import static org.hamcrest.Matchers.equalTo;

/**
 * Tests if the argument is a {@link CharSequence} that matches a specified length.
 */
public class CharSequenceLengthMatcher extends TypeSafeMatcher<CharSequence> {

    /**
     * Creates a matcher of {@link CharSequence} that matches when the examined {@link CharSequence} has the length
     * determined by the specified matcher.
     * <p/>
     * For example:
     * <pre>assertThat("myStringOfNote", length(not(equalTo(10))))</pre>
     * <pre>assertThat("myStringOfNote", length(lessThan(15))))</pre>
     *
     * @param lengthMatcher the matcher to apply to the examined {@link CharSequence}
     */

    @Factory
    public static CharSequenceLengthMatcher length(Matcher<? super Integer> lengthMatcher) {
        return new CharSequenceLengthMatcher(lengthMatcher);
    }

    /**
     * Creates a matcher of {@link CharSequence} that matches when the examined {@link CharSequence} has the specified
     * length.
     * <p/>
     * For example:
     * <pre>assertThat("myStringOfNote", length(10))</pre>
     *
     * @param length the length that the returned matcher will expect any examined string to have
     */
    @Factory
    public static CharSequenceLengthMatcher length(int length) {
        return length(equalTo(length));
    }

    private final Matcher<? super Integer> lengthMatcher;

    public CharSequenceLengthMatcher(Matcher<? super Integer> lengthMatcher) {
        this.lengthMatcher = lengthMatcher;
    }

    @Override
    protected boolean matchesSafely(CharSequence text) {
        return lengthMatcher.matches(text != null ? text.length() : 0);
    }

    @Override
    public void describeMismatchSafely(CharSequence item, Description mismatchDescription) {
        mismatchDescription.appendText("was length \"").appendText(item == null ? null : String.valueOf(item.length())).appendText("\"");
    }

    @Override
    public void describeTo(Description description) {
        description.appendText("has string length ").appendDescriptionOf(lengthMatcher);
    }
}
```

**Comment by dmak** [comment]
I already see the difficulty with above code: it assumes that body is string, however it could be just a binary stream (e.g. image). Can it extend `BaseMatcher<byte[]>` ?

**Comment by johanhaleby** [comment]
RA only converts the body if you're using expectations (`then()...`) otherwise if should be left as is. But in this case yes it would convert it and taking the charset into account. Making a change in RA to accommodate your use case would probably require an extensive rewrite. I would suggest that in this case it's perhaps better to consume the inputstream to an array and validate the length of the array without using REST Assured expectations. I.e. something like:

```java
byte[] bytes = get("/x").asByteArray();
assertThat(bytes.length).isEqualTo(120);
```

**Comment by dmak** [comment]
OK, that is exactly I am using (see top-most post). If there are no plans to improve that, then the issue can be closed.

**Comment by johanhaleby** [comment]
I can't see myself having time to implement this in a foreseeable so unless you're willing to dig into it yourself and provide a PR I'll close the issue.
