### ISSUE TITLE
Add cookie filter with cookie attributes matching.

### ISSUE THREAD

**Issue by MaciejCiszewski** [rest-assured/rest-assured#956]
Currently we do have CookieFilter that parses the cookies from the response and adds them to the request unconditionally in terms of the domain or other cookie attributes like path etc. 
Wouldn't it be useful to create more advanced version of this filter that does proper cookie matching against the request URL so that it works more like a real browser?

**Comment by johanhaleby** [comment]
Yeah that sounds like a good idea. Maybe you could help out?

**Comment by MaciejCiszewski** [comment]
@johanhaleby Sure, PR added: [https://github.com/rest-assured/rest-assured/pull/957](url)
