### ISSUE TITLE
x-www-form-urlencoded keyValue pair parameters are sent as form-data

### ISSUE THREAD

**Issue by sumit-global** [rest-assured/rest-assured#963]
Hi,

I have a post request where i need to send x-www-form-urlencoded keyValue pair parameters and content-type should be x-www-form-urlencoded.

If i look to post man it will look like please find attachements

I am using below code:

RestAssured.baseURI = "https://ww.abc.com";

         RequestSpecification request = RestAssured.given().log().all().config(RestAssured.config()
         .encoderConfig(EncoderConfig.encoderConfig()
         .encodeContentTypeAs("x-www-form-urlencoded",
         ContentType.URLENC)))
         .contentType("x-www-form-urlencoded")
          .formParam("abc", "def")
          .formParam("hij", "xyz")
          .formParam("123", "456")
          .formParam("789", "222")
          .formParam("password", "abc")
         .header("accept", "application/json")
         .header("123", "abc")
         .header("456", "ttt")
         .header("channel", "1111").request();

Response res = request.post("/111");

When i check RestAssured logs it shows all parameters in Form params but parameters are sent as form-data not as x-www-form-urlencoded parameters.
Please do let me know is there any other way to send x-www-form-urlencoded parameters or some updation required in code.
![auto generated inline image 1](https://user-images.githubusercontent.com/24950602/34976648-7a4cbb2c-fabd-11e7-8c59-c9c91051ddbe.png)
![auto generated inline image 2](https://user-images.githubusercontent.com/24950602/34976649-7a887ca2-fabd-11e7-9432-987523eef1d9.png)

**Comment by sumit-global** [comment]
finally find the fix, what is missed is to set charset UTF-8 in content type, after adding that it works fine.

**Comment by cheeseinlove** [comment]
I think i meet the same problem with you .Here comes my code `                RestAssured.baseURI="*****"
        RequestSpecification request = RestAssured.given().config(RestAssured.config()
                .encoderConfig(EncoderConfig.encoderConfig()
                .encodeContentTypeAs("x-www-form-urlencoded",
                ContentType.URLENC)))
                .contentType(ContentType.URLENC.withCharset("UTF-8"))
                .formParam("grant_type", "authorization_code")
                .formParam("code", code)
                .formParam("client_id","sb-caas2-xsuaa!t791")
                .when().log().all()
                .then().log().all().request()
        request.post("/oauth2/token")`  
and the response is 405 with  msg:"Only support Content-Type：application/x-www-form-urlencoded"  .
I have tried in postmant it works fine. This problem drives me crazy for a couple f days .
Hope your reply .Thanks a lot!

**Comment by cheeseinlove** [comment]
Here is my log
`Request method:	POST
Request URI:	***
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	grant_type=authorization_code
				code=28FtesRhWx
				client_id=***
Path params:	<none>
Headers:		Accept=image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap
				Content-Type=application/x-www-form-urlencoded; charset=UTF-8
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
HTTP/1.1 405 Method Not Allowed
Content-Length: 61
Date: Tue, 30 Jan 2018 06:59:20 GMT
X-Correlationid: 5d155b6f-0d85-4775-5f50-82c397e5b44b
X-Smp-Log-Correlation-Id: 5d155b6f-0d85-4775-5f50-82c397e5b44b
X-Vcap-Request-Id: 5d155b6f-0d85-4775-5f50-82c397e5b44b

Only support Content-Type：application/x-www-form-urlencoded`

**Comment by sumit-global** [comment]
Hi cheeseinlove,

try with below code
Response request = RestAssured.given()
                .config(RestAssured.config()
                        .encoderConfig(EncoderConfig.encoderConfig()
                                .encodeContentTypeAs("x-www-form-urlencoded",
                                        ContentType.URLENC)))
                .contentType("application/x-www-form-urlencoded; charset=UTF-8")
                .formParam("grant_type", "authorization_code")
                .formParam("code", "")
                .formParam("client_id", "sb-caas2-xsuaa!t791")
                        .post("/oauth2/token");

**Comment by cheeseinlove** [comment]
I tried as you edited .However  it failed with response code :405 &&msg:Only support Content-Type：application/x-www-form-urlencoded.By the way ,my rest assured version is 3.0.3 in gradle and i use the java code with HttpURLConnection to post the request successfully!I'm still find the  way to solve it in rest assured ...That's a long way @sumit-global

**Comment by saathya2007** [comment]
Thanks @sumit-global . it was very useful for me and it worked :)

**Comment by BSrinivas** [comment]
The below code should be enough
`RestAssured.given()
.baseUri(baseUrl)
.contentType(ContentType.URLENC.withCharset("UTF-8"))
.formParam("grant_type", "password")
.formParam("username", "Username")
.formParam("password", "Password")
.post("/auth/generatetoken/");`

**Comment by alexriordan** [comment]
Finally fix the issue, Thanks Srinivas.

**Comment by jiten0811** [comment]
I keep on getting 404  even though i am following above steps:

given().
  config(RestAssured.config() .
		  encoderConfig(EncoderConfig.encoderConfig()
		  .encodeContentTypeAs("x-www-form-urlencoded",ContentType.URLENC)))
  .contentType(ContentType.URLENC.withCharset("UTF-8"))  
  .auth().basic(Username, password).
  
  header("Authorization","Basic "+encodedAuthString)
  .header("Content-Type", "application/x-www-form-urlencoded")	
  .header("Accept","application/json") 
  .formParam("grant_type", "client_credentials") 
  .when()
  .post("https://api-mig.tetrapak.com/oauth2/v2/token").then().log().all().extract().response();

**Comment by raohariom422** [comment]
Hi,
Below code is working fine for me:-
public void AccessToken() throws IOException
	{
		String path = System.getProperty("user.dir")+"//src//test//java//com//force//config//Config.properties";
		FileInputStream fis=new FileInputStream(path);
		prop.load(fis);
		RestAssured.baseURI=prop.getProperty("SSOAccessTokenURL");
		Response request = RestAssured.given()
				.config(RestAssured.config()
				.encoderConfig(EncoderConfig.encoderConfig()
				.encodeContentTypeAs("x-www-form-urlencoded",
				ContentType.URLENC)))
				.contentType("application/x-www-form-urlencoded; charset=UTF-8")
				.formParam("grant_type", "client_credentials")
				.formParam("client_id", "1234")
				.formParam("client_secret", "5678")
				.post("/tokens/bearer");
	    System.out.println("Response is"+request);
	    String responsestring=request.asString();
		System.out.println(responsestring);
		io.restassured.path.json.JsonPath js=new io.restassured.path.json.JsonPath(responsestring);
		System.out.println("js is:"+js);
		String token=js.get("access_token");
		System.out.println("token is:"+token);
	}

**Comment by kuldeep-cashify** [comment]
> I tried as you edited .However it failed with response code :405 &&msg:Only support Content-Type：application/x-www-form-urlencoded.By the way ,my rest assured version is 3.0.3 in gradle and i use the java code with HttpURLConnection to post the request successfully!I'm still find the way to solve it in rest assured ...That's a long way @sumit-global

HI Can you share the Code which work for You.
