### ISSUE TITLE
Not able to Upload file as binary data using rest assured

### ISSUE THREAD

**Issue by yengda** [rest-assured/rest-assured#964]
Hi All,
I need to upload file as binary data along with content type header as per the file type like "application/pdf". The endpoint does not support multi-part file upload. 
Is there any other way to upload a file using rest assured which supports binary file upload?

**Comment by johanhaleby** [comment]
Yes, you should be able to do:

```java
byte[] pdfAsByteArray = ...
given().contentType("application/pdf").body(pdfAsByteArray).when().post("/x"). ..
```
