### ISSUE TITLE
Cannot get requests with certificate to work 

### ISSUE THREAD

**Issue by BogdanJelerRO** [rest-assured/rest-assured#967]
Hello. I have certain endpoints in the apis which are secured with a p12 certificate. I cannot get those tests to run anymore. 

Here is my setup . Each test class extends a BaseApiTest in which I have this : 

 ```
@BeforeClass
    public void setUpCaseFlow() throws Exception
    {
        RestAssured.useRelaxedHTTPSValidation("TLSv1.2");
       
        
        RestAssured.trustStore("resources/vlm.jks", "changeit");
        RestAssured.config().getSSLConfig().with().keyStore("D:\\Development_Repos_ToServeTest\\vlm_systemtest\\src\\stest\\resources\\backend_client.p12","changeit");
        
        
       //RestAssured.keyStore("/resources/backend_client.p12" ,"changeit");
        
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }
```

My p12 certificate is found in the /src/stest/resources. In the tests for which I have secured endpoints I do this 

 ```
@Test(priority = 2)
    public void getPackageDescriptors() throws Exception
    {
        String backendClientCertificate = "backend_client.p12";
        ClassLoader classLoader = ClassLoader.getSystemClassLoader();
        File file = new File(classLoader.getResource(backendClientCertificate).getFile());
        
        packageDescriptorEbri = given().spec(reqSpecWithCertificate).auth().certificate(file.getName(), "changeit",
                                                           new CertificateAuthSettings().                                                      
                                                           trustStoreType("PKCS12")).
                                when().get(ENDPOINT + firstPackageName + "/" + VERSION).then().statusCode(200).extract().path("ebri");
```

The exception I get is this : 

`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at sun.security.ssl.Alerts.getSSLException(Unknown Source) at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source) at sun.security.ssl.Handshaker.fatalSE(Unknown Source) at sun.security.ssl.Handshaker.fatalSE(Unknown Source) at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) at sun.security.ssl.Handshaker.processLoop(Unknown Source) at sun.security.ssl.Handshaker.process_record(Unknown Source) at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:573) at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:557) at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)`

Any ideas about this ? I tried almost everything suggested on the web and did not workout for me

**Comment by johanhaleby** [comment]
You could also try the mailing list if you haven't done so already, perhaps there's someone who can help you there.

**Comment by johanhaleby** [comment]
Also try https://stackoverflow.com/a/37436519/398441

**Comment by BogdanJelerRO** [comment]
@johanhaleby : tried what's in the link, it did not worked for me, but I'll retry . What mailing list are you referring to ?

**Comment by johanhaleby** [comment]
Search for "mailing list" on the front page, https://github.com/rest-assured/rest-assured

**Comment by BogdanJelerRO** [comment]
@johanhaleby  : can you please give me an example of how loading a certificate like this should work?
I managed to get it work in Postman , by loading the crt file and the key (the private key)
Can I do this in RestAssured? Not to load the p12 file dirrectly, but the crt and the key files . 

Thanks alot for your support

**Comment by johanhaleby** [comment]
@BogdanJelerRO I've never tried this myself so I don't know. A quick google search turns up an SO [question with this answer](https://stackoverflow.com/questions/36352033/how-to-make-https-get-call-with-certificate-in-rest-assured-java/37422468):  https://stackoverflow.com/questions/36352033/how-to-make-https-get-call-with-certificate-in-rest-assured-java/37422468 

Maybe that helps.

**Comment by BogdanJelerRO** [comment]
found the solution : 

 ```
RestAssured.config = RestAssured.config().sslConfig(SSLConfig.sslConfig()
                                                                     .trustStore(this.getClass().getResource(trustStore).getFile(), trustStorePassword).trustStoreType("JKS")
                                                                     .keyStore(this.getClass().getResource(keyStore).getFile(), keyStorePassword).keystoreType("PKCS12"));
```

**Comment by BogdanJelerRO** [comment]
this ticket can be closed.

**Comment by exerciseaccount** [comment]
@BogdanJelerRO, were you able to use the CRT and KEY files? I was not able to, and spent the last 2 days trying to get rest assured to work with the certificates. Any help would be deeply appreciated.

**Comment by BogdanJelerRO** [comment]
@exerciseaccount  As far as I remember you need to pack the crt into the pkcs12 and load them into your solution , both truststore and keystore

**Comment by Suchithra51020** [comment]
@BogdanJelerRO can yu please let m,e know how you got this??

**Comment by lauragarzong** [comment]
> 

Someone could explain me how did you add the certificates?
