### ISSUE TITLE
How can we run Rest assured testcases as part CD/CI pipeline using jenkins

### ISSUE THREAD

**Issue by gsainagendraprasad** [rest-assured/rest-assured#968]
HI we wrote RestAssured test cases using Java - intellij IDE, we would like to execute this testcases as part CD/CI pipleline through jenkins. How can we do this??

**Comment by johanhaleby** [comment]
This is out of scope of the REST Assured project.

**Comment by manamirest** [comment]
Can we run them from Gitlab ?
Thanks,
Manami

**Comment by johanhaleby** [comment]
@manamirest I would think so
