### ISSUE TITLE
Getting IllegalArgumentException when using "?" & "@" in Json Path

### ISSUE THREAD

**Issue by rahulmittal14** [rest-assured/rest-assured#969]
java.lang.IllegalArgumentException: Invalid JSON expression:
Script1.groovy: 1: expecting EOF, found '[' @ line 1, column 37.
                            CourseList[?(@.CatalogNumber="131")]
                                             ^

Please let me know how to solve it.

**Comment by SreecharanShroff** [comment]
$..[?(@.object_name=='test')].r_object_id
reproducible with above valid jsonpath, could you please fix or provide any workaround ?

**Comment by johanhaleby** [comment]
REST Assured is not using jsonpath, it's using gpath as described by the [docs](https://github.com/rest-assured/rest-assured/wiki/Usage#example-1---json).

**Comment by SreecharanShroff** [comment]
ok, got it working with gpath. thanks @johanhaleby

**Comment by ChawlaS-ELS-CT** [comment]
Using the below code:
List<String> noCustomerUserGuidList = responseInJsonPath.get("$.[?(@.organizations ==0)].userGuid");
Invalid JSON expression:
Script1.groovy: 1: unexpected token: [ @ line 1, column 27.
                            [?(@.organizations ==0)].userGuid

**Comment by ycherrak** [comment]
@ChawlaS-ELS-CT:
I guess it will be something like:
`$.find { it.organization == 0}.userGuid`
in your case
