### ISSUE TITLE
Few of the Integer values in response are parsed as BigDecimal

### ISSUE THREAD

**Issue by vmasule** [rest-assured/rest-assured#973]
**Actual API Response without Rest-Assured:** 

`{
    "userID": 9,
    "dateStarted": "2016-10-27T00:00:00.0+01:00",
    "dateLeft": null,
    "statusID": 2,
    "statusDescription": "Current",
    "homeAddress": "sample string 1",
    "titleID": 1
}`

**Below is the code to call API and to get response:**

`
Response response = requestSpecification
                .when().get("https://holcahost:8080/app/getUserHistory")
                .thenReturn();
`
**Have also tried with below configuration:**

`
Response response = requestSpecification
.config(RestAssured.config().jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.BIG_INTEGER)))
                .when().get("https://holcahost:8080/app/getUserHistory")
                .thenReturn();
`
**Rest-Assured Response:** 
`{
    "userID": 9.0,
    "dateStarted": "2016-10-27T00:00:00.0+01:00",
    "dateLeft": null,
    "statusID": 2,
    "statusDescription": "Current",
    "homeAddress": "sample string 1",
    "titleID": 1.0
}`

**Assertions Error:**

`Expected: is <9>
  Actual: 9.0`

API Version: 3.0.6
It is parsing 9 to 9.0 and 1 to 1.0 but statusID is correctly parsed , Any help will be appreciated.

**Comment by johanhaleby** [comment]
What does your assertion looks like?

**Comment by vmasule** [comment]
@johanhaleby I have tried below two options.

.then().body("userID", Matchers.equalTo(9)) -- This is as mentioned in Docs

AND

Assert.assertEquals("userID match with user profile response", 9, response.jsonPath().get("userID"));

But both fail as `userID` is response shows 9.0 instead 9

**Comment by vmasule** [comment]
@johanhaleby Any updates on this.

**Comment by johanhaleby** [comment]
You need to be vary of the JSON type. 

```java
.then().body("userID", Matchers.equalTo(9))
```

means that userID must be an int, instead try:

```java
.then().body("userID", Matchers.equalTo(9.0))
```

Not much REST Assured could/should do about the error messages since they are produced by Hamcrest.

**Comment by adrian05** [comment]
It looks to me like this solution is just a dirty workaround. I expect Integers in the body but RestAssured gives me floats/doubles. In my case I use Matchers that compare the response body with an expected json file and it fails for some Integers too seeing them as float (even though Postman or other simmilar tools retrieve the values as Integers as they are stored in the database)
