### ISSUE TITLE
Custom logging output 

### ISSUE THREAD

**Issue by znevrly** [rest-assured/rest-assured#981]
Hi,
first of all, thank you for great effort making this awesome framework 👍 

I have question about quite annoying thing related to RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();

It works perfectly but usually I have quite long request body and response body and stacktrace is at the end of console output. **I would like to have custom ouput** where response body and stacktrace its on top. Is there any way how to achieve it?

Thank you.

**Comment by johanhaleby** [comment]
Logging is just implemented using a filter so you can roll your own LoggingFilter which does exactly what you're after. See the `io.restassured.filter.log.RequestLoggingFilter` and `io.restassured.filter.log.ResponseLoggingFilter` for inspiration.

**Comment by gustahrodrigues** [comment]
I was looking for something similar and I've found [Failure config](https://github.com/rest-assured/rest-assured/wiki/Usage#failure-config). It works as expected.
