### ISSUE TITLE
How to assert the json body response look likje 

### ISSUE THREAD

**Issue by kishorekumarl** [rest-assured/rest-assured#982]
Hi guys 
I need a help on asserted the  json body and json response look like 
{
"Code":"123456",
"seatcode":"1",
"pricelist":"5.00",
}
how to assert the response  ?

**Comment by anderfsilva** [comment]
You could try something like this:
```
import static org.hamcrest.Matchers.is;
...
.body(
    "Code", is("123456"),
    "seatcode", is("1"),
    "pricelist", is("5.00"));
```

**Comment by kishorekumarl** [comment]
@anderfsilva  Thanks for the update

**Comment by kobbikobb** [comment]
@kishorekumarl why is this issue still open?

**Comment by johanhaleby** [comment]
@kobbikobb I'm going to close it, thanks for bringing it to my attention.

**Comment by kishorekumarl** [comment]
Yes, it fixed
Thanks for everyone support.

Regards
L.Kishore Kumar
