### ISSUE TITLE
Not able to send Patch/Get request using Rest Assured when it has Authorization key as sid from the browser cookie

### ISSUE THREAD

**Issue by it-shivani** [rest-assured/rest-assured#983]
Hi,

I am trying to send a simple patch request with Authorization key in the request parameter is sid from my session cookie.

This request works completely fine with any of the API tools - Postman, Insomnia and some online REST API tool as well. It only does not work with Rest Assured. 

Also tried using Get request with similar request header to see if the issue is with Patch call or how the headers are interpreted. But Get did not work as well.

I am really stuck for many days with this issue. It would be great help if you can help solve this. 

Looking at your comments in previous issues I tried using wireshark but my session is https and also I was not able to work around with that tool. If you let me know some other way to validate the exact request body and header send by my rest assured request that may be that  help figuring out the solution. 

Thanks in advance.

**Comment by johanhaleby** [comment]
Please use the mailing list
