### ISSUE TITLE
HTTPS call returns 500 instead of 200, why logged curl has -k option

### ISSUE THREAD

**Issue by BeginnerRA** [rest-assured/rest-assured#998]
hello there

this code returns 500 instead of 200
RestAssured.baseURI = "https://myintenraldomain/version";
io.restassured.config.RestAssuredConfig config = CurlLoggingRestAssuredConfigFactory.createConfig();  

			given()
			.config(config)
			.header("x-id","XXXXXXXXXXXXXX")
			.header("Authorization",token)
			.header("Accept","*/*")
			.when().get()
			.then()
			.assertThat().statusCode(200).log().all();

the Log shows the curl 

curl 'https://myintenraldomain/version' -H 'Accept: */*' -H 'Host: myintenraldomain' -H 'Connection: Keep-Alive' -H 'User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_131)' --compressed -k -v

If i remove -k in curl option it works fine
but how do i get this removed

How to avoid this?

**Comment by johanhaleby** [comment]
`-k` in curl means insecure so you might want to try [relaxed https validation](https://github.com/rest-assured/rest-assured/wiki/Usage#ssl).

Please use the mailing list when asking questions in the future.
